<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\InformasiBerkala;
use App\Models\InformasiSertaMerta;
use App\Models\InformasiSetiapSaat;
use App\Models\DaftarInformasi;

class Dip2026SyncSeeder extends Seeder
{
    /**
     * Sinkronisasi Bersih Resmi DIP 2026 Langsung dari Tautan Google Drive DAFTAR SIAP TAYANG.xlsx
     * - Memuat seluruh Kategori Resmi: PROFIL, TATA CARA / PROSEDUR, PENGADAAN, KINERJA & KEUANGAN, PROGRAM DAN KEGIATAN
     * - Menggunakan Tautan Google Drive Langsung dari Excel (Tidak menggunakan file lokal sehingga anti-404)
     * - PERMANEN: TABEL DOKUMENS (LAPORAN LAYANAN) & PEJABAT TIDAK DISENTUH SAMA SEKALI!
     */
    public function run(): void
    {
        InformasiBerkala::truncate();
        InformasiSertaMerta::truncate();
        InformasiSetiapSaat::truncate();
        DaftarInformasi::truncate();

        // PENTING: Dokumen (Laporan Layanan) & Pejabat TIDAK DISENTUH SAMA SEKALI
        // agar seluruh edit manual user di admin panel tetap utuh dan 100% permanen!

        // 1. SEED INFORMASI BERKALA (PROFIL, TATA CARA, PENGADAAN, KINERJA, PROGRAM)
        $berkalaItems = [
            [
                'judul' => 'Profil Politeknik Keselamatan Transportasi Jalan (PKTJ) Tegal',
                'ringkasan' => 'Informasi komprehensif mengenai kedudukan, alamat domisili kampus, kontak resmi, profil kelembagaan, tugas pokok dan fungsi, serta visi dan misi PKTJ Tegal.',
                'pejabat' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggungjawab' => 'Bagian Keuangan dan Umum',
                'bentuk' => 'Hardcopy & Softcopy',
                'waktu' => 'Tegal, 2025/2026',
                'retensi' => '1 Tahun',
                'file_path' => '/profil/profil-ppid',
                'file_name' => 'Profil PKTJ Tegal',
                'tipe_informasi' => 'PROFIL',
                'aktif' => true,
            ],
            [
                'judul' => 'Profil PPID Pelaksana UPT PKTJ Tegal',
                'ringkasan' => 'Profil kelembagaan Pejabat Pengelola Informasi dan Dokumentasi (PPID) Pelaksana Politeknik Keselamatan Transportasi Jalan Tegal.',
                'pejabat' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggungjawab' => 'Tim PPID dan Humas',
                'bentuk' => 'Hardcopy & Softcopy',
                'waktu' => 'Tegal, 2025/2026',
                'retensi' => '1 Tahun',
                'file_path' => '/profil/profil-ppid',
                'file_name' => 'Profil PPID PKTJ',
                'tipe_informasi' => 'PROFIL',
                'aktif' => true,
            ],
            [
                'judul' => 'Struktur Organisasi di lingkungan PKTJ Tegal',
                'ringkasan' => 'Bagan struktur organisasi tata kelola pimpinan institusi, jurusan, program studi, unit pelaksana teknis, serta struktur tim pengelola PPID Pelaksana PKTJ Tegal.',
                'pejabat' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggungjawab' => 'Bagian Keuangan dan Umum',
                'bentuk' => 'Hardcopy & Softcopy',
                'waktu' => 'Tegal, 2025/2026',
                'retensi' => '1 Tahun',
                'file_path' => '/profil/struktur-organisasi',
                'file_name' => 'Struktur Organisasi PKTJ',
                'tipe_informasi' => 'PROFIL',
                'aktif' => true,
            ],
            [
                'judul' => 'Profil Singkat Pejabat Publik PKTJ Tegal',
                'ringkasan' => 'Biografi ringkas, rekam jejak pengabdian, riwayat pendidikan formal, dan jabatan Direktur, para Wakil Direktur, dan Kepala Bagian di lingkungan PKTJ Tegal.',
                'pejabat' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggungjawab' => 'Bagian Keuangan dan Umum',
                'bentuk' => 'Hardcopy & Softcopy',
                'waktu' => 'Tegal, 2025/2026',
                'retensi' => '1 Tahun',
                'file_path' => '/profil/profil-pejabat',
                'file_name' => 'Profil Singkat Pejabat PKTJ',
                'tipe_informasi' => 'PROFIL',
                'aktif' => true,
            ],
            [
                'judul' => 'Laporan Harta Kekayaan Pejabat Negara (LHKPN)',
                'ringkasan' => 'Rekapitulasi tanda terima dan bukti kepatuhan pelaporan e-LHKPN bagi para pejabat penyelenggara negara di lingkungan PKTJ Tegal.',
                'pejabat' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggungjawab' => 'Bagian Keuangan dan Umum',
                'bentuk' => 'Hardcopy & Softcopy',
                'waktu' => 'Tegal, 2025/2026',
                'retensi' => '1 Tahun',
                'file_path' => '/profil/profil-pejabat',
                'file_name' => 'LHKPN Pejabat PKTJ',
                'tipe_informasi' => 'PROFIL',
                'aktif' => true,
            ],
            [
                'judul' => 'Visi dan Misi PKTJ Tegal',
                'ringkasan' => 'Visi dan misi resmi Politeknik Keselamatan Transportasi Jalan dalam mewujudkan pendidikan tinggi vokasi transportasi jalan yang berstandar internasional.',
                'pejabat' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggungjawab' => 'Bagian Keuangan dan Umum',
                'bentuk' => 'Hardcopy & Softcopy',
                'waktu' => 'Tegal, 2025/2026',
                'retensi' => '1 Tahun',
                'file_path' => '/profil/visi-misi',
                'file_name' => 'Visi dan Misi PKTJ',
                'tipe_informasi' => 'PROFIL',
                'aktif' => true,
            ],
            [
                'judul' => 'Tugas Pokok, Fungsi, dan Tanggung Jawab PPID',
                'ringkasan' => 'Rincian tugas pokok, wewenang, fungsi, dan tanggung jawab PPID Pelaksana UPT PKTJ Tegal dalam pengelolaan dan pelayanan informasi publik.',
                'pejabat' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggungjawab' => 'Tim PPID dan Humas',
                'bentuk' => 'Hardcopy & Softcopy',
                'waktu' => 'Tegal, 2025/2026',
                'retensi' => '1 Tahun',
                'file_path' => '/profil/tugas-dan-fungsi-ppid',
                'file_name' => 'Tupoksi PPID PKTJ',
                'tipe_informasi' => 'PROFIL',
                'aktif' => true,
            ],
            [
                'judul' => 'Agenda Pimpinan PKTJ Tegal',
                'ringkasan' => 'Jadwal kegiatan kedinasan, kunjungan kerja, dan audiensi resmi Direktur beserta jajaran manajemen pimpinan PKTJ Tegal.',
                'pejabat' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggungjawab' => 'Bagian Keuangan dan Umum',
                'bentuk' => 'Hardcopy & Softcopy',
                'waktu' => 'Tegal, 2025/2026',
                'retensi' => '1 Tahun',
                'file_path' => '/profil/profil-ppid',
                'file_name' => 'Agenda Pimpinan PKTJ',
                'tipe_informasi' => 'PROFIL',
                'aktif' => true,
            ],
            [
                'judul' => 'Statistik Data Kepegawaian PKTJ Tegal',
                'ringkasan' => 'Data statistik dan rekapitulasi jumlah dosen tetap, instruktur, pranata laboratorium, dan tenaga kependidikan ASN maupun PPNPN di PKTJ Tegal.',
                'pejabat' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggungjawab' => 'Bagian Keuangan dan Umum',
                'bentuk' => 'Hardcopy & Softcopy',
                'waktu' => 'Tegal, 2025/2026',
                'retensi' => '1 Tahun',
                'file_path' => '/informasi-publik/statistik-pegawai',
                'file_name' => 'Statistik Kepegawaian',
                'tipe_informasi' => 'PROFIL',
                'aktif' => true,
            ],
            [
                'judul' => 'Standar Pelayanan PPID PKTJ',
                'ringkasan' => 'Standar operasional pelayanan informasi publik meliputi persyaratan, alur, jangka waktu pemenuhan permohonan informasi, serta hak dan kewajiban pemohon informasi.',
                'pejabat' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggungjawab' => 'Bagian Keuangan dan Umum',
                'bentuk' => 'Hardcopy & Softcopy',
                'waktu' => 'Tegal, 2025/2026',
                'retensi' => 'Selama Berlaku',
                'file_path' => '/layanan-informasi/maklumat-dan-standar-biaya-layanan',
                'file_name' => 'Standar Pelayanan PPID',
                'tipe_informasi' => 'TATA CARA / PROSEDUR',
                'aktif' => true,
            ],
            [
                'judul' => 'Maklumat Pelayanan PPID PKTJ',
                'ringkasan' => 'Pernyataan kesanggupan dan komitmen segenap jajaran pengelola PPID PKTJ untuk memberikan pelayanan informasi publik secara tepat waktu, transparan, dan akuntabel.',
                'pejabat' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggungjawab' => 'PPID Pelaksana UPT PKTJ Tegal',
                'bentuk' => 'Hardcopy & Softcopy',
                'waktu' => 'Tegal, 2025/2026',
                'retensi' => 'Selama Berlaku',
                'file_path' => '/layanan-informasi/maklumat-dan-standar-biaya-layanan',
                'file_name' => 'Maklumat Pelayanan PPID',
                'tipe_informasi' => 'TATA CARA / PROSEDUR',
                'aktif' => true,
            ],
            [
                'judul' => 'Tata cara permohonan informasi publik',
                'ringkasan' => 'Panduan prosedur dan tata cara permohonan informasi publik ke desk PPID PKTJ secara online melalui formulir daring atau permohonan langsung ke kantor layanan.',
                'pejabat' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggungjawab' => 'PPID Pelaksana UPT PKTJ Tegal',
                'bentuk' => 'Hardcopy & Softcopy',
                'waktu' => 'Tegal, 2025/2026',
                'retensi' => 'Selama Berlaku',
                'file_path' => '/prosedur/permintaan-informasi',
                'file_name' => 'Tata Cara Permohonan Informasi',
                'tipe_informasi' => 'TATA CARA / PROSEDUR',
                'aktif' => true,
            ],
            [
                'judul' => 'Tata cara mengajukan keberatan informasi publik',
                'ringkasan' => 'Prosedur pengajuan keberatan kepada Atasan PPID apabila pemohon informasi publik tidak memperoleh tanggapan atau tanggapan tidak sesuai ketentuan.',
                'pejabat' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggungjawab' => 'PPID Pelaksana UPT PKTJ Tegal',
                'bentuk' => 'Hardcopy & Softcopy',
                'waktu' => 'Tegal, 2025/2026',
                'retensi' => 'Selama Berlaku',
                'file_path' => '/prosedur/penanganan-keberatan',
                'file_name' => 'Tata Cara Keberatan Informasi',
                'tipe_informasi' => 'TATA CARA / PROSEDUR',
                'aktif' => true,
            ],
            [
                'judul' => 'Tata cara penyelesaian sengketa informasi publik',
                'ringkasan' => 'Mekanisme dan tahapan pengajuan sengketa informasi publik ke Komisi Informasi Pusat (KIP) apabila upaya keberatan tidak tercapai kesepakatan.',
                'pejabat' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggungjawab' => 'PPID Pelaksana UPT PKTJ Tegal',
                'bentuk' => 'Hardcopy & Softcopy',
                'waktu' => 'Tegal, 2025/2026',
                'retensi' => 'Selama Berlaku',
                'file_path' => '/prosedur/sengketa-informasi',
                'file_name' => 'Tata Cara Sengketa Informasi',
                'tipe_informasi' => 'TATA CARA / PROSEDUR',
                'aktif' => true,
            ],
            [
                'judul' => 'Tata cara pengaduan masyarakat (Whistleblowing System & LAPOR!)',
                'ringkasan' => 'Saluran resmi pengaduan masyarakat atas dugaan penyalahgunaan wewenang, pelanggaran etika, atau ketidakpuasan layanan melalui portal SP4N-LAPOR! dan WBS Kemenhub.',
                'pejabat' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggungjawab' => 'Satuan Pengawas Internal (SPI)',
                'bentuk' => 'Softcopy (Online Portal)',
                'waktu' => 'Tegal, 2025/2026',
                'retensi' => 'Selama Berlaku',
                'file_path' => 'https://www.lapor.go.id/',
                'file_name' => 'Portal SP4N-LAPOR',
                'tipe_informasi' => 'TATA CARA / PROSEDUR',
                'aktif' => true,
            ],
            [
                'judul' => 'Laporan Tahunan Layanan Informasi Publik PKTJ Tahun 2025',
                'ringkasan' => 'Laporan tahunan pelaksanaan pelayanan informasi publik dan keterbukaan informasi PPID Pelaksana UPT Politeknik Keselamatan Transportasi Jalan Tahun 2025.',
                'pejabat' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggungjawab' => 'Tim PPID dan Humas',
                'bentuk' => 'Hardcopy & Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '1 Tahun',
                'file_path' => '/layanan-informasi/laporan',
                'file_name' => 'Laporan Tahunan PPID 2025',
                'tipe_informasi' => 'KINERJA DAN KEUANGAN',
                'aktif' => true,
            ],
            [
                'judul' => 'Laporan Akses Layanan Informasi Publik dan Rekapitulasi Medsos TA 2026',
                'ringkasan' => 'Rekapitulasi log bulanan permohonan informasi dan pertanyaan masuk di kanal media sosial resmi Politeknik Keselamatan Transportasi Jalan Tahun Berjalan 2026.',
                'pejabat' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggungjawab' => 'Tim PPID dan Humas',
                'bentuk' => 'Hardcopy & Softcopy',
                'waktu' => 'Tegal, 2026',
                'retensi' => '1 Tahun',
                'file_path' => '/layanan-informasi/laporan-akses',
                'file_name' => 'Laporan Akses PPID 2026',
                'tipe_informasi' => 'KINERJA DAN KEUANGAN',
                'aktif' => true,
            ],
            [
                'judul' => 'Laporan Survei Kepuasan Masyarakat (IKM) PKTJ',
                'ringkasan' => 'Laporan berkala hasil survei kepuasan masyarakat (IKM) terhadap pelayanan informasi publik di Politeknik Keselamatan Transportasi Jalan Tegal.',
                'pejabat' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggungjawab' => 'Bagian Keuangan dan Umum',
                'bentuk' => 'Hardcopy & Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '1 Tahun',
                'file_path' => '/layanan-informasi/laporan-survey',
                'file_name' => 'Laporan Survei IKM PKTJ',
                'tipe_informasi' => 'KINERJA DAN KEUANGAN',
                'aktif' => true,
            ],
            [
                'judul' => 'Ringkasan Eksekutif Laporan Kinerja Instansi Pemerintah (LKjIP / LAKIP) PKTJ Tahun 2025',
                'ringkasan' => 'Ringkasan eksekutif akuntabilitas kinerja instansi pemerintah (LKjIP) PKTJ Tahun 2025 yang merangkum pencapaian Indikator Kinerja Utama (IKU).',
                'pejabat' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggungjawab' => 'Bagian Keuangan dan Umum',
                'bentuk' => 'Hardcopy & Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '1 Tahun',
                'file_path' => 'https://drive.google.com/file/d/18azvUjvumzPkAN-hTmSWhkWaJrXZFle3/view?usp=drive_link',
                'file_name' => 'Ringkasan_Eksekutif_LKjIP_PKTJ_2025.pdf',
                'tipe_informasi' => 'KINERJA DAN KEUANGAN',
                'aktif' => true,
            ],
            [
                'judul' => 'DIPA Petikan PKTJ Tegal Tahun Anggaran 2025',
                'ringkasan' => 'Alokasi anggaran DIPA Petikan Politeknik Keselamatan Transportasi Jalan Tahun Anggaran 2025.',
                'pejabat' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggungjawab' => 'Bagian Keuangan dan Umum',
                'bentuk' => 'Hardcopy & Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '1 Tahun',
                'file_path' => 'https://drive.google.com/file/d/18azvUjvumzPkAN-hTmSWhkWaJrXZFle3/view?usp=drive_link',
                'file_name' => 'DIPA_PKTJ_2025_Revisi_08.pdf',
                'tipe_informasi' => 'KINERJA DAN KEUANGAN',
                'aktif' => true,
            ],
            [
                'judul' => 'Rencana Umum Pengadaan (SiRUP) PKTJ Tegal',
                'ringkasan' => 'Pengumuman Rencana Umum Pengadaan (RUP) penyedia barang dan jasa pemerintah di lingkungan PKTJ Tegal melalui portal resmi SiRUP Lembaga Kebijakan Pengadaan Barang/Jasa Pemerintah (LKPP).',
                'pejabat' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggungjawab' => 'PPK / Bagian Keuangan dan Umum',
                'bentuk' => 'Softcopy (Online Portal)',
                'waktu' => 'Tegal, 2025/2026',
                'retensi' => '1 Tahun',
                'file_path' => 'https://sirup.lkpp.go.id/',
                'file_name' => 'Portal SiRUP LKPP',
                'tipe_informasi' => 'PENGADAAN BARANG DAN JASA',
                'aktif' => true,
            ],
            [
                'judul' => 'Pengumuman Pengadaan Pemilihan Penyedia Barang dan Jasa (LPSE) PKTJ',
                'ringkasan' => 'Daftar pengumuman tender terbuka, seleksi umum, e-purchasing, dan pengadaan barang/jasa satuan kerja PKTJ Tegal melalui Layanan Pengadaan Secara Elektronik (LPSE) Kementerian Perhubungan.',
                'pejabat' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggungjawab' => 'Pokja Pemilihan / UKPBJ',
                'bentuk' => 'Softcopy (Online Portal)',
                'waktu' => 'Tegal, 2025/2026',
                'retensi' => '1 Tahun',
                'file_path' => 'https://lpse.dephub.go.id/',
                'file_name' => 'Portal LPSE Kemenhub',
                'tipe_informasi' => 'PENGADAAN BARANG DAN JASA',
                'aktif' => true,
            ],
            [
                'judul' => 'Informasi Penerimaan Calon Taruna (SIPENCATAR) PKTJ',
                'ringkasan' => 'Portal dan informasi resmi alur seleksi penerimaan calon taruna/i (SIPENCATAR) Kementerian Perhubungan di lingkungan Politeknik Keselamatan Transportasi Jalan Tegal.',
                'pejabat' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggungjawab' => 'Bagian Administrasi Akademik dan Ketarunaan',
                'bentuk' => 'Softcopy (Online Portal)',
                'waktu' => 'Tegal, 2025/2026',
                'retensi' => '1 Tahun',
                'file_path' => 'https://pktj.ac.id/pages/informasi-sipencatar',
                'file_name' => 'Portal SIPENCATAR',
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => true,
            ],
            [
                'judul' => 'INFORMASI',
                'ringkasan' => 'RINGKASAN INFORMASI',
                'pejabat' => 'PEJABAT YANG
MENGUASAI INFORMASI',
                'penanggungjawab' => 'PENERBIT INFORMASI',
                'bentuk' => 'BENTUK
INFORMASI
YANG TERSEDIA',
                'waktu' => 'TEMPAT DAN
WAKTU PEMBUATAN',
                'retensi' => 'JANGKA WAKTU
PENYIMPANAN
DAN RETEN WAKTU',
                'file_path' => null,
                'file_name' => null,
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => false,
            ],
            [
                'judul' => 'Akreditasi Prodi',
                'ringkasan' => 'Dokumen Laporan Evaluasi Diri Program Studi (LED), dan Laporan Kinerja Program Studi (LKPS) Prodi RSTJ, TRO, TO yang di Upload pada sistem SAKTI Lam Teknik untuk Akreditasi Prodi',
                'pejabat' => 'Ka SPM',
                'penanggungjawab' => 'Tim SPM dan masing-masing Prodi',
                'bentuk' => 'Soft Copy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '5 tahun',
                'file_path' => 'https://drive.google.com/file/d/1rvltyYA70k88Icn1dUpuyD9jpSlhhdDY/view?usp=drive_link',
                'file_name' => 'Salinan led_211432025 (Informasi Publik) RSTJ_TERSENSOR.pdf',
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => true,
            ],
            [
                'judul' => 'Audit Mutu Internal',
                'ringkasan' => 'Audit Mutu Internal Tahun 2025 yang dilakukan oleh Auditor internal kepada masing-masing bagian atau Auditee',
                'pejabat' => 'Ka SPM',
                'penanggungjawab' => 'Tim SPM dan Auditor',
                'bentuk' => 'Soft Copy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '2 tahun',
                'file_path' => 'https://drive.google.com/file/d/1k9sOdvKbToFwcTiE2McZ2B73KO0_4fkY/view?usp=drive_link',
                'file_name' => 'LAPORAN AMI 2025_TERSENSOR.pdf',
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => true,
            ],
            [
                'judul' => 'Jadwal Perkuliahan',
                'ringkasan' => 'Membahas ploting dosen terlebih dahulu untuk penyusunan Jadwal Perkuliahan/ semester',
                'pejabat' => 'Kepala Progam Studi Teknologi Rekayasa Otomotif (TRO)',
                'penanggungjawab' => 'Prodi TRO Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '6 Bulan',
                'file_path' => null,
                'file_name' => null,
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => false,
            ],
            [
                'judul' => 'Jadwal Perkuliahan',
                'ringkasan' => 'Membahas ploting dosen terlebih dahulu untuk penyusunan Jadwal Perkuliahan/ semester',
                'pejabat' => 'Kepala Progam Studi Diploma III Teknologi Otomotif (TO)',
                'penanggungjawab' => 'Prodi Diploma III TO Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '6 Bulan',
                'file_path' => 'https://drive.google.com/file/d/1tY4S4T279H3GIRLw1Pkd96TBUZdNQrJS/view?usp=drive_link',
                'file_name' => 'Jadwal TO Semester Ganjil TA 2025-2026_TERSENSOR.pdf',
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => true,
            ],
            [
                'judul' => 'Laporan Kegiatan Kehumasan',
                'ringkasan' => 'Laporan kegitan dalam bentuk penerbitan berita melalu media sosial, website, dan media massa selama tahun 2025',
                'pejabat' => 'Kapokja PPID dan Humas',
                'penanggungjawab' => 'Tim Kerjasama',
                'bentuk' => 'softcopy dan hardcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '1 tahun',
                'file_path' => null,
                'file_name' => null,
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => false,
            ],
            [
                'judul' => 'Laporan Kegiatan Pengawasan Mutu dan Manajemen Sistem Penyelenggaraan Makanan',
                'ringkasan' => 'Laporan kegiatan pengawasan mutu dan manajemen sistem penyelenggawaan makanan, yang berisi evaluasi penyelenggaraan permakanan taruna selama tahun 2025',
                'pejabat' => 'Nutrisionis Terampil',
                'penanggungjawab' => 'Pusat Pembangunan Karakter',
                'bentuk' => 'Softfile',
                'waktu' => 'Tegal, 2025',
                'retensi' => '5 Tahun',
                'file_path' => 'https://drive.google.com/file/d/1lbc6mAZtkDVIkVrpsQg8uuYBn_FL33zn/view?usp=drive_link',
                'file_name' => 'Salinan 1. LAPORAN MSPM JANUARI_TERSENSOR.pdf',
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => true,
            ],
            [
                'judul' => 'Laporan Kegiatan Pengukuran Indeks Massa Tubuh (IMT) Taruna Tahun 2025',
                'ringkasan' => 'Laporan kegiatan pengukuran Indeks Massa Tubuh (IMT) yang berisi hasil pengukuran Indeks Massa Tubuh (IMT) Taruna pada Semester 1 dan Semester 2 Tahun 2025',
                'pejabat' => 'Nutrisionis Terampil',
                'penanggungjawab' => 'Pusat Pembangunan Karakter',
                'bentuk' => 'Softfile',
                'waktu' => 'Tegal, 2025',
                'retensi' => '5 Tahun',
                'file_path' => 'https://drive.google.com/file/d/1AzLms44HlcLDJncxnUcDV_wFZZOgxdch/view?usp=drive_link',
                'file_name' => 'Salinan 1. Laporan Kegiatan IMT Maret 2025_TERSENSOR.pdf',
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => true,
            ],
            [
                'judul' => 'Laporan Kegiatan Softkill Taruna Tahun 2025',
                'ringkasan' => 'Laporan kegiatan softkill taruna tentang literasi kesehatan mental tahun 2025',
                'pejabat' => 'Pengasuh Praja',
                'penanggungjawab' => 'Pusat Pembangunan Karakter',
                'bentuk' => 'Softfile',
                'waktu' => 'Tegal, 2025',
                'retensi' => '5 Tahun',
                'file_path' => null,
                'file_name' => null,
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => false,
            ],
            [
                'judul' => 'Laporan Keuangan PKTJ Tegal',
                'ringkasan' => 'Laporan Realisasi Anggaran (LRA), neraca, Laporan Operasional, Laporan Perubahan Ekuitas dan Catatan atas Laporan Keuangan PKTJ Tegal yang telah di audit oleh BPK-RI',
                'pejabat' => 'Ketua Tim Substansi Bidang Keuangan',
                'penanggungjawab' => 'Bagian Keuangan',
                'bentuk' => 'softcopy dan hardcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '1 (satu) tahun',
                'file_path' => null,
                'file_name' => null,
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => false,
            ],
            [
                'judul' => 'Laporan Penilian Samapta Periodik Taruna Tahun 2025',
                'ringkasan' => 'Laporan penilaian samapta periodik berisi hasil penilaian samapta atau kebugaran jasmani taruna yang dilakukan pada semester ganjil dan semester genap tahun 2025',
                'pejabat' => 'Pengasuh Praja',
                'penanggungjawab' => 'Pusat Pembangunan Karakter',
                'bentuk' => 'Softfile',
                'waktu' => 'Tegal, 2025',
                'retensi' => '5 Tahun',
                'file_path' => 'https://drive.google.com/file/d/1dklOY3q0RlCz6m-NTLlgjwG1mG1anUrk/view?usp=drive_link',
                'file_name' => 'Salinan 1. LAPORAN HASIL TES KESAMAPTAAN TARUNA SEMESTER GANJIL_TERSENSOR.pdf',
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => true,
            ],
            [
                'judul' => 'Laporan Perkuliahan Semester Ganjil',
                'ringkasan' => 'Pelaksanaan Pembelajaran semester genap dimulai bulan maret s.d bulan Juli 2025',
                'pejabat' => 'Kepala Progam Studi Rekayasa Sistem Transportasi Jalan (RSTJ)',
                'penanggungjawab' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '6 bulan',
                'file_path' => null,
                'file_name' => null,
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => false,
            ],
            [
                'judul' => 'Laporan Perkuliahan Semester Genap',
                'ringkasan' => 'Laporan Perkuliahan Semester Genap',
                'pejabat' => 'Kepala Program Studi RSTJ',
                'penanggungjawab' => 'Program Studi RSTJ',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => 'selama masih berlaku',
                'file_path' => 'https://drive.google.com/file/d/1whVnOxu2OAIrLjGQOi4UVnSODDvWSFtN/view?usp=drive_link',
                'file_name' => 'Laporan Perkuliahan Semester Genap 2024_2025 (Informasi Publik) TERSENSOR.pdf',
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => true,
            ],
            [
                'judul' => 'Laporan Permohonan Informasi Publik',
                'ringkasan' => 'Laporan Permohonan Informasi Publik',
                'pejabat' => 'Kapokja PPID dan Humas',
                'penanggungjawab' => 'Tim Kerjasama',
                'bentuk' => 'softcopy dan hardcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '1 tahun',
                'file_path' => null,
                'file_name' => null,
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => false,
            ],
            [
                'judul' => 'Laporan Tracer Study 2025',
                'ringkasan' => 'Laporan ini merupakan hasil dari kegiatan tracer study yang dilaksanakan
terhadap lulusan tahun 2024 dan 2023 dari tiga program studi, yaitu Sarjana Terapan
Rekayasa Sistem Transportasi Jalan (RSTJ), Sarjana Terapan Teknologi Rekayasa
Otomotif (TRO), dan Diploma III Teknologi Otomotif (TO).',
                'pejabat' => 'Katim Substansi Bidang Administrasi Ketarunaan dan Alumni',
                'penanggungjawab' => 'Tim Administrasi Ketarunaan dan Alumni',
                'bentuk' => 'softcopy dan hardcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '5 (lima) tahun',
                'file_path' => 'https://drive.google.com/file/d/1Z03rj5TTeSRbyoJbvoI1OVNeHDeJnmr2/view?usp=drive_link',
                'file_name' => 'Laporan Tracer Study 2025 (fix) (InformasI Publik)_TERSENSOR.pdf',
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => true,
            ],
            [
                'judul' => 'Laporan pelaksanaan seminar hasil',
                'ringkasan' => 'Dijalankan saat taruna melaksanakan magang 1 dan membuat laporan magang juga menyusun proposal Tugas Akhir, data di ambil saat melaksanakan magang 1',
                'pejabat' => 'Kepala Program Studi RSTJ',
                'penanggungjawab' => 'Prodi RSTJ PKTJ',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal 2025',
                'retensi' => '3 Bulan',
                'file_path' => null,
                'file_name' => null,
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => false,
            ],
            [
                'judul' => 'Laporan pelaksanaan seminar proposal',
                'ringkasan' => 'Dijalankan saat taruna di semester 5',
                'pejabat' => 'Kepala Progam Studi Diploma III Teknologi Otomotif (TO)',
                'penanggungjawab' => 'Prodi Diploma III TO Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '3 Bulan',
                'file_path' => null,
                'file_name' => null,
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => false,
            ],
            [
                'judul' => 'Laporan pelaksanaan seminar proposal',
                'ringkasan' => 'Dijalankan saat taruna melaksanakan magang 1 dan membuat laporan magang juga menyusun proposal Tugas Akhir, data di ambil saat melaksanakan magang 1',
                'pejabat' => 'Kepala Progam Studi Teknologi Rekayasa Otomotif (TRO)',
                'penanggungjawab' => 'Prodi TRO Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '3 Bulan',
                'file_path' => null,
                'file_name' => null,
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => false,
            ],
            [
                'judul' => 'Pelaksanaan Ujikom Andalalin',
                'ringkasan' => 'Diawali dengan kegiatan Pra Ujikom Penilai Andalalin pd tgl 14 s.d 15 Agustus 2025dan di lanjutkan dengan Ujikom Penilai Andalalin pd tgl 19 s.d 21 Agustus 2025',
                'pejabat' => 'Kepala Progam Studi Rekayasa Sistem Transportasi Jalan (RSTJ)',
                'penanggungjawab' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '12 bulan',
                'file_path' => 'https://drive.google.com/file/d/1hgqfwqJATIAUnQMK89_WqFOsXvgNyxLq/view?usp=drive_link',
                'file_name' => 'laporan ujikom andalalin 2025 (Informasi Publik)_TERSENSOR.pdf',
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => true,
            ],
            [
                'judul' => 'Pelaksanaan Ujikom Pembantu PKB',
                'ringkasan' => 'Diawali dengan kegiatan Pra Ujikom Pembantu PKB pd tgl 13 s.d 15 dan di lanjutkan dengan Ujikom Pembantu PKB pd tgl 19 s.d 21 Agustus 2025 yang diikuti oleh 31 Mahasiswa/i Mandiri',
                'pejabat' => 'Kepala Progam Studi Teknologi Rekayasa Otomotif (TRO)',
                'penanggungjawab' => 'Prodi TRO Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '1 Tahun',
                'file_path' => 'https://drive.google.com/file/d/1bkVuYjckwiflyopuFsEhQn75Jr3KUAmn/view?usp=drive_link',
                'file_name' => 'Laporan Ujikom Pembantu PKB Tahun 2025 (Informasi Publik) TERSENSOR.pdf',
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => true,
            ],
            [
                'judul' => 'Pelaksanaan Ujikom Pemeliharaan Jalan',
                'ringkasan' => 'Diawali dengan kegiatan Pelatihan Pemeliharaan Jalan pd tgl 15 Agustus 2025 dan di lanjutkan dengan Ujikom/Assesment Pemeliharaan Jalan pd tgl 28 Agustus 2025',
                'pejabat' => 'Kepala Progam Studi Rekayasa Sistem Transportasi Jalan (RSTJ)',
                'penanggungjawab' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '12 bulan',
                'file_path' => 'https://drive.google.com/file/d/1NhA8-ImFldPpGCTGJm0YzEnmSK4zgJnn/view?usp=drive_link',
                'file_name' => 'Salinan LaporanPKS_Laporan_uji Kompetensi Peneliharaan Jalan (Informasi Publik)_TERSENSOR.pdf',
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => true,
            ],
            [
                'judul' => 'Pelaksanaan Ujikom Penguji Berkala Kendaraan Bermotor Tingkat 3',
                'ringkasan' => 'Diawali dengan kegiatan Pra Ujikom Penguji Berkala Kendaraan Bermotor Tingkat 3 pd tgl 25 s.d 28 dan di lanjutkan dengan Ujikom Penguji Berkala Kendaraan Bermotor Tingkat 3 pd tgl 11 s.d 18 Agustus 2025 yang diikuti oleh 106 Mahasiswa/i D3 TO POLBIT dan NoN POLBIT',
                'pejabat' => 'Kepala Progam Studi Diploma III Teknologi Otomotif (TO)',
                'penanggungjawab' => 'Prodi Diploma III TO Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '1 Tahun',
                'file_path' => null,
                'file_name' => null,
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => false,
            ],
            [
                'judul' => 'Pelaksanaan Ujikom Sistem Manajemen Keselamatan',
                'ringkasan' => 'Diawali dengan kegiatan Pra Ujikom SMK pd tgl 13 s.d 14 dan di lanjutkan dengan Ujikom SMK pd tgl 18 s.d 19 Agustus 2025 yang diikuti oleh 57 Mahasiswa/i Pola Pembibitan (Polbit)',
                'pejabat' => 'Kepala Progam Studi Teknologi Rekayasa Otomotif (TRO)',
                'penanggungjawab' => 'Prodi TRO Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '1 Tahun',
                'file_path' => 'https://drive.google.com/file/d/13R7DxU7BzK53vXcvyDPZaGFA2HQvucVz/view?usp=drive_link',
                'file_name' => 'Laporan Ujikom SMK PAU 2025_fix (Informasi Publik)_TERSENSOR.pdf',
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => true,
            ],
            [
                'judul' => 'Pelaksanaan UTS dan UAS',
                'ringkasan' => 'Pelaksanaan mengikuti Kalender Akademik di dukung dengan 7x pertemuan pembelajaran, minimal 6x pertemuan untuk pelaksanaan kegiata UTS dan UAS 14x pertemuan',
                'pejabat' => 'Kepala Progam Studi Rekayasa Sistem Transportasi Jalan (RSTJ)',
                'penanggungjawab' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '6 bulan',
                'file_path' => 'https://drive.google.com/file/d/1skDjqrJrioh7lhKpvN1fAWYkSsqPKFj-/view?usp=drive_link',
                'file_name' => 'Salinan NOTA DINAS 86 (Informasi Publik)_TERSENSOR.pdf',
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => true,
            ],
            [
                'judul' => 'Pelaksanaan UTS dan UAS',
                'ringkasan' => 'Pelaksanaan mengikuti Kalender Akademik di dukung dengan 7x pertemuan pembelajaran, minimal 6x pertemuan untuk pelaksanaan kegiata UTS dan UAS 14x pertemuan',
                'pejabat' => 'Kepala Progam Studi Teknologi Rekayasa Otomotif (TRO)',
                'penanggungjawab' => 'Prodi TRO Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '6 Bulan',
                'file_path' => 'https://drive.google.com/file/d/1ez4_J3ZyLFN41OY-tBchy3W0k8AeOAAx/view?usp=drive_link',
                'file_name' => 'Nodin Pelaksanaan UAS Ganjil 25-26 (Informasi Publik)_TERSENSOR.pdf',
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => true,
            ],
            [
                'judul' => 'Pelaksanaan UTS dan UAS',
                'ringkasan' => 'Pelaksanaan mengikuti Kalender Akademik di dukung dengan 7x pertemuan pembelajaran, minimal 6x pertemuan untuk pelaksanaan kegiata UTS dan UAS 14x pertemuan',
                'pejabat' => 'Kepala Progam Studi Diploma III Teknologi Otomotif (TO)',
                'penanggungjawab' => 'Prodi Diploma III TO Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '6 Bulan',
                'file_path' => 'https://drive.google.com/file/d/1hlV5Ac65SPio7VLsn9E8Zvx5Deecatxe/view?usp=drive_link',
                'file_name' => 'Pengumuman UTS GANJIL 20252026 (Informasi Publik)_TERSENSOR.pdf',
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => true,
            ],
            [
                'judul' => 'Ploting dan jadwal Perkuliahan Semester Genap',
                'ringkasan' => 'Membahas ploting dosen terlebih dahulu untuk penyusunan Jadwal Perkuliahan/ semester',
                'pejabat' => 'Kepala Progam Studi Rekayasa Sistem Transportasi Jalan (RSTJ)',
                'penanggungjawab' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '6 bulann',
                'file_path' => null,
                'file_name' => null,
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => false,
            ],
            [
                'judul' => 'Rapat Tinjauan Manajemen',
                'ringkasan' => 'Risalah rapat tinjauan manajemen tahun 2025',
                'pejabat' => 'Ka SPM',
                'penanggungjawab' => 'Tim SPM',
                'bentuk' => 'Soft Copy dan Hard Copy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '1 tahun',
                'file_path' => null,
                'file_name' => null,
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => false,
            ],
            [
                'judul' => 'Rencana Kerja Tahunan (RKT) PKTJ Tegal Tahun 2025',
                'ringkasan' => 'Penjabaran dari sasaran dan
program yang telah ditetapkan dalam RENSTRA dan akan dilaksanakan oleh BPSDMP',
                'pejabat' => 'Ketua Tim Substansi Bidang Keuangan',
                'penanggungjawab' => 'Bagian Perencanaan',
                'bentuk' => 'softcopy dan hardcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '1 (satu) tahun',
                'file_path' => null,
                'file_name' => null,
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => false,
            ],
            [
                'judul' => 'Rencana Strategis (Renstra)',
                'ringkasan' => 'Rencana  Strategis (Renstra) PKTJ Tegal',
                'pejabat' => 'Ketua Tim Substansi Bidang Keuangan',
                'penanggungjawab' => 'Bagian Perencanaan',
                'bentuk' => 'softcopy dan hardcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '5 (lima) tahun',
                'file_path' => null,
                'file_name' => null,
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => false,
            ],
            [
                'judul' => 'Rencana Umum Pengadaan',
                'ringkasan' => 'Berisi dokumen daftar paket pekerjaan yang dilaksanakan dalam 1 (satu) Tahun  Anggaran',
                'pejabat' => 'Kepala Bagian Umum dan Keuangan',
                'penanggungjawab' => 'Bagian Umum dan Keuangan',
                'bentuk' => 'Soft Copy dan Hard Copy',
                'waktu' => 'Tegal, Tahun 2025',
                'retensi' => '1 Tahun',
                'file_path' => null,
                'file_name' => null,
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => false,
            ],
            [
                'judul' => 'Screening gigi kepada taruna/i PKTJ',
                'ringkasan' => 'Kegiatan screening gigi dilakukan secara rutin dan bertahap',
                'pejabat' => 'Kanit Kesehatan',
                'penanggungjawab' => 'Dokter Gigi dan Petrawat Gigi',
                'bentuk' => 'Softfile',
                'waktu' => 'PKTJ Tegal',
                'retensi' => '5 tahun',
                'file_path' => null,
                'file_name' => null,
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => false,
            ],
            [
                'judul' => 'Screening gigi kepada taruna/i PKTJ',
                'ringkasan' => 'Kegiatan rutin screening TBC yang merupakan program dari Dinas Kesehatan Kota Tegal',
                'pejabat' => 'Kanit Kesehatan',
                'penanggungjawab' => 'Nakes Unit Kesehatan',
                'bentuk' => 'Softfile',
                'waktu' => 'PKTJ tegal',
                'retensi' => '5 tahun',
                'file_path' => 'https://drive.google.com/file/d/1cs5uk0mhMAnJA50LLm7MTgTkC9a7fULp/view?usp=drive_link',
                'file_name' => 'Laporan Kegiatan Skringing TB (Informasi Publik)_TERSENSOR.pdf',
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => true,
            ],
            [
                'judul' => 'Surveillance ISO 21001 : 2018',
                'ringkasan' => 'Audit Surveillance dari SGS Indonesia, Penerapan ISO 21001 : 2018.
 Standar ini menekankan pentingnya kepuasan peserta didik, proses pembelajaran yang efektif, pemenuhan kebutuhan seluruh pemangku kepentingan pendidikan, serta perbaikan berkelanjutan dalam layanan pendidikan',
                'pejabat' => 'Ka SPM',
                'penanggungjawab' => 'Tim SPM',
                'bentuk' => 'Soft Copy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '2 tahun',
                'file_path' => 'https://drive.google.com/file/d/1RP4Mq6eUcA24hvZMDNmL7XxPp27A_Vhz/view?usp=drive_link',
                'file_name' => 'FULL LAPORAN HASIL KEGIATAN SURVEILLANCE ISO 21001;2018 C2V3 (Informasi Publik) TERSENSOR.pdf',
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => true,
            ],
            [
                'judul' => 'Survey Kepuasan Masyarakat Semester I',
                'ringkasan' => 'Laporan berisi nilai Indeks kepuasan masyarakat dan nilai indeks presepsi korupsi',
                'pejabat' => 'Ka SPM',
                'penanggungjawab' => 'Tim SPM',
                'bentuk' => 'Soft Copy dan Hard Copy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '1 tahun',
                'file_path' => 'https://drive.google.com/file/d/1gYZNEK_IFgG0hlYSmbHXG9R1Q688Z68_/view?usp=drive_link',
                'file_name' => 'LAPORAN IPK PKTJ SEMESTER 1 2025.pdf',
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => true,
            ],
            [
                'judul' => 'Tarif Layanan Diklat Teknis',
                'ringkasan' => 'SK Tarif Layanan Pendidikan dan Pelatihan',
                'pejabat' => 'Ka UPU',
                'penanggungjawab' => 'Tim UPU',
                'bentuk' => 'Soft File',
                'waktu' => 'Tegal, 2025',
                'retensi' => '1 (Satu) Tahun',
                'file_path' => null,
                'file_name' => null,
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => false,
            ],
            [
                'judul' => 'Tarif Layanan Penunjang Akademik',
                'ringkasan' => 'SK Tarif Layanan Penunjang Akademik',
                'pejabat' => 'Ka UPU',
                'penanggungjawab' => 'Tim UPU',
                'bentuk' => 'Soft File',
                'waktu' => 'Tegal, 2025',
                'retensi' => '1 (Satu) Tahun',
                'file_path' => null,
                'file_name' => null,
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'aktif' => false,
            ],
        ];

        // 2. SEED INFORMASI SERTA MERTA
        $sertamertaItems = [
            [
                'judul' => 'INFORMASI',
                'ringkasan' => 'RINGKASAN INFORMASI',
                'pejabat' => 'PEJABAT YANG
MENGUASAI INFORMASI',
                'penanggungjawab' => 'PENERBIT INFORMASI',
                'bentuk' => 'BENTUK
INFORMASI
YANG TERSEDIA',
                'waktu' => 'TEMPAT DAN
WAKTU PEMBUATAN',
                'retensi' => 'JANGKA WAKTU
PENYIMPANAN
DAN RETEN WAKTU',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'Daftar Arsip Aktif Tahun 2025',
                'ringkasan' => 'Daftar arsip merupakan daftar berkas yang telah dikelompokkan berdasarkan permasalahan',
                'pejabat' => 'Ketua Tim Bidang Umum',
                'penanggungjawab' => 'Bagiaun Keuangan Umum dan Kerjasama',
                'bentuk' => 'Soft file',
                'waktu' => 'Tegal bulan Januari- Desember 2025',
                'retensi' => 'Sesuai Masa Reten Arsip',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'Daftar MoU / Kerjasama',
                'ringkasan' => 'Dokumen kerjasama perpustakaan PKTJ dengan perpustakaan perguruan tinggi lain atau instansi.',
                'pejabat' => 'Kepala Unit Perpustakaan',
                'penanggungjawab' => 'Unit Kerjasama / Perpustakaan PKTJ',
                'bentuk' => 'Hardcopy & Sofcopy',
                'waktu' => 'Tegal. Sesuai Tanggal MoU',
                'retensi' => 'Sesuai masa berlaku MoU (biasanya 3-5 tahun)',
                'file_path' => 'https://drive.google.com/file/d/1EEa1yo0dCuDWgWMbFp6aUVQZiHzBlFvG/view?usp=drive_link',
                'file_name' => 'Road Map 2024.pdf',
                'aktif' => true,
            ],
            [
                'judul' => 'Donor darah dalam rangka Hari Perhubungan Nasional tahun 2025',
                'ringkasan' => 'Kegiatan Donor darah dalam rangka Hari Perhubungan Nasional tahun 2025 yang diikuti oleh civitas akademika PKTJ',
                'pejabat' => 'Kanit Kesehatan',
                'penanggungjawab' => 'Nakes Unit Kesehatan',
                'bentuk' => 'Softfile',
                'waktu' => 'PKTJ Tegal',
                'retensi' => '5 tahun',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'Jumlah kunjungan pasien klinik pratama PKTJ tahun 2025',
                'ringkasan' => 'Kunjungan Pasien tahun 2025 meliputi taruna, pegawai, dan masyarakat umum',
                'pejabat' => 'Kanit Kesehatan',
                'penanggungjawab' => 'Nakes Unit Kesehatan',
                'bentuk' => 'Softfile',
                'waktu' => 'PKTJ Tegal di tiap akhir bulan',
                'retensi' => '5 tahun',
                'file_path' => 'https://drive.google.com/file/d/1jY-CngE5yJKKUDvqpVAKa_SC5Ab2cFME/view?usp=sharing',
                'file_name' => 'KUNJUNGAN PASIEN JAN-NOV 2025.pdf',
                'aktif' => true,
            ],
            [
                'judul' => 'Katalog Induk (OPAC)',
                'ringkasan' => 'Daftar seluruh koleksi buku yang dimiliki perpustakaan beserta status ketersediaannya.',
                'pejabat' => 'Kepala Unit Perpustakaan',
                'penanggungjawab' => 'Unit Perpustakaan PKTJ',
                'bentuk' => 'Digital (Database)',
                'waktu' => 'Tegal, Realtime',
                'retensi' => 'Permanen (Database terus bertambah)',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'Laporan kebersihan asrama',
                'ringkasan' => 'pengecekan kebersihan asrama',
                'pejabat' => 'kanit asrama',
                'penanggungjawab' => 'unit asrama',
                'bentuk' => 'softfile',
                'waktu' => 'PKTJ Tegal di tiap akhir bulan',
                'retensi' => '2 tahun',
                'file_path' => 'https://drive.google.com/file/d/1kzb8Zi0KK4lMijVu55AinwblduZvE5WG/view?usp=drive_link',
                'file_name' => '1. LAPORAN BULAN JANUARI ASRAMA 2025 (Informasi Publik)_TERSENSOR.pdf',
                'aktif' => true,
            ],
            [
                'judul' => 'Laporan Statistik Koleksi',
                'ringkasan' => 'Informasi statistik pengunjung dan peminjaman koleksi',
                'pejabat' => 'Kepala Unit Perpustakaan',
                'penanggungjawab' => 'Unit Perpustakaan PKTJ',
                'bentuk' => 'Hardcopy & Sofcopy',
                'waktu' => 'Tegal,  Diperbarui setiap bulan',
                'retensi' => '5 Tahun',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'Pemeriksaan Kesehatan Gratis Pengemudi Ojek Online Dalam Rangka Hari Perhubungan Nasional Tahun 2025',
                'ringkasan' => 'Kegiatan pemeriksaan kesehatan gratis meliputi pemeriksaan tekanan darah, gula darah sewaktu, kolesterol, dan asam urat bagi  pengemudi Ojek online',
                'pejabat' => 'Kanit Kesehatan',
                'penanggungjawab' => 'Nakes Unit Kesehatan',
                'bentuk' => 'Softfile',
                'waktu' => 'PKTJ Tegal',
                'retensi' => '5 tahun',
                'file_path' => 'https://drive.google.com/file/d/1PCJ7TjFLh--7npmi85dXwP8Yi6cO6wlF/view?usp=drive_link',
                'file_name' => 'Laporan Kegiatan Pemeriksaan Gratis Pengemudi Ojek Online Harbunas 2025 (Informasi Publik)_TERSENSOR.pdf',
                'aktif' => true,
            ],
            [
                'judul' => 'Pemeriksaan Kesehatan Gratis Pengemudi Ojek Online Dalam Rangka HUT RI ke 80',
                'ringkasan' => 'Kegiatan pemeriksaan kesehatan gratis meliputi pemeriksaan tekanan darah, gula darah sewaktu, kolesterol, dan asam urat bagi  pengemudi Ojek online',
                'pejabat' => 'Kanit Kesehatan',
                'penanggungjawab' => 'Nakes Unit Kesehatan',
                'bentuk' => 'Softfile',
                'waktu' => 'PKTJ Tegal',
                'retensi' => '5 tahun',
                'file_path' => 'https://drive.google.com/file/d/1k1lxiDvvRFcCvI5OIfXOZbfo00Bw0sZI/view?usp=drive_link',
                'file_name' => 'Laporan Kegiatan Pemeriksaan Gratis Pengemudi Ojek Online HUT RI (Informasi Publik)_TERSENSOR.pdf',
                'aktif' => true,
            ],
            [
                'judul' => 'Penawaran Diklat Teknis Sektor Perhubungan Darat',
                'ringkasan' => 'Daftar Diklat Teknis, Tarif Diklat, RAB Diklat, Kurikulum dan Silabus Diklat',
                'pejabat' => 'Ka UPU',
                'penanggungjawab' => 'Tim UPU',
                'bentuk' => 'Soft File',
                'waktu' => 'Tegal, 2025',
                'retensi' => 'Selama masih berlaku',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'Penghapusan BMN Tahun 2025',
                'ringkasan' => 'Kegiatan penghapusan Barang Milik Negarai di lingkungan Politeknik Keselamatan Transportasi Jalan Tahun 2025',
                'pejabat' => 'Ketua Tim Bidang Umum',
                'penanggungjawab' => 'Bagiaun Keuangan Umum dan Kerjasama',
                'bentuk' => 'Soft file',
                'waktu' => 'Tegal bulan Juli 2025',
                'retensi' => '7 tahun',
                'file_path' => 'https://drive.google.com/file/d/1aRbozmigMYPH-3LQwjApjdCT4iI1OuAG/view?usp=drive_link',
                'file_name' => 'Salinan 202507231513390_Surat Rekomendasi Penghapusan BMN ke KPKNL Bangunan Gedung_TERSENSOR.pdf',
                'aktif' => true,
            ],
            [
                'judul' => 'Penyuluhan Kesehatan Umum dan Gigi Mulut kepada taruna',
                'ringkasan' => 'Kegiatan penyuluhan kesehatan kepada taruna/ni PKTJ baik kesehatan umum maupun kesehatan gigi dan mulut secara offline',
                'pejabat' => 'Kanit Kesehatan',
                'penanggungjawab' => 'Dokter Umum / Dokter Gigi / Nakes Unit Kesehatan',
                'bentuk' => 'Softfile',
                'waktu' => 'PKTJ Tegal',
                'retensi' => '5 Tahun',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'Profil Progam Studi RSTJ',
                'ringkasan' => 'Memuat Visi Misi, Lulusan, Dosen, Prestasi Taruna/i Prodi RSTJ dan kegiatan Pembelajaran Prodi RSTJ',
                'pejabat' => 'Kepala Progam Studi Rekayasa Sistem Transportasi Jalan (RSTJ)',
                'penanggungjawab' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => 'Selama masih berlaku /  Diperbarui jika ada perubahan',
                'file_path' => 'https://drive.google.com/file/d/1qOzwfGGg3V2edOgdxBD4Fjj1DncRU30X/view?usp=drive_link',
                'file_name' => '[update 1 Juli 2025] Dokumen Reviu Kurikulum Prodi RSTJ 2025.pdf',
                'aktif' => true,
            ],
            [
                'judul' => 'Profil Progam Studi TO',
                'ringkasan' => 'Memuat Visi Misi, Lulusan, Dosen, Prestasi Taruna/i Prodi TO dan kegiatan Pembelajaran Prodi TO',
                'pejabat' => 'Kepala Progam Studi Diploma III Teknologi Otomotif (TO)',
                'penanggungjawab' => 'Prodi Diploma III TO Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2021',
                'retensi' => 'Selama masih berlaku /  Diperbarui jika ada perubahan',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'Profil Progam Studi TRO',
                'ringkasan' => 'Memuat Visi Misi, Lulusan, Dosen, Prestasi Taruna/i Prodi TRO dan kegiatan Pembelajaran Prodi TRO',
                'pejabat' => 'Kepala Progam Studi Teknologi Rekayasa Otomotif (TRO)',
                'penanggungjawab' => 'Prodi TRO Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2021',
                'retensi' => 'Selama masih berlaku /  Diperbarui jika ada perubahan',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'Profil Unit Perpustakaan PKTJ',
                'ringkasan' => 'Memuat sejarah, visi misi, struktur organisasi, jam layanan, dan fasilitas perpustakaan.',
                'pejabat' => 'Kepala Unit Perpustakaan',
                'penanggungjawab' => 'Unit Perpustakaan PKTJ',
                'bentuk' => 'Hardcopy & Sofcopy',
                'waktu' => 'Tegal, 2023',
                'retensi' => 'Selama berlaku / Diperbarui jika ada perubahan',
                'file_path' => 'https://drive.google.com/file/d/1hcC1XY8hd7XWF-AHqW1fdDoUzyyED934/view?usp=drive_link',
                'file_name' => 'PROFIL PERPUSTAKAAN PKTJ (Informasi Publik)_TERSENSOR.pdf',
                'aktif' => true,
            ],
            [
                'judul' => 'Sosialisasi P4GN (Pencegahan, Pemberantasan, Penyalahgunaan dan Peredaran Gelap Narkotika) kepada Taruna PKTJ',
                'ringkasan' => 'Kegiatan Sosialisasi P4GN dilakukan secara online',
                'pejabat' => 'Kanit Kesehatan',
                'penanggungjawab' => 'Dokter Unit Kesehatan PKTJ',
                'bentuk' => 'Softfile',
                'waktu' => 'PKTJ Tegal',
                'retensi' => '5 tahun',
                'file_path' => 'https://drive.google.com/file/d/1CZsernmJspWDeXuq0c-1V0LE0ufnsMZK/view?usp=drive_link',
                'file_name' => 'Laporan Kegiatan P4GN 2025 (Informasi Publik).docx_TERSENSOR.pdf',
                'aktif' => true,
            ],
            [
                'judul' => 'SPI CHARTER (Piagam SPI)',
                'ringkasan' => 'Piagam Satuan Pengawas Internal (Audit Charter SPI) adalah dokumen formal yang berisi tentang komitmen pimpinan berupa pengakuan keberadaan dan berfungsinya Satuan Pengawas Internal di sebuah organisasi. Piagam Satuan Pengawas Internal PKTJ mencakup visi, misi, kedudukan, tugas, fungsi, dan ruang lingkup serta persetujuan dan pengesahan dari Pimpinan Organisasi.',
                'pejabat' => 'Kepala SPI',
                'penanggungjawab' => 'SPI Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy dan Hardcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '1 (satu) tahun',
                'file_path' => 'https://drive.google.com/file/d/1XY_1ktDrqGwQJ2nuK_sslnYrP0Ddv4nx/view?usp=drive_link',
                'file_name' => 'Piagam SPI 2025 (Informasi Publik)_TERSENSOR.pdf',
                'aktif' => true,
            ],
        ];

        // 3. SEED INFORMASI SETIAP SAAT
        $setiapsaatItems = [
            [
                'judul' => 'INFORMASI',
                'ringkasan' => 'RINGKASAN INFORMASI',
                'pejabat' => 'PEJABAT YANG
MENGUASAI INFORMASI',
                'penanggungjawab' => 'PENERBIT INFORMASI',
                'bentuk' => 'BENTUK
INFORMASI
YANG TERSEDIA',
                'waktu' => 'TEMPAT DAN
WAKTU PEMBUATAN',
                'retensi' => 'JANGKA WAKTU
PENYIMPANAN
DAN RETEN WAKTU',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'DIP (Daftar Informasi Publik)',
                'ringkasan' => 'Daftar yang memuat informasi-informasi yang dapat diakses oleh masyarakat sebagai bagian dari hak untuk mendapatkan informasi publik',
                'pejabat' => 'Kapokja PPID dan Humas',
                'penanggungjawab' => 'Tim Kerjasama',
                'bentuk' => 'softcopy dan hardcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '1 tahun',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'Dokumen Kurikulum',
                'ringkasan' => 'Hasil review kurikulum Prodi RSTJ. Kurikulum lama (tahun 2020) diganti dengan kurikulum baru (2025)',
                'pejabat' => 'Kepala Progam Studi Rekayasa Sistem Transportasi Jalan (RSTJ)',
                'penanggungjawab' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => 'Selama masih berlaku',
                'file_path' => 'https://drive.google.com/file/d/1Yq1cQU5fVWRM0ogGBIlONl-p6AtbHcOT/view?usp=drive_link',
                'file_name' => 'KP-BPSDMP 173 Tahun 2025_RSTJ-1_SK Kurikulum 2025_TERSENSOR.pdf',
                'aktif' => true,
            ],
            [
                'judul' => 'Dokumen Kurikulum',
                'ringkasan' => 'Hasil review kurikulum Prodi TRO. Kurikulum lama (tahun 2020) diganti dengan kurikulum baru (2025)',
                'pejabat' => 'Kepala Progam Studi Teknologi Rekayasa Otomotif (TRO)',
                'penanggungjawab' => 'Prodi TRO Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2026',
                'retensi' => 'Selama masih berlaku',
                'file_path' => 'https://drive.google.com/file/d/14Z2niInObd5DyMfw1LL_9QYdX3jGbPS6/view?usp=drive_link',
                'file_name' => 'Kurikulum TRO 2025 KP-BPSDMP 181 Tahun 2025_TRO_TERSENSOR.pdf',
                'aktif' => true,
            ],
            [
                'judul' => 'Dokumen Kurikulum',
                'ringkasan' => 'Kurikulum Prodi TO. Kurikulum lama (tahun 2020) diganti dengan kurikulum baru (2025)',
                'pejabat' => 'Kepala Progam Studi Diploma III Teknologi Otomotif (TO)',
                'penanggungjawab' => 'Prodi Diploma III TO Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => 'Selama masih berlaku',
                'file_path' => 'https://drive.google.com/file/d/1GRN5PAXrJwYUc01QqVskbyHpF-Uo-WKi/view?usp=drive_link',
                'file_name' => 'KURIKULUM D3 TO 2020 PKTJ_TERSENSOR.pdf',
                'aktif' => true,
            ],
            [
                'judul' => 'Dokumen Kurikulum',
                'ringkasan' => 'Hasil review kurikulum Prodi TO. Kurikulum lama (tahun 2020) diganti dengan kurikulum baru (2025)',
                'pejabat' => 'Kepala Progam Studi Diploma III Teknologi Otomotif (TO)',
                'penanggungjawab' => 'Prodi Diploma III TO Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => 'Selama masih berlaku',
                'file_path' => 'https://drive.google.com/file/d/1JzIqbOa5BZy49tJYKfdICmkh1Ysi0yNQ/view?usp=drive_link',
                'file_name' => 'KURIKULUM HASIL REVIEW D3 TO 2025 SAH_TERSENSOR.pdf',
                'aktif' => true,
            ],
            [
                'judul' => 'Kegiatan Pembelajaran Teaching Factory (TeFa)',
                'ringkasan' => 'Pedoman TeFa RSTJ',
                'pejabat' => 'Kepala Progam Studi Rekayasa Sistem Transportasi Jalan (RSTJ)',
                'penanggungjawab' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '6 bulan',
                'file_path' => 'https://drive.google.com/file/d/1Q4KCRsbVOCqY2VTlOhwZ8OOnBRmnkN54/view?usp=drive_link',
                'file_name' => 'PedomanTefa RSTJ.pdf',
                'aktif' => true,
            ],
            [
                'judul' => 'Kegiatan Pembelajaran Teaching Factory (TeFa)',
                'ringkasan' => 'Progres TeFa RSTJ',
                'pejabat' => 'Kepala Progam Studi Rekayasa Sistem Transportasi Jalan (RSTJ)',
                'penanggungjawab' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '6 bulan',
                'file_path' => 'https://drive.google.com/file/d/1xYhKYTH3JSQyrZsnV09DR28GIpPgRq9l/view?usp=drive_link',
                'file_name' => 'Progres TEFA RSTJ Ganjil 2025-2026.pdf',
                'aktif' => true,
            ],
            [
                'judul' => 'Kegiatan Pembelajaran Teaching Factory (TeFa)',
                'ringkasan' => 'Produk TeFa RSTJ Kelas A',
                'pejabat' => 'Kepala Progam Studi Rekayasa Sistem Transportasi Jalan (RSTJ)',
                'penanggungjawab' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '6 bulan',
                'file_path' => 'https://drive.google.com/file/d/1a-yG1DvOuosOMRKt5-77hUGzlL5N3_vo/view?usp=drive_link',
                'file_name' => 'Preview Produk TeFa RSTJ Kelas A Kelompok 1_TERSENSOR.pdf',
                'aktif' => true,
            ],
            [
                'judul' => 'Kegiatan Pembelajaran Teaching Factory (TeFa)',
                'ringkasan' => 'Produk TeFa RSTJ Kelas B',
                'pejabat' => 'Kepala Progam Studi Rekayasa Sistem Transportasi Jalan (RSTJ)',
                'penanggungjawab' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '6 bulan',
                'file_path' => 'https://drive.google.com/file/d/1z5qQ6l5LGVjSaClxwCaSDIYDwm3ds66-/view?usp=drive_link',
                'file_name' => 'Preview Produk TeFa RSTJ Kelas B Kelompok 1_TERSENSOR.pdf',
                'aktif' => true,
            ],
            [
                'judul' => 'Kegiatan Pembelajaran Teaching Factory (TeFa)',
                'ringkasan' => 'SK PENUNJUKAN TIM TeFa 2025',
                'pejabat' => 'Kepala Progam Studi Teknologi Rekayasa Otomotif (TRO)',
                'penanggungjawab' => 'Prodi TRO Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '6 Bulan',
                'file_path' => 'https://drive.google.com/file/d/1QFpmVataYKiB9UNgr_l9-p0Z7m4dchhG/view?usp=drive_link',
                'file_name' => 'SK PENUNJUKAN TIM TeFa 2025 (Informasi Publik)_TERSENSOR.pdf',
                'aktif' => true,
            ],
            [
                'judul' => 'Kegiatan Pembelajaran Teaching Factory (TeFa)',
                'ringkasan' => 'Produk TeFa TRO',
                'pejabat' => 'Kepala Progam Studi Teknologi Rekayasa Otomotif (TRO)',
                'penanggungjawab' => 'Prodi TRO Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '6 Bulan',
                'file_path' => 'https://drive.google.com/drive/folders/1-KoetVPqIyiJ3VXd3EaVwpZkaC2bzRcB?usp=drive_link',
                'file_name' => 'TeFa TRO',
                'aktif' => true,
            ],
            [
                'judul' => 'Kegiatan Pembelajaran Teaching Factory (TeFa)',
                'ringkasan' => 'Pada semester ganjil 2025-2026, dimulai model pembelajaran Tefa. Setelah UTS, taruna mengerjakan proyek baik dari industri maupun dari internal kampus PKTJ.',
                'pejabat' => 'Kepala Progam Studi Diploma III Teknologi Otomotif (TO)',
                'penanggungjawab' => 'Prodi Diploma III TO Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '6 Bulan',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'Kontrak',
                'ringkasan' => 'Kontrak adalah kesepakatan atau perjanjian mengikat secara hukum antara dua pihak atau lebih yang menciptakan kewajiban tertentu bagi masing-masing pihak, mengatur hak dan tanggung jawab mereka, serta dapat ditegakkan secara hukum jika terjadi wanprestasi, bisa dalam bentuk lisan atau tulisan, dan seringkali merupakan bagian dari perjanjian yang lebih luas (perikatan).',
                'pejabat' => 'Katim Kerjasama',
                'penanggungjawab' => 'Tim Kerjasama',
                'bentuk' => 'softcopy dan hardcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '1 tahun',
                'file_path' => 'https://drive.google.com/file/d/1LUoIDHDwphNHlW6a0lx1v1waAobKJPxy/view?usp=drive_link',
                'file_name' => '10.1-Kontrak Pengujian Ketidakrataan dan Kekesatan Jalan di Ruas Jalan Tol PT PPTR Tahun 2025-PKTJ Tegal (Informasi Publik)_TERSENSOR.pdf',
                'aktif' => true,
            ],
            [
                'judul' => 'Laporan Diklat Pemberdayaan Masyarakat',
                'ringkasan' => 'Laporan seluruh DIklat Pemberdayaan Masyarakat yang dilaksanakan selama tahun 2025',
                'pejabat' => 'Kapokja Diklat',
                'penanggungjawab' => 'Tim Administrasi Akademik',
                'bentuk' => 'softcopy dan hardcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '2 tahun',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'Laporan Diklat Teknis',
                'ringkasan' => 'Laporan seluruh diklat teknis yang dilaksanakan selama thuan 2025',
                'pejabat' => 'Kapokja Diklat',
                'penanggungjawab' => 'Tim Administrasi Akademik',
                'bentuk' => 'softcopy dan hardcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '2 tahun',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'Laporan kebersihan asrama',
                'ringkasan' => 'pengecekan kebersihan asrama',
                'pejabat' => 'kanit asrama',
                'penanggungjawab' => 'unit asrama',
                'bentuk' => 'softfile',
                'waktu' => 'PKTJ Tegal di tiap akhir bulan',
                'retensi' => '2 tahun',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'Laporan penanganan keluhan asrama',
                'ringkasan' => 'tindak lanjut penanganan kekuhan oenghuni asrama',
                'pejabat' => 'kanit asrama',
                'penanggungjawab' => 'unit asrama',
                'bentuk' => 'softfile',
                'waktu' => 'PKTJ Tegal di tiap akhir bulan',
                'retensi' => '2 tahun',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'Laporan Pengawasan Permakanan',
                'ringkasan' => 'Laporan pengawasan pemakanan yang berisi kesesuaian menu permakanan taruna selama tahun 2025',
                'pejabat' => 'Nutrisionis Terampil',
                'penanggungjawab' => 'Pusat Pembangunan Karakter',
                'bentuk' => 'Softfile',
                'waktu' => 'Tegal, 2025',
                'retensi' => '5 Tahun',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'Laporan perbaikan fasilitas asrama',
                'ringkasan' => 'perbaikan yang dilakukan oleh tim unit asrama',
                'pejabat' => 'kanit asrama',
                'penanggungjawab' => 'unit asrama',
                'bentuk' => 'softfile',
                'waktu' => 'PKTJ Tegal di tiap akhir bulan',
                'retensi' => '2 tahun',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'MoU',
                'ringkasan' => 'MoU (Memorandum of Understanding) adalah nota kesepahaman atau perjanjian pendahuluan yang berisi pernyataan niat dan kesepakatan awal antara dua pihak atau lebih sebelum membuat kontrak formal yang lebih mengikat secara hukum. MoU berfungsi sebagai landasan awal untuk menjajaki kerja sama, menguraikan tujuan, dan ruang lingkup, namun biasanya tidak mengikat secara hukum seperti kontrak, kecuali ada klausul khusus yang ditambahkan',
                'pejabat' => 'Katim Kerjasama',
                'penanggungjawab' => 'Tim Kerjasama',
                'bentuk' => 'softcopy dan hardcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '5 tahun',
                'file_path' => 'https://drive.google.com/file/d/1lm5RH7NM7YTS5OETZyY1nJ2iLMxgRWtD/view?usp=drive_link',
                'file_name' => 'Kesepakatan Bersama PJ 15 Tahun 2025 PKTJ x SUZUKI (Informasi Publik)_TERSENSOR.pdf',
                'aktif' => true,
            ],
            [
                'judul' => 'Panduan Pelaksanaan  Penelitian Dan Pengabdian Kepada Masyarakat',
                'ringkasan' => 'Panduan Berisi Ketentuan-Ketentuan Pelaksanaan  Kegiatan Penelitian Dan PKM',
                'pejabat' => 'Kepala P3M',
                'penanggungjawab' => 'P3M Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2021',
                'retensi' => '5 (lima) tahun',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'Perjanjian  Kinerja (PK) PKTJ Tegal tahun 2025',
                'ringkasan' => 'Perjanjian Kinerja merupakan
rencana kinerja tahunan yang merupakan penjabaran dari RENSTRA',
                'pejabat' => 'Ketua Tim Substansi Bidang Keuangan',
                'penanggungjawab' => 'Bagian Perencanaan',
                'bentuk' => 'softcopy dan hardcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '1 (satu) tahun',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'Perjanjian Kerja Sama',
                'ringkasan' => 'Perjanjian Kerja Sama (PKS) adalah kesepakatan formal dan mengikat secara hukum antara dua pihak atau lebih untuk bekerja sama mencapai tujuan bersama, yang merinci hak, kewajiban, tanggung jawab, dan pembagian sumber daya untuk suatu proyek atau usaha tertentu, seringkali lebih mengikat daripada MoU (Memorandum of Understanding) yang bersifat pra-kontrak.',
                'pejabat' => 'Katim Kerjasama',
                'penanggungjawab' => 'Tim Kerjasama',
                'bentuk' => 'softcopy dan hardcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '5 tahun',
                'file_path' => 'https://drive.google.com/file/d/1opXQdCZ9G3kKIqTcmgEcEbU-Bxjc0mUz/view?usp=drive_link',
                'file_name' => 'IA PJ-PKTJ 21 2025 PKTJ x Psikologi Undip (Informasi Publik)_TERSENSOR.pdf',
                'aktif' => true,
            ],
            [
                'judul' => 'Perjanjian kerjasama Dejavato Foundation dan PKTJ',
                'ringkasan' => 'Perjanjian Kerjasama tentang Penyediaan Volunteer Asing untuk meningkatkan kemampuan Bahasa Inggris Civitas Akademika PKTJ',
                'pejabat' => 'Kanit Bahasa',
                'penanggungjawab' => 'Unit Kerjasama / Unit Bahasa',
                'bentuk' => 'Softcopy dan Hardcopy',
                'waktu' => 'PKTJ Tegal Tahun 2018',
                'retensi' => '10 Tahun',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'Perjanjian Kerjasama IIEF dan PKTJ',
                'ringkasan' => 'Perjanjian Kerjasama tentang Penetapan PKTJ Tegal sebagai mitra IIEF untuk melaksanakan Tes TOEFL ITP berlisensi ETS',
                'pejabat' => 'Kanit Bahasa',
                'penanggungjawab' => 'Unit Kerjasama / Unit Bahasa',
                'bentuk' => 'Softcopy dan Hardcopy',
                'waktu' => 'PKTJ Tegal Tahun 2023',
                'retensi' => '5 Tahun',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'Perjanjian Kinerja (PK) PKTJ Tegal tahun 2025',
                'ringkasan' => 'Perjanjian Kinerja merupakan
 rencana kinerja tahunan yang merupakan penjabaran dari RENSTRA',
                'pejabat' => 'Ketua Tim Substansi Bidang Keuangan',
                'penanggungjawab' => 'Bagian Perencanaan',
                'bentuk' => 'softcopy dan hardcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '1 (satu) tahun',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'Program Kerja dan Sasaran Mutu Unit Bahasa',
                'ringkasan' => 'Program Kerja Unit Bahasa merupakan dokumen yang berisi tentang rencana tahunan kegiatan Unit Bahasa dan Sasaran Mutu mencakup target yang akan dicapai dalam satu tahun.',
                'pejabat' => 'Kanit Bahasa',
                'penanggungjawab' => 'Unit Bahasa',
                'bentuk' => 'Softcopy dan Hardcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '1 Tahun',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'Program Kerja SPI',
                'ringkasan' => 'Program Kerja SPI merupakan dokumen yang berisi tentang rencana tahunan kegiatan pengawasan (audit, reviu, evaluasi) untuk memastikan tujuan organisasi tercapai, pengelolaan keuangan dan aset aman, serta kepatuhan terhadap aturan, mencakup aspek kelembagaan, sistem pengendalian, SDM, dan tindak lanjut temuan audit di PKTJ.',
                'pejabat' => 'Kepala SPI',
                'penanggungjawab' => 'SPI Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy dan Hardcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '1 (satu) tahun',
                'file_path' => 'https://drive.google.com/file/d/11SVPDZoPM8apJYh8KDgFGrip_92Kz9zm/view?usp=drive_link',
                'file_name' => 'Program Kerja SPI 2025 (Informasi Publik)_TERSENSOR.pdf',
                'aktif' => true,
            ],
            [
                'judul' => 'Rekapan Pengelolaan CCTV Kampus PKTJ',
                'ringkasan' => 'Informasi ringkas dan berkala mengenai status fungsionalitas dan lokasi CCTV yang terpasang di area kampus PKTJ.',
                'pejabat' => 'Unit IT',
                'penanggungjawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk' => 'softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => 'sesuai retensi arsip',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'Rekapitulasi Sewa Aset Sarana dan Prasarana PKTJ',
                'ringkasan' => 'Identitas Penyewa, Pelaksanaan Sewa, Tujuan Sewa',
                'pejabat' => 'Ka UPU',
                'penanggungjawab' => 'Tim UPU',
                'bentuk' => 'Soft File',
                'waktu' => 'Tegal, 2025',
                'retensi' => '5 (lima) Tahun',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'Repository Institusi (Karya Ilmiah)',
                'ringkasan' => 'Informasi metadata karya ilmiah (Tugas Akhir dan Laporan Magang) yang dihasilkan sivitas akademika PKTJ.',
                'pejabat' => 'Kepala Unit Perpustakaan',
                'penanggungjawab' => 'Unit Perpustakaan PKTJ',
                'bentuk' => 'Digital (Database)',
                'waktu' => 'Tegal, Realtime',
                'retensi' => 'Permanen (Database terus bertambah)',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'Roadmap Penelitian Dan Pengabdian Kepada Masyarakat',
                'ringkasan' => 'Roadmap Penelitian Dan Pengabdian Kepada Masyarakat Berisi Tema-Tema Penelitian dan PKM selama 5 tahun',
                'pejabat' => 'Kepala P3M',
                'penanggungjawab' => 'P3M Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2024',
                'retensi' => '5 (lima) tahun',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'SOP',
                'ringkasan' => 'Dokumen yang berisi Standar Operasional Prosedur Unit Bahasa',
                'pejabat' => 'Kanit Bahasa',
                'penanggungjawab' => 'Bagian Penjaminan Mutu PKTJ',
                'bentuk' => 'Softcopy dan Hardcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '5 Tahun',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'SOP Layanan BLU',
                'ringkasan' => 'Prosedur dan Alur Layanan BLU PKTJ',
                'pejabat' => 'Ka. UPU',
                'penanggungjawab' => 'Tim UPU',
                'bentuk' => 'Soft File',
                'waktu' => 'Tegal,2025',
                'retensi' => 'Selama masih berlaku',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'SOP Pemberian Layanan Jasa Perpustakaan Dan Informasi Mengenai Sumber Pembelajaran',
                'ringkasan' => 'Prosedur dan alur layanan peminjaman serta pengembalian buku bagi pemustaka.',
                'pejabat' => 'Kepala Unit Perpustakaan',
                'penanggungjawab' => 'Bagian Penjaminan Mutu PKTJ',
                'bentuk' => 'Hardcopy & Sofcopy',
                'waktu' => 'Tegal, 2023',
                'retensi' => 'Selama SOP belum direvisi',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'SOP Pembuatan Surat Bebas Pustaka',
                'ringkasan' => 'Syarat dan prosedur pengurusan surat keterangan bebas pustaka untuk syarat Wisuda/Kelulusan.',
                'pejabat' => 'Kepala Unit Perpustakaan',
                'penanggungjawab' => 'Bagian Penjaminan Mutu PKTJ',
                'bentuk' => 'Hardcopy & Sofcopy',
                'waktu' => 'Tegal, 2023',
                'retensi' => 'Selama SOP belum direvisi',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'SOP Penetapan Tarif',
                'ringkasan' => 'Prosedur dan Alur Penetapan Tarif Baru Layanan PKTJ',
                'pejabat' => 'Ka. UPU',
                'penanggungjawab' => 'Tim UPU',
                'bentuk' => 'Soft File',
                'waktu' => 'Tegal,2025',
                'retensi' => 'Selama masih berlaku',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'SOP Pengadaan Bahan Pustaka',
                'ringkasan' => 'Tata cara pengajuan usulan pengadaan buku oleh Dosen atau Taruna.',
                'pejabat' => 'Kepala Unit Perpustakaan',
                'penanggungjawab' => 'Bagian Penjaminan Mutu PKTJ',
                'bentuk' => 'Hardcopy & Sofcopy',
                'waktu' => 'Tegal, 2023',
                'retensi' => 'Selama SOP belum direvisi',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'SOP SPI',
                'ringkasan' => 'Dokumen yang berisi tentang Standar Operasional dan Prosedur SPI',
                'pejabat' => 'Kepala SPI',
                'penanggungjawab' => 'SPI Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '5 (lima) tahun',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'SPK/SPMK (Surat Perjanjian Kerja)/(Surat Perintah Mulai Kerja)',
                'ringkasan' => 'Surat Perjanjian Kerja/Surat Perintah Kerja /Surat Perintah Mulai Kerja adalah dokumen legal yang mengikat secara hukum, berisi perintah resmi dari pemberi kerja (perusahaan/instansi) kepada pekerja/penyedia jasa untuk memulai suatu pekerjaan, serta merinci syarat-syarat kerja, hak, kewajiban, ruang lingkup pekerjaan, batas waktu (durasi), hingga biaya atau nilai kontrak, menjadikannya landasan hukum pelaksanaan proyek atau tugas',
                'pejabat' => 'Katim Kerjasama',
                'penanggungjawab' => 'Tim Kerjasama',
                'bentuk' => 'softcopy dan hardcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => '1 tahun',
                'file_path' => 'https://drive.google.com/file/d/1jP_z3VAlXuB4Dti4_UPhEv_GAD-rJszw/view?usp=drive_link',
                'file_name' => '28-SPK Pekerjaan Jasa Uji Reflektifitas Tahap I pada Ruas Jalan Tol Pejagan Pemalang Tahun 2025-PKTJ Tegal (Informasi Publik)_TERSENSOR.pdf',
                'aktif' => true,
            ],
            [
                'judul' => 'Struktur Organisasi Unit Teknologi Informasi',
                'ringkasan' => 'Struktur organisasi Unit Teknologi Informasi PKTJ yang terdiri dari Kepala Unit Teknologi Informasi di bawah Kepala Bagian Administrasi Akademik dan Ketarunaan, serta Kelompok Jabatan Fungsional. Struktur ini berada di bawah koordinasi Direktur Politeknik Keselamatan Transportasi Jalan',
                'pejabat' => 'Unit TI',
                'penanggungjawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk' => 'softcopy',
                'waktu' => 'Tegal, 2025',
                'retensi' => 'sesuai retensi arsip',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
            [
                'judul' => 'Tata Tertib Perpustakaan',
                'ringkasan' => 'Peraturan mengenai etika, tata cara berpakaian, dan larangan di dalam ruang perpustakaan.',
                'pejabat' => 'Kepala Unit Perpustakaan',
                'penanggungjawab' => 'Unit Perpustakaan PKTJ',
                'bentuk' => 'Softcopy',
                'waktu' => 'Tegal, 2019',
                'retensi' => 'Selama peraturan masih berlaku',
                'file_path' => null,
                'file_name' => null,
                'aktif' => false,
            ],
        ];

        // Insert Berkala
        foreach ($berkalaItems as $it) {
            $m = new InformasiBerkala();
            $m->judul = $it['judul'];
            $m->deskripsi = $it['ringkasan'];
            $m->tanggal = '2025-10-01';
            $m->file_path = $it['file_path'];
            $m->file_name = $it['file_name'];
            $m->file_size = $it['file_path'] ? 'Link GDrive' : null;
            $m->file_type = 'link';
            $m->aktif = $it['aktif'];
            $m->is_blurred = false;
            $m->bisa_download = true;
            $m->save();

            $d = new DaftarInformasi();
            $d->judul_informasi = $it['judul'];
            $d->kategori = 'informasi-berkala';
            $d->tipe_informasi = $it['tipe_informasi'];
            $d->isi_informasi = $it['ringkasan'];
            $d->pejabat_penguasa = $it['pejabat'];
            $d->penerbit_informasi = $it['penanggungjawab'];
            $d->penanggung_jawab = $it['penanggungjawab'];
            $d->tempat_pembuatan = 'Tegal';
            $d->waktu_pembuatan = $it['waktu'];
            $d->bentuk_informasi = $it['bentuk'];
            $d->jangka_waktu = $it['retensi'];
            $d->file_informasi = $it['file_path'];
            $d->aktif = $it['aktif'];
            $d->is_blurred = false;
            $d->bisa_download = true;
            $d->save();
        }

        // Insert Serta Merta
        foreach ($sertamertaItems as $it) {
            $m = new InformasiSertaMerta();
            $m->judul = $it['judul'];
            $m->deskripsi = $it['ringkasan'];
            $m->tanggal = '2025-10-01';
            $m->file_path = $it['file_path'];
            $m->file_name = $it['file_name'];
            $m->file_size = $it['file_path'] ? 'Link GDrive' : null;
            $m->file_type = 'link';
            $m->aktif = $it['aktif'];
            $m->is_blurred = false;
            $m->bisa_download = true;
            $m->save();

            $d = new DaftarInformasi();
            $d->judul_informasi = $it['judul'];
            $d->kategori = 'informasi-serta-merta';
            $d->tipe_informasi = 'sertamerta';
            $d->isi_informasi = $it['ringkasan'];
            $d->pejabat_penguasa = $it['pejabat'];
            $d->penerbit_informasi = $it['penanggungjawab'];
            $d->penanggung_jawab = $it['penanggungjawab'];
            $d->tempat_pembuatan = 'Tegal';
            $d->waktu_pembuatan = $it['waktu'];
            $d->bentuk_informasi = $it['bentuk'];
            $d->jangka_waktu = $it['retensi'];
            $d->file_informasi = $it['file_path'];
            $d->aktif = $it['aktif'];
            $d->is_blurred = false;
            $d->bisa_download = true;
            $d->save();
        }

        // Insert Setiap Saat
        foreach ($setiapsaatItems as $it) {
            $m = new InformasiSetiapSaat();
            $m->judul = $it['judul'];
            $m->deskripsi = $it['ringkasan'];
            $m->tanggal = '2025-10-01';
            $m->file_path = $it['file_path'];
            $m->file_name = $it['file_name'];
            $m->file_size = $it['file_path'] ? 'Link GDrive' : null;
            $m->file_type = 'link';
            $m->aktif = $it['aktif'];
            $m->is_blurred = false;
            $m->bisa_download = true;
            $m->save();

            $d = new DaftarInformasi();
            $d->judul_informasi = $it['judul'];
            $d->kategori = 'informasi-setiap-saat';
            $d->tipe_informasi = 'setiapsaat';
            $d->isi_informasi = $it['ringkasan'];
            $d->pejabat_penguasa = $it['pejabat'];
            $d->penerbit_informasi = $it['penanggungjawab'];
            $d->penanggung_jawab = $it['penanggungjawab'];
            $d->tempat_pembuatan = 'Tegal';
            $d->waktu_pembuatan = $it['waktu'];
            $d->bentuk_informasi = $it['bentuk'];
            $d->jangka_waktu = $it['retensi'];
            $d->file_informasi = $it['file_path'];
            $d->aktif = $it['aktif'];
            $d->is_blurred = false;
            $d->bisa_download = true;
            $d->save();
        }
    }
}
