<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class Dip2026SyncSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Ensure columns exist on pejabats
        if (Schema::hasTable('pejabats')) {
            if (!Schema::hasColumn('pejabats', 'lhkpn_links')) {
                Schema::table('pejabats', function ($table) {
                    $table->json('lhkpn_links')->nullable();
                });
            }
            if (!Schema::hasColumn('pejabats', 'foto_width')) {
                Schema::table('pejabats', function ($table) {
                    $table->integer('foto_width')->nullable()->default(160);
                    $table->integer('foto_height')->nullable()->default(240);
                    $table->integer('foto_card_height')->nullable()->default(390);
                    $table->string('foto_position')->nullable()->default('top center');
                    $table->string('foto_radius')->nullable()->default('14px');
                });
            }
            DB::table('pejabats')->where('id', 6)->orWhere('nama', 'like', '%Agus Hariyanto%')
                ->update(['jabatan' => 'Kepala Bagian Keuangan dan Administrasi Umum']);
        }

        // 2. Clean dummy Laporan Layanan / Dokumens
        if (Schema::hasTable('dokumens')) {
            DB::table('dokumens')
                ->whereIn('kategori', ['Laporan Layanan', 'Laporan Akses', 'Laporan Tahunan'])
                ->delete();
            DB::table('dokumens')
                ->where('judul', 'like', '%Laporan Permohonan Informasi%')
                ->orWhere('judul', 'like', '%Laporan Tahunan%')
                ->delete();
        }

        // 3. Clean legacy tables to prevent stale or duplicate entries
        if (Schema::hasTable('informasi_berkalas')) {
            DB::table('informasi_berkalas')->delete();
        }
        if (Schema::hasTable('informasi_sertamertas')) {
            DB::table('informasi_sertamertas')->delete();
        }
        if (Schema::hasTable('informasi_setiap_saats')) {
            DB::table('informasi_setiap_saats')->delete();
        }
        if (Schema::hasTable('informasi_setiapsaats')) {
            DB::table('informasi_setiapsaats')->delete();
        }

        // 4. Clean daftar_informasis (keep informasi-dikecualikan)
        if (Schema::hasTable('daftar_informasis')) {
            DB::table('daftar_informasis')->where('kategori', '!=', 'informasi-dikecualikan')->delete();
        }

        // Helper to insert item
        $insertItem = function (string $kategori, array $item) {
            $richContent = '<p>' . htmlspecialchars($item['ringkasan']) . '</p>' .
                '<div style="margin-top: 14px; padding: 14px 18px; background-color: #f0f7ff; border-left: 4px solid #004a99; border-radius: 8px;">' .
                '<p style="margin: 0; font-size: 14px; color: #1e293b;">' .
                '<strong>Tautan Dokumen Resmi Google Drive:</strong><br>' .
                '<a href="' . htmlspecialchars($item['link']) . '" target="_blank" rel="noopener noreferrer" style="color: #004a99; text-decoration: underline; font-weight: 700; display: inline-block; margin-top: 6px;">' .
                '<i class="fas fa-external-link-alt" style="margin-right: 6px;"></i> Buka Dokumen (Google Drive)' .
                '</a>' .
                '</p>' .
                '</div>';

            DB::table('daftar_informasis')->insert([
                'judul_informasi'    => $item['judul'],
                'kategori'           => $kategori,
                'tipe_informasi'     => 'dokumen',
                'isi_informasi'      => $richContent,
                'pejabat_penguasa'   => $item['pejabat'] ?? 'PPID Pelaksana UPT PKTJ Tegal',
                'penerbit_informasi' => $item['penerbit'] ?? 'Politeknik Keselamatan Transportasi Jalan',
                'tempat_pembuatan'   => $item['tempat'] ?? 'Tegal',
                'penanggung_jawab'   => $item['penerbit'] ?? 'PKTJ Tegal',
                'waktu_pembuatan'    => $item['waktu'] ?? '2025',
                'bentuk_informasi'   => $item['bentuk'] ?? 'Softcopy',
                'jangka_waktu'       => $item['retensi'] ?? '1 Tahun',
                'file_informasi'     => $item['link'],
                'aktif'              => 1,
                'is_blurred'         => 0,
                'bisa_download'      => 1,
                'created_at'         => now(),
                'updated_at'         => now(),
            ]);
        };

        // 5. INFORMASI BERKALA (28 Verified Items)
        $berkalaData = [
            [
                'judul' => 'Akreditasi Program Studi (LED & LKPS Prodi RSTJ, TRO, TO)',
                'ringkasan' => 'Dokumen Laporan Evaluasi Diri Program Studi (LED) dan Laporan Kinerja Program Studi (LKPS) Prodi RSTJ, TRO, dan TO yang diunggah pada sistem LAM Teknik untuk akreditasi program studi.',
                'pejabat' => 'Kepala SPM',
                'penerbit' => 'Tim SPM dan masing-masing Prodi',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '5 Tahun',
                'link' => 'https://drive.google.com/file/d/1cn3kpfAolP2XXpMwIeFjIbyLyJzMsDGT/view?usp=drive_link',
            ],
            [
                'judul' => 'Laporan Audit Mutu Internal (AMI) PKTJ Tahun 2025',
                'ringkasan' => 'Laporan pelaksanaan Audit Mutu Internal Tahun 2025 oleh Auditor Internal kepada masing-masing unit kerja dan auditee di lingkungan PKTJ.',
                'pejabat' => 'Kepala SPM',
                'penerbit' => 'Tim SPM dan Auditor',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '2 Tahun',
                'link' => 'https://drive.google.com/file/d/1SgWVM5rXisRA03X2mP1V4XE-n_vx7n1A/view?usp=drive_link',
            ],
            [
                'judul' => 'Jadwal Kegiatan Softskill Literasi Kesehatan Mental Taruna Tahun 2025',
                'ringkasan' => 'Jadwal dan susunan kegiatan pembentukan karakter softskill taruna mengenai literasi kesehatan mental tahun 2025.',
                'pejabat' => 'Pengasuh Praja',
                'penerbit' => 'Pusat Pembangunan Karakter',
                'bentuk' => 'Softfile',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '5 Tahun',
                'link' => 'https://drive.google.com/file/d/1UKgitogU1fpLfSizig91wbB_XVHSEgxz/view?usp=drive_link',
            ],
            [
                'judul' => 'Jadwal Perkuliahan Program Studi D3 Teknologi Otomotif (TO) TA 2025/2026',
                'ringkasan' => 'Jadwal perkuliahan dan plotting dosen pengampu semester ganjil Program Studi Diploma III Teknologi Otomotif (TO) TA 2025/2026.',
                'pejabat' => 'Kepala Program Studi D3 Teknologi Otomotif (TO)',
                'penerbit' => 'Prodi D3 TO Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '6 Bulan',
                'link' => 'https://drive.google.com/file/d/1P4_gCmIeBuj2-NKea-66BFfCutwCc7UX/view?usp=drive_link',
            ],
            [
                'judul' => 'Laporan Pengawasan Mutu & Manajemen Sistem Penyelenggaraan Makanan (MSPM) Taruna 2025',
                'ringkasan' => 'Laporan kegiatan pengawasan mutu dan manajemen sistem penyelenggaraan makanan (MSPM) serta evaluasi permakanan taruna periode Januari hingga November 2025.',
                'pejabat' => 'Nutrisionis Terampil',
                'penerbit' => 'Pusat Pembangunan Karakter',
                'bentuk' => 'Softfile',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '5 Tahun',
                'link' => 'https://drive.google.com/file/d/12hNO6rPTU_0uWUe7jht2aYNH0vGK2M62/view?usp=drive_link',
            ],
            [
                'judul' => 'Laporan Kegiatan Pengukuran Indeks Massa Tubuh (IMT) Taruna Tahun 2025',
                'ringkasan' => 'Laporan hasil pengukuran Indeks Massa Tubuh (IMT) taruna/i PKTJ pada Semester 1 (Maret) dan Semester 2 (Agustus) Tahun 2025.',
                'pejabat' => 'Nutrisionis Terampil',
                'penerbit' => 'Pusat Pembangunan Karakter',
                'bentuk' => 'Softfile',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '5 Tahun',
                'link' => 'https://drive.google.com/file/d/1Yfm4P60ku-VES3DguWMX-hUmwKPYIP2e/view?usp=drive_link',
            ],
            [
                'judul' => 'Laporan Penilaian Samapta Periodik Taruna Tahun 2025',
                'ringkasan' => 'Laporan penilaian tes kesamaptaan jasmani periodik taruna/i PKTJ yang dilaksanakan pada Semester Ganjil dan Semester Genap Tahun 2025.',
                'pejabat' => 'Pengasuh Praja',
                'penerbit' => 'Pusat Pembangunan Karakter',
                'bentuk' => 'Softfile',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '5 Tahun',
                'link' => 'https://drive.google.com/file/d/1OfKfPGUfovfe34wYQ0IvmB-Gn0JJEynA/view?usp=drive_link',
            ],
            [
                'judul' => 'Laporan Perkuliahan Semester Genap Prodi RSTJ TA 2024/2025',
                'ringkasan' => 'Laporan pelaksanaan perkuliahan Semester Genap Tahun Akademik 2024/2025 Program Studi Sarjana Terapan Rekayasa Sistem Transportasi Jalan (RSTJ).',
                'pejabat' => 'Kepala Program Studi RSTJ',
                'penerbit' => 'Program Studi RSTJ',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => 'Selama Masih Berlaku',
                'link' => 'https://drive.google.com/drive/folders/1tGeLPdWyPcEIU3eg3Ir9dx4TtkiDJsgO?usp=drive_link',
            ],
            [
                'judul' => 'Laporan Tracer Study Lulusan PKTJ Tahun 2025',
                'ringkasan' => 'Laporan hasil kegiatan penelusuran lulusan (tracer study) terhadap alumni tahun 2023 dan 2024 dari program studi RSTJ, TRO, dan D3 TO.',
                'pejabat' => 'Katim Substansi Administrasi Ketarunaan dan Alumni',
                'penerbit' => 'Tim Administrasi Ketarunaan dan Alumni',
                'bentuk' => 'Softcopy & Hardcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '5 Tahun',
                'link' => 'https://drive.google.com/file/d/1_R9FtirHJn8EYshWXI8JpgmJ9ad1SkWO/view?usp=drive_link',
            ],
            [
                'judul' => 'Laporan Pelaksanaan Uji Kompetensi Penilai Analisis Dampak Lalu Lintas (Andalalin) 2025',
                'ringkasan' => 'Diawali dengan kegiatan pra-ujikom penilai Andalalin dan dilanjutkan pelaksanaan asesmen uji kompetensi penilai Andalalin Prodi RSTJ Tahun 2025.',
                'pejabat' => 'Kepala Program Studi RSTJ',
                'penerbit' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '1 Tahun',
                'link' => 'https://drive.google.com/file/d/1Ilhf0YdRhQ7dxrekCkvdzJ4CJCtaGPYP/view?usp=drive_link',
            ],
            [
                'judul' => 'Laporan Pelaksanaan Uji Kompetensi Pembantu Penguji Kendaraan Bermotor (PKB) 2025',
                'ringkasan' => 'Diawali kegiatan pra-ujikom dan dilanjutkan uji kompetensi pembantu penguji kendaraan bermotor (PKB) bagi 31 mahasiswa Program Studi TRO Tahun 2025.',
                'pejabat' => 'Kepala Program Studi TRO',
                'penerbit' => 'Prodi TRO Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '1 Tahun',
                'link' => 'https://drive.google.com/file/d/1T0e51-oIN1zi70Tp96Et7tu2WheeAXa7/view?usp=drive_link',
            ],
            [
                'judul' => 'Laporan Pelaksanaan Uji Kompetensi Pemeliharaan Jalan (PKS Kerjasama) 2025',
                'ringkasan' => 'Laporan kegiatan pelatihan pemeliharaan jalan dan asesmen/uji kompetensi pemeliharaan jalan hasil kerja sama Program Studi RSTJ Tahun 2025.',
                'pejabat' => 'Kepala Program Studi RSTJ',
                'penerbit' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '1 Tahun',
                'link' => 'https://drive.google.com/file/d/1qnwCoURKV1qnMPuCGXVUwpFn9MlP0Jx8/view?usp=drive_link',
            ],
            [
                'judul' => 'Laporan Pelaksanaan Uji Kompetensi Penguji Berkala Kendaraan Bermotor Tingkat 3',
                'ringkasan' => 'Pra-ujikom dan uji kompetensi penguji berkala kendaraan bermotor tingkat 3 bagi 106 mahasiswa D3 TO POLBIT dan NON-POLBIT.',
                'pejabat' => 'Kepala Program Studi D3 TO',
                'penerbit' => 'Prodi D3 TO Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '1 Tahun',
                'link' => 'https://drive.google.com/drive/folders/10bFBQqAABU4xr-UZ4-nD9n_AjTKuVl9U?usp=drive_link',
            ],
            [
                'judul' => 'Laporan Pelaksanaan Uji Kompetensi Sistem Manajemen Keselamatan (SMK) 2025',
                'ringkasan' => 'Diawali kegiatan pra-ujikom dan dilanjutkan uji kompetensi Sistem Manajemen Keselamatan (SMK) bagi 57 mahasiswa Polbit Program Studi TRO Tahun 2025.',
                'pejabat' => 'Kepala Program Studi TRO',
                'penerbit' => 'Prodi TRO Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '1 Tahun',
                'link' => 'https://drive.google.com/file/d/1YsTHPUBSn-LhG4dhs1xFjmHrEF9UwT2s/view?usp=drive_link',
            ],
            [
                'judul' => 'Pelaksanaan UTS dan UAS Program Studi RSTJ TA 2025/2026',
                'ringkasan' => 'Nota dinas pelaksanaan ujian tengah semester (UTS) dan ujian akhir semester (UAS) mengikuti kalender akademik Program Studi RSTJ TA 2025/2026.',
                'pejabat' => 'Kepala Program Studi RSTJ',
                'penerbit' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '6 Bulan',
                'link' => 'https://drive.google.com/file/d/15vXKG0Fm8zNr7i-tuC9gHhygv_0rgdIE/view?usp=drive_link',
            ],
            [
                'judul' => 'Pelaksanaan UTS dan UAS Program Studi TRO TA 2025/2026',
                'ringkasan' => 'Nota dinas pelaksanaan ujian tengah semester dan ujian akhir semester ganjil Program Studi Teknologi Rekayasa Otomotif (TRO) TA 2025/2026.',
                'pejabat' => 'Kepala Program Studi TRO',
                'penerbit' => 'Prodi TRO Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '6 Bulan',
                'link' => 'https://drive.google.com/file/d/1cFjBfLtGgOkYsjud8uMLu9qXd5jWbix8/view?usp=drive_link',
            ],
            [
                'judul' => 'Pelaksanaan UTS dan UAS Program Studi D3 TO TA 2025/2026',
                'ringkasan' => 'Pengumuman dan ketentuan pelaksanaan ujian tengah semester dan ujian akhir semester ganjil Program Studi Diploma III TO TA 2025/2026.',
                'pejabat' => 'Kepala Program Studi D3 TO',
                'penerbit' => 'Prodi D3 TO Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '6 Bulan',
                'link' => 'https://drive.google.com/file/d/1gAl4oo672SWlv05qOeAupBflSJ8DY-F7/view?usp=drive_link',
            ],
            [
                'judul' => 'Ploting dan Jadwal Perkuliahan Semester Genap Prodi RSTJ',
                'ringkasan' => 'Ploting dosen pengampu dan susunan jadwal perkuliahan semester genap Program Studi Sarjana Terapan RSTJ.',
                'pejabat' => 'Kepala Program Studi RSTJ',
                'penerbit' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '6 Bulan',
                'link' => 'https://drive.google.com/drive/folders/17IaQFiEyMC3mgEI6Xd99myZV0WA3LAhG?usp=drive_link',
            ],
            [
                'judul' => 'Rapat Tinjauan Manajemen (RTM) PKTJ Tahun 2025',
                'ringkasan' => 'Risalah dan hasil evaluasi rapat tinjauan manajemen penjaminan mutu SPM PKTJ Tegal Tahun 2025.',
                'pejabat' => 'Kepala SPM',
                'penerbit' => 'Tim SPM PKTJ',
                'bentuk' => 'Softcopy & Hardcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '1 Tahun',
                'link' => 'https://drive.google.com/drive/folders/1YJqNIXAXI-LVZd9ejMdKPLoeePJQJ_TH?usp=drive_link',
            ],
            [
                'judul' => 'Laporan Pelaksanaan Screening Kesehatan Gigi dan Skrining TB Taruna PKTJ 2025',
                'ringkasan' => 'Kegiatan rutin screening pemeriksaan kesehatan gigi dan skrining tuberkulosis (TB) bagi taruna/i PKTJ bekerja sama dengan Dinas Kesehatan Kota Tegal.',
                'pejabat' => 'Kepala Unit Kesehatan',
                'penerbit' => 'Tenaga Kesehatan Unit Kesehatan PKTJ',
                'bentuk' => 'Softfile',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '5 Tahun',
                'link' => 'https://drive.google.com/file/d/1wt1p7rf2tFoYkEHk3nJxTrc86Oxcea5p/view?usp=drive_link',
            ],
            [
                'judul' => 'Laporan Audit Surveillance ISO 21001:2018 Sistem Manajemen Organisasi Pendidikan 2025',
                'ringkasan' => 'Laporan hasil audit surveillance ISO 21001:2018 oleh SGS Indonesia mengenai penjaminan mutu proses pembelajaran dan kepuasan peserta didik di PKTJ Tegal.',
                'pejabat' => 'Kepala SPM',
                'penerbit' => 'Tim SPM PKTJ',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '2 Tahun',
                'link' => 'https://drive.google.com/file/d/1ipXcaEhEjIAUnyCitdhBxGV2cc2rputU/view?usp=drive_link',
            ],
            [
                'judul' => 'Laporan Survei Kepuasan Masyarakat (IKM) & Indeks Persepsi Korupsi (IPK) Semester I 2025',
                'ringkasan' => 'Laporan berkala hasil survei Indeks Kepuasan Masyarakat (IKM) dan Indeks Persepsi Korupsi (IPK) Semester I Tahun 2025 di lingkungan PKTJ Tegal.',
                'pejabat' => 'Kepala SPM',
                'penerbit' => 'Tim SPM PKTJ',
                'bentuk' => 'Softcopy & Hardcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '1 Tahun',
                'link' => 'https://drive.google.com/drive/folders/1ZDALUWnp5ReH7QRUZt4bXYXjHlGOk6yq?usp=drive_link',
            ],
            [
                'judul' => 'DIPA Petikan PKTJ Tahun Anggaran 2025 (Revisi 08)',
                'ringkasan' => 'Dokumen otorisasi pelaksanaan anggaran Daftar Isian Pelaksanaan Anggaran (DIPA) Petikan PKTJ Tegal Tahun Anggaran 2025 revisi ke-8.',
                'pejabat' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit' => 'Bagian Keuangan dan Administrasi Umum',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '1 Tahun',
                'link' => 'https://drive.google.com/file/d/1hLQ-26Oko2u1uve8jD9NMbNknRnyLD_W/view?usp=drive_link',
            ],
            [
                'judul' => 'Surat Keputusan (SK) Penetapan PPID Pelaksana UPT PKTJ Tahun 2024',
                'ringkasan' => 'Surat Keputusan Direktur PKTJ Nomor SK-PKTJ 12 Tahun 2024 tentang Penetapan Pengelola Informasi dan Dokumentasi (PPID) Pelaksana di lingkungan UPT PKTJ Tegal.',
                'pejabat' => 'Direktur PKTJ',
                'penerbit' => 'Subbagian Tata Usaha & Kepegawaian',
                'bentuk' => 'Softcopy',
                'waktu' => '2024',
                'tempat' => 'Tegal',
                'retensi' => 'Selama Berlaku',
                'link' => 'https://drive.google.com/file/d/16_4Pmme_pWLgafTXlmBU0uuS82qs5RhP/view?usp=sharing',
            ],
            [
                'judul' => 'Penyampaian Laporan Tahunan Pelayanan Informasi Publik PKTJ 2025 ke PPID Utama Kemenhub',
                'ringkasan' => 'Surat penyampaian resmi Laporan Tahunan Layanan Informasi Publik UPT PKTJ Tegal Tahun 2025 kepada PPID Utama Kementerian Perhubungan.',
                'pejabat' => 'Direktur PKTJ',
                'penerbit' => 'PPID Pelaksana PKTJ',
                'bentuk' => 'Softcopy / PDF',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '5 Tahun',
                'link' => 'https://drive.google.com/file/d/1NabSL0TAkoFyp7aEEiyeXbWrkBDbMGyx/view?usp=drive_link',
            ],
            [
                'judul' => 'Laporan Tahunan Pelaksanaan Program Kerja & Keuangan PKTJ 2025',
                'ringkasan' => 'Laporan tahunan komprehensif pertanggungjawaban pelaksanaan seluruh program kerja, kegiatan akademis, dan realisasi anggaran PKTJ Tegal Tahun 2025.',
                'pejabat' => 'Direktur PKTJ',
                'penerbit' => 'Bagian Keuangan dan Administrasi Umum',
                'bentuk' => 'Softcopy / PDF',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '5 Tahun',
                'link' => 'https://drive.google.com/file/d/1pe1vqLCRemRpA6G5q2VpC0L6KhTGriEo/view?usp=sharing',
            ],
            [
                'judul' => 'Ringkasan Eksekutif LKjIP / LAKIP PKTJ 2025',
                'ringkasan' => 'Ringkasan eksekutif akuntabilitas kinerja instansi pemerintah (LKjIP / LAKIP) mengenai pencapaian target sasaran strategis PKTJ Tegal Tahun 2025.',
                'pejabat' => 'Direktur PKTJ',
                'penerbit' => 'Subbagian Tata Usaha & Tim AKIP',
                'bentuk' => 'Softcopy / PDF',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '5 Tahun',
                'link' => 'https://drive.google.com/file/d/18azvUjvumzPkAN-hTmSWhkWaJrXZFle3/view?usp=drive_link',
            ],
            [
                'judul' => 'Laporan Pengaduan Masyarakat, WBS, dan SP4N-LAPOR 2025/2026',
                'ringkasan' => 'Rekapitulasi penanganan aspirasi masyarakat, Whistleblowing System (WBS), dan tindak lanjut laporan pengaduan melalui portal SP4N-LAPOR PKTJ.',
                'pejabat' => 'Satuan Pengawas Internal (SPI)',
                'penerbit' => 'Tim Penanganan Pengaduan Masyarakat & SPI PKTJ',
                'bentuk' => 'Softcopy / PDF',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '5 Tahun',
                'link' => 'https://drive.google.com/file/d/1GWWRCz0vru-ZWGbiWkiGhohBo1cCxmxw/view?usp=drive_link',
            ],
        ];

        foreach ($berkalaData as $item) {
            $insertItem('informasi-berkala', $item);
        }

        // 6. INFORMASI SERTA MERTA (18 Verified Items)
        $sertaMertaData = [
            [
                'judul' => 'Roadmap Penelitian dan Pengabdian Kepada Masyarakat (P3M) PKTJ Tahun 2024',
                'ringkasan' => 'Dokumen Roadmap Penelitian dan Pengabdian Kepada Masyarakat (P3M) Politeknik Keselamatan Transportasi Jalan Tahun 2024 yang memuat peta jalan dan tema strategis riset institusi.',
                'pejabat' => 'Kepala Pusat Penelitian dan Pengabdian Masyarakat (P3M)',
                'penerbit' => 'Pusat Penelitian dan Pengabdian Masyarakat (P3M)',
                'bentuk' => 'Softcopy',
                'waktu' => '2024',
                'tempat' => 'Tegal',
                'retensi' => '5 Tahun',
                'link' => 'https://drive.google.com/file/d/1EEa1yo0dCuDWgWMbFp6aUVQZiHzBlFvG/view?usp=drive_link',
            ],
            [
                'judul' => 'Jumlah Kunjungan Pasien Klinik Pratama PKTJ Tahun 2025',
                'ringkasan' => 'Data statistik dan rekapitulasi kunjungan pasien rawat jalan pada Klinik Pratama PKTJ meliputi taruna, pegawai, dan masyarakat umum periode Januari-November 2025.',
                'pejabat' => 'Kanit Kesehatan',
                'penerbit' => 'Nakes Unit Kesehatan',
                'bentuk' => 'Softfile',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '5 Tahun',
                'link' => 'https://drive.google.com/drive/folders/1zmYPO6XuAm6rp9HMuUO1UAy6fSROproS?usp=drive_link',
            ],
            [
                'judul' => 'Laporan Kebersihan Asrama PKTJ Tahun 2025 (Bulan Januari s/d Desember Lengkap)',
                'ringkasan' => 'Rekapitulasi berkala laporan pengecekan dan monitoring kebersihan asrama taruna/i PKTJ Kampus I dan II dari Bulan Januari hingga Desember 2025 secara lengkap.',
                'pejabat' => 'Kanit Asrama',
                'penerbit' => 'Unit Asrama',
                'bentuk' => 'Google Drive Folder',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '2 Tahun',
                'link' => 'https://drive.google.com/drive/folders/1qU81c6u8w7zy6oCCF2mLxN_FxIouESxW?usp=drive_link',
            ],
            [
                'judul' => 'Pemeriksaan Kesehatan Gratis Pengemudi Ojek Online Dalam Rangka Hari Perhubungan Nasional Tahun 2025',
                'ringkasan' => 'Kegiatan bakti sosial pemeriksaan kesehatan gratis (tekanan darah, gula darah sewaktu, kolesterol, dan asam urat) bagi pengemudi ojek online dalam rangka Hari Perhubungan Nasional 2025.',
                'pejabat' => 'Kanit Kesehatan',
                'penerbit' => 'Nakes Unit Kesehatan',
                'bentuk' => 'Softfile',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '5 Tahun',
                'link' => 'https://drive.google.com/file/d/1a3nUuc1aFcz38juWmUw-FTrpL3QkErkE/view?usp=drive_link',
            ],
            [
                'judul' => 'Pemeriksaan Kesehatan Gratis Pengemudi Ojek Online Dalam Rangka HUT RI ke 80',
                'ringkasan' => 'Kegiatan bakti sosial pemeriksaan kesehatan gratis meliputi pemeriksaan tekanan darah, gula darah sewaktu, kolesterol, dan asam urat bagi pengemudi ojek online dalam rangka HUT RI ke-80.',
                'pejabat' => 'Kanit Kesehatan',
                'penerbit' => 'Nakes Unit Kesehatan',
                'bentuk' => 'Softfile',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '5 Tahun',
                'link' => 'https://drive.google.com/file/d/14qD_iSgw9QYvEDjeexFzMOqjQBE4O9R7/view?usp=drive_link',
            ],
            [
                'judul' => 'Penghapusan Barang Milik Negara (BMN) PKTJ Tahun 2025',
                'ringkasan' => 'Kegiatan penghapusan Barang Milik Negara di lingkungan Politeknik Keselamatan Transportasi Jalan Tahun 2025.',
                'pejabat' => 'Ketua Tim Bidang Umum',
                'penerbit' => 'Bagian Keuangan Umum dan Kerjasama',
                'bentuk' => 'Soft file',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '7 Tahun',
                'link' => 'https://drive.google.com/drive/folders/19cbR6rqgd7geDJsO4q9hxtan9D8Lpz1b?usp=drive_link',
            ],
            [
                'judul' => 'Profil Program Studi Rekayasa Sistem Transportasi Jalan (RSTJ)',
                'ringkasan' => 'Memuat Visi Misi, Lulusan, Dosen, Prestasi Taruna/i Prodi RSTJ dan kegiatan Pembelajaran Prodi RSTJ.',
                'pejabat' => 'Kepala Program Studi RSTJ',
                'penerbit' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => 'Selama masih berlaku / Diperbarui jika ada perubahan',
                'link' => 'https://drive.google.com/drive/folders/1_uPmo1JucI1DNNpRdtWci5n0Oxyunouq?usp=drive_link',
            ],
            [
                'judul' => 'Profil Unit Perpustakaan PKTJ',
                'ringkasan' => 'Memuat sejarah, visi misi, struktur organisasi, jam layanan, dan fasilitas perpustakaan.',
                'pejabat' => 'Kepala Unit Perpustakaan',
                'penerbit' => 'Unit Perpustakaan PKTJ',
                'bentuk' => 'Hardcopy & Softcopy',
                'waktu' => '2023',
                'tempat' => 'Tegal',
                'retensi' => 'Selama berlaku / Diperbarui jika ada perubahan',
                'link' => 'https://drive.google.com/file/d/1dTJ_sBSr8JU1tnKSkavIZ1r2nUOUrMrx/view?usp=drive_link',
            ],
            [
                'judul' => 'Sosialisasi P4GN kepada Taruna PKTJ',
                'ringkasan' => 'Kegiatan Sosialisasi Pencegahan, Pemberantasan, Penyalahgunaan dan Peredaran Gelap Narkotika (P4GN) kepada Taruna PKTJ dilakukan secara online.',
                'pejabat' => 'Kanit Kesehatan',
                'penerbit' => 'Dokter Unit Kesehatan PKTJ',
                'bentuk' => 'Softfile',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '5 Tahun',
                'link' => 'https://drive.google.com/file/d/1-Nv0oNJwzwEHTP6pUEWR9cQbTLzc-7wy/view?usp=drive_link',
            ],
            [
                'judul' => 'Piagam Satuan Pengawas Internal (SPI Charter) PKTJ Tegal',
                'ringkasan' => 'Piagam Satuan Pengawas Internal (Audit Charter SPI) adalah dokumen formal yang berisi komitmen pimpinan berupa pengakuan keberadaan dan berfungsinya Satuan Pengawas Internal di sebuah organisasi.',
                'pejabat' => 'Kepala SPI',
                'penerbit' => 'SPI Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy dan Hardcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '1 (satu) tahun',
                'link' => 'https://drive.google.com/file/d/1H14Y7vILtPAGoSluY3Zv9zlYk69gDPZl/view?usp=drive_link',
            ],
            [
                'judul' => 'SK BPSDMP No. 17 Tahun 2025 tentang Pembentukan Tim Penghapusan BMN PKTJ',
                'ringkasan' => 'Keputusan Kepala BPSDMP mengenai penetapan tim penghapusan barang milik negara rusak berat pada Politeknik Keselamatan Transportasi Jalan.',
                'pejabat' => 'Bagian Keuangan dan Umum',
                'penerbit' => 'BPSDMP Kemenhub / PKTJ',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '7 Tahun',
                'link' => 'https://drive.google.com/file/d/15SHHrTblDsjl27FibdhzkteotNzsDNOU/view?usp=drive_link',
            ],
            [
                'judul' => 'Surat Keterangan Penghentian Penggunaan Barang Milik Negara (BMN) Rusak Berat',
                'ringkasan' => 'Surat keterangan resmi mengenai penghentian penggunaan barang milik negara dalam kondisi rusak berat.',
                'pejabat' => 'Pengelola BMN PKTJ',
                'penerbit' => 'Bagian Keuangan dan Umum',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '7 Tahun',
                'link' => 'https://drive.google.com/file/d/1XCiGZba6RnIdCUegfDuJ8J4YpQ8cgCe2/view?usp=drive_link',
            ],
            [
                'judul' => 'Surat Rekomendasi Kedaruratan Penghapusan Bangunan Gedung Rusak ke KPKNL',
                'ringkasan' => 'Surat rekomendasi permohonan penghapusan dan pembongkaran bangunan gedung rusak kepada KPKNL Tegal.',
                'pejabat' => 'Tim Teknis Sarpras PKTJ',
                'penerbit' => 'Bagian Keuangan dan Umum',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '7 Tahun',
                'link' => 'https://drive.google.com/file/d/1aRbozmigMYPH-3LQwjApjdCT4iI1OuAG/view?usp=drive_link',
            ],
            [
                'judul' => 'Berita Acara Pemeriksaan Kondisi Barang dan Fisik Gedung Rusak Berat Tahun 2025',
                'ringkasan' => 'Berita acara hasil pemeriksaan fisik dan inventarisasi kondisi gedung yang mengalami kerusakan berat.',
                'pejabat' => 'Tim Verifikasi BMN',
                'penerbit' => 'Bagian Keuangan dan Umum',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '7 Tahun',
                'link' => 'https://drive.google.com/file/d/1MrlZOCs9EUBiEsq9BfGV3HD_f2bsfrrr/view?usp=drive_link',
            ],
            [
                'judul' => 'Perjanjian Kerjasama Darurat Akses E-Journal dengan Konsorsium FPPTI',
                'ringkasan' => 'Perjanjian kerjasama pemanfaatan dan akses konsorsium e-journal ilmiah antara PKTJ dengan FPPTI Jawa Tengah.',
                'pejabat' => 'Kepala Unit Perpustakaan',
                'penerbit' => 'Unit Perpustakaan PKTJ',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '3 Tahun',
                'link' => 'https://drive.google.com/file/d/1tMVLB1ZKFhMzp7Hxno60YOpO6lwAb90u/view?usp=drive_link',
            ],
            [
                'judul' => 'Perjanjian Kerjasama Pertukaran Informasi Pustaka dengan IAIN Kendari',
                'ringkasan' => 'Perjanjian kerjasama perpustakaan untuk pertukaran referensi literatur dan informasi ilmiah antara PKTJ dan IAIN Kendari.',
                'pejabat' => 'Kepala Unit Perpustakaan',
                'penerbit' => 'Unit Perpustakaan PKTJ',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '3 Tahun',
                'link' => 'https://drive.google.com/file/d/1o4-bFvEmkVq5_Nfj6XgoAWmneiRflwU4/view?usp=drive_link',
            ],
            [
                'judul' => 'Perjanjian Kerjasama Pertukaran Informasi Pustaka dengan Stikes Bhamada Slawi',
                'ringkasan' => 'Kerjasama antar-perpustakaan perguruan tinggi untuk akses koleksi bahan pustaka dan layanan informasi.',
                'pejabat' => 'Kepala Unit Perpustakaan',
                'penerbit' => 'Unit Perpustakaan PKTJ',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '3 Tahun',
                'link' => 'https://drive.google.com/file/d/13XvfY2buFn4s8KxHkp4aZXgHRRhnE9J9/view?usp=drive_link',
            ],
            [
                'judul' => 'Perjanjian Kerjasama Pertukaran Informasi Pustaka dengan UIN Sunan Gunung Djati',
                'ringkasan' => 'Kerjasama pertukaran publikasi ilmiah dan jejaring perpustakaan perguruan tinggi Islam negeri dengan PKTJ.',
                'pejabat' => 'Kepala Unit Perpustakaan',
                'penerbit' => 'Unit Perpustakaan PKTJ',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '3 Tahun',
                'link' => 'https://drive.google.com/file/d/1QFKjtEXMzJWorHYDkw9zevxW8lKosqx9/view?usp=drive_link',
            ],
        ];

        foreach ($sertaMertaData as $item) {
            $insertItem('informasi-serta-merta', $item);
        }

        // 7. INFORMASI SETIAP SAAT (27 Verified Items)
        $setiapSaatData = [
            [
                'judul' => 'Dokumen Kurikulum Program Studi Sarjana Terapan RSTJ (KP-BPSDMP 173 Tahun 2025)',
                'ringkasan' => 'Hasil review kurikulum Prodi Sarjana Terapan RSTJ. Menggantikan kurikulum lama 2020 dengan kurikulum baru 2025 berbasis Outcome-Based Education (OBE).',
                'pejabat' => 'Kepala Program Studi RSTJ',
                'penerbit' => 'Prodi RSTJ PKTJ Tegal',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => 'Selama Masih Berlaku',
                'link' => 'https://drive.google.com/file/d/1y6IgSsr8_Nan6lx9x3MS8tNNodGIzxYM/view?usp=drive_link',
            ],
            [
                'judul' => 'Dokumen Kurikulum Program Studi Sarjana Terapan TRO (KP-BPSDMP 181 Tahun 2025)',
                'ringkasan' => 'Hasil review kurikulum Prodi Sarjana Terapan TRO. Kurikulum operasional 2025 untuk peningkatan kompetensi teknologi rekayasa otomotif.',
                'pejabat' => 'Kepala Program Studi TRO',
                'penerbit' => 'Prodi TRO PKTJ Tegal',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => 'Selama Masih Berlaku',
                'link' => 'https://drive.google.com/file/d/1JvAj5qveSh5KW55HlTzEPNWd2XeQuFSU/view?usp=drive_link',
            ],
            [
                'judul' => 'Dokumen Kurikulum Program Studi D3 Teknologi Otomotif (Kurikulum 2020)',
                'ringkasan' => 'Buku pedoman kurikulum Program Studi Diploma III Teknologi Otomotif (TO) PKTJ Tegal Tahun 2020.',
                'pejabat' => 'Kepala Program Studi D3 TO',
                'penerbit' => 'Prodi D3 TO PKTJ Tegal',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => 'Selama Masih Berlaku',
                'link' => 'https://drive.google.com/file/d/1cyX-7EgNPsdcsgT2CiBt6b5skNLHGcgv/view?usp=drive_link',
            ],
            [
                'judul' => 'Dokumen Kurikulum Hasil Review Program Studi D3 Teknologi Otomotif Tahun 2025',
                'ringkasan' => 'Hasil review dan pengesahan pembaruan kurikulum Program Studi Diploma III Teknologi Otomotif (TO) PKTJ Tegal Tahun 2025.',
                'pejabat' => 'Kepala Program Studi D3 TO',
                'penerbit' => 'Prodi D3 TO PKTJ Tegal',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => 'Selama Masih Berlaku',
                'link' => 'https://drive.google.com/file/d/1jCxlNseEQufG024MQCutbXfFRLGlnjY3/view?usp=drive_link',
            ],
            [
                'judul' => 'Pedoman Pembelajaran Teaching Factory (TeFa) Prodi RSTJ',
                'ringkasan' => 'Pedoman pelaksanaan pembelajaran Teaching Factory (TeFa) Program Studi Sarjana Terapan RSTJ.',
                'pejabat' => 'Kepala Program Studi RSTJ',
                'penerbit' => 'Prodi RSTJ PKTJ Tegal',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '1 Tahun',
                'link' => 'https://drive.google.com/file/d/1U_0Gxo_VDiR44WPU1d3kgzGUWWxwEJZM/view?usp=drive_link',
            ],
            [
                'judul' => 'Laporan Progres Pembelajaran Teaching Factory (TeFa) Prodi RSTJ Semester Ganjil',
                'ringkasan' => 'Laporan perkembangan capaian pelaksanaan Teaching Factory (TeFa) mahasiswa Prodi RSTJ Semester Ganjil TA 2025/2026.',
                'pejabat' => 'Kepala Program Studi RSTJ',
                'penerbit' => 'Prodi RSTJ PKTJ Tegal',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '6 Bulan',
                'link' => 'https://drive.google.com/file/d/1thfMdVSo7D-kf2cFTtffKmGeDIg-h1gw/view?usp=drive_link',
            ],
            [
                'judul' => 'Portofolio dan Laporan Produk TeFa Prodi RSTJ Kelas A (Kelompok 1 - 6)',
                'ringkasan' => 'Dokumen portofolio hasil karya dan produk rekayasa keselamatan jalan mahasiswa TeFa Prodi RSTJ Kelas A.',
                'pejabat' => 'Kepala Program Studi RSTJ',
                'penerbit' => 'Prodi RSTJ PKTJ Tegal',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '6 Bulan',
                'link' => 'https://drive.google.com/drive/folders/1JRi9kaNpvPbNkFxWoCl-DMyRkQVRbWog?usp=drive_link',
            ],
            [
                'judul' => 'Portofolio dan Laporan Produk TeFa Prodi RSTJ Kelas B (Kelompok 1 - 6)',
                'ringkasan' => 'Dokumen portofolio hasil karya dan produk rekayasa keselamatan jalan mahasiswa TeFa Prodi RSTJ Kelas B.',
                'pejabat' => 'Kepala Program Studi RSTJ',
                'penerbit' => 'Prodi RSTJ PKTJ Tegal',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '6 Bulan',
                'link' => 'https://drive.google.com/drive/folders/1Q1Hlce9Fc8ndhC5vRVHcW10KdtnsGkeC?usp=drive_link',
            ],
            [
                'judul' => 'Surat Keputusan (SK) Penunjukan Tim Teaching Factory (TeFa) Prodi TRO 2025',
                'ringkasan' => 'Surat keputusan penetapan susunan tim pengajar dan pembimbing kegiatan Teaching Factory (TeFa) Prodi TRO Tahun 2025.',
                'pejabat' => 'Kepala Program Studi TRO',
                'penerbit' => 'Prodi TRO PKTJ Tegal',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '1 Tahun',
                'link' => 'https://drive.google.com/file/d/1UqUH_JDSE84qvKkT-KrdFjCb53XJTX0i/view?usp=drive_link',
            ],
            [
                'judul' => 'Kegiatan Pembelajaran Teaching Factory (TeFa) - Produk TeFa Prodi TRO PKTJ',
                'ringkasan' => 'Dokumen portofolio dan laporan produk kegiatan pembelajaran Teaching Factory (TeFa) Program Studi Teknologi Rekayasa Otomotif (TRO) PKTJ Tegal Tahun 2025.',
                'pejabat' => 'Kepala Program Studi TRO',
                'penerbit' => 'Prodi TRO PKTJ Tegal',
                'bentuk' => 'Google Drive Folder',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => 'Selama Berlaku',
                'link' => 'https://drive.google.com/drive/folders/1-KoetVPqIyiJ3VXd3EaVwpZkaC2bzRcB?usp=drive_link',
            ],
            [
                'judul' => 'Kontrak Pengujian dan Perjanjian Kerja Kemitraan PKTJ',
                'ringkasan' => 'Dokumen kontrak kesepakatan pelaksanaan pekerjaan pengujian ketidakrataan dan kekesatan jalan tol antara PKTJ dengan mitra penyedia jasa.',
                'pejabat' => 'Katim Kerjasama / PPK PKTJ',
                'penerbit' => 'Unit Pengembangan Usaha (UPU)',
                'bentuk' => 'Softcopy & Hardcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => 'Sesuai Masa Kontrak',
                'link' => 'https://drive.google.com/drive/folders/1LUoIDHDwphNHlW6a0lx1v1waAobKJPxy?usp=drive_link',
            ],
            [
                'judul' => 'Memorandum of Understanding (MoU) / Nota Kesepahaman Kemitraan PKTJ',
                'ringkasan' => 'Dokumen Nota Kesepahaman (Memorandum of Understanding / MoU) kemitraan dan kerja sama kelembagaan Politeknik Keselamatan Transportasi Jalan.',
                'pejabat' => 'Katim Kerjasama PKTJ',
                'penerbit' => 'Unit Kerjasama PKTJ',
                'bentuk' => 'Softcopy & Hardcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => 'Sesuai Masa Berlaku MoU (3-5 Tahun)',
                'link' => 'https://drive.google.com/drive/folders/1lm5RH7NM7YTS5OETZyY1nJ2iLMxgRWtD?usp=drive_link',
            ],
            [
                'judul' => 'Perjanjian Kerja Sama (PKS) Kemitraan Strategis PKTJ',
                'ringkasan' => 'Dokumen kesepakatan formal dan legalitas Perjanjian Kerja Sama (PKS) antara Politeknik Keselamatan Transportasi Jalan dengan instansi/mitra strategis.',
                'pejabat' => 'Katim Kerjasama PKTJ',
                'penerbit' => 'Unit Kerjasama PKTJ',
                'bentuk' => 'Softcopy & Hardcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => 'Sesuai Masa Berlaku Kerjasama',
                'link' => 'https://drive.google.com/drive/folders/1opXQdCZ9G3kKIqTcmgEcEbU-Bxjc0mUz?usp=drive_link',
            ],
            [
                'judul' => 'Surat Perjanjian Kerja / Surat Perintah Mulai Kerja (SPK/SPMK)',
                'ringkasan' => 'Dokumen legal Surat Perjanjian Kerja (SPK) dan Surat Perintah Mulai Kerja (SPMK) pengadaan jasa uji reflektifitas dan pengujian laboratorium PKTJ.',
                'pejabat' => 'PPK & Katim Kerjasama',
                'penerbit' => 'Unit Layanan Pengadaan / PPK Laboratorium',
                'bentuk' => 'Softcopy & Hardcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => 'Sesuai Masa Pelaksanaan Kontrak',
                'link' => 'https://drive.google.com/drive/folders/1jP_z3VAlXuB4Dti4_UPhEv_GAD-rJszw?usp=drive_link',
            ],
            [
                'judul' => 'Program Kerja Pengawasan Tahunan Satuan Pengawas Internal (SPI) PKTJ 2025',
                'ringkasan' => 'Dokumen rencana tahunan kegiatan audit, reviu, pemantauan, dan evaluasi kepatuhan internal di lingkungan PKTJ Tahun 2025.',
                'pejabat' => 'Kepala SPI',
                'penerbit' => 'SPI Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy & Hardcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => '1 Tahun',
                'link' => 'https://drive.google.com/file/d/17fHyAY4ctzyzVUIPzhHM2F9o-2Hc0RSi/view?usp=drive_link',
            ],
            [
                'judul' => 'Roadmap Penelitian dan Pengabdian Kepada Masyarakat (P3M) PKTJ 5 Tahunan',
                'ringkasan' => 'Peta jalan riset dan rencana induk pengabdian kepada masyarakat yang memuat fokus tema dan luaran selama 5 tahun.',
                'pejabat' => 'Kepala Pusat P3M',
                'penerbit' => 'P3M Politeknik Keselamatan Transportasi Jalan',
                'bentuk' => 'Softcopy',
                'waktu' => '2024',
                'tempat' => 'Tegal',
                'retensi' => '5 Tahun',
                'link' => 'https://drive.google.com/file/d/1kg1sCnGls8xv_ZQB2gVQK_Os2kLtu12a/view?usp=drive_link',
            ],
            [
                'judul' => 'Daftar Informasi Dikecualikan (DIK) PKTJ & Berita Acara Uji Konsekuensi',
                'ringkasan' => 'Dokumen penetapan Daftar Informasi yang Dikecualikan di lingkungan PKTJ Tegal beserta Berita Acara Uji Konsekuensi berdasarkan Pasal 17 UU No. 14 Tahun 2008.',
                'pejabat' => 'Tim Penguji Konsekuensi PPID PKTJ',
                'penerbit' => 'PPID Pelaksana UPT PKTJ Tegal',
                'bentuk' => 'Softcopy',
                'waktu' => '2026',
                'tempat' => 'Tegal',
                'retensi' => 'Selama Berlaku',
                'link' => 'https://drive.google.com/file/d/1ZfOIvQmVyoZElh8eTwEER71hSEJ7__Z7/view?usp=sharing',
            ],
            [
                'judul' => 'Standar Operasional Prosedur (SOP) Audit Kinerja Satuan Pengawas Internal (SPI)',
                'ringkasan' => 'Prosedur operasional baku pengawasan dan audit kinerja pelaksanaan anggaran serta program kerja unit di lingkungan PKTJ.',
                'pejabat' => 'Kepala SPI',
                'penerbit' => 'Satuan Pengawas Internal (SPI)',
                'bentuk' => 'Softcopy',
                'waktu' => '2024',
                'tempat' => 'Tegal',
                'retensi' => 'Selama Berlaku',
                'link' => 'https://drive.google.com/file/d/1wjnwG1Rc9WwXt41pzkHJ1nTY7P0ptGfR/view?usp=sharing',
            ],
            [
                'judul' => 'Standar Operasional Prosedur (SOP) Audit Dengan Tujuan Tertentu (ADTT)',
                'ringkasan' => 'Prosedur investigasi dan pemeriksaan khusus satuan pengawas internal atas dugaan penyimpangan administrasi.',
                'pejabat' => 'Kepala SPI',
                'penerbit' => 'Satuan Pengawas Internal (SPI)',
                'bentuk' => 'Softcopy',
                'waktu' => '2024',
                'tempat' => 'Tegal',
                'retensi' => 'Selama Berlaku',
                'link' => 'https://drive.google.com/file/d/1hosNNy168-E8aUHdK-xSs4Kasb8GCNfc/view?usp=sharing',
            ],
            [
                'judul' => 'SOP Pemeliharaan dan Kalibrasi Peralatan Simulator dan Laboratorium Pendidikan',
                'ringkasan' => 'Pedoman operasional pemeliharaan preventif, kalibrasi berkala, dan perbaikan perangkat laboratorium keselamatan jalan.',
                'pejabat' => 'Kepala Unit Laboratorium',
                'penerbit' => 'Unit Laboratorium dan Simulator PKTJ',
                'bentuk' => 'Softcopy',
                'waktu' => '2024',
                'tempat' => 'Tegal',
                'retensi' => 'Selama Berlaku',
                'link' => 'https://drive.google.com/file/d/1OjmlHil-8HLWjWDuA-sJ1qPXlBd_Q7cs/view?usp=sharing',
            ],
            [
                'judul' => 'SOP Inventarisasi Peralatan Ruangan Laboratorium dan Simulator Pendidikan',
                'ringkasan' => 'Standar Operasional Prosedur inventarisasi peralatan, perlengkapan ruangan laboratorium, dan simulator pendidikan di lingkungan Politeknik Keselamatan Transportasi Jalan.',
                'pejabat' => 'Kepala Unit Laboratorium Pendidikan',
                'penerbit' => 'Unit Laboratorium dan Simulator PKTJ',
                'bentuk' => 'Softcopy',
                'waktu' => '2023',
                'tempat' => 'Tegal',
                'retensi' => 'Selama Berlaku (Direvisi Berkala)',
                'link' => 'https://drive.google.com/file/d/1DUFV_F1NHCdS8rp7LhaDtBgKvF99irdJ/view?usp=sharing',
            ],
            [
                'judul' => 'Laporan Rekapitulasi Pertanyaan Masuk dan Konsultasi Layanan Informasi Publik di Media Sosial PKTJ Tahun 2026',
                'ringkasan' => 'Lembar rekapitulasi interaktif monitoring pertanyaan publik, permohonan informasi, dan konsultasi masyarakat melalui kanal media sosial resmi PKTJ Tegal Tahun 2026.',
                'pejabat' => 'Tim Pokja Humas dan PPID PKTJ',
                'penerbit' => 'Tim Pengelola Media Sosial & Layanan Informasi Publik',
                'bentuk' => 'Google Spreadsheet (Realtime Online)',
                'waktu' => '2026',
                'tempat' => 'Tegal',
                'retensi' => '1 Tahun',
                'link' => 'https://docs.google.com/spreadsheets/d/1q8R8llMqjE8wNysRQ39q8vafcsXcvKxNRSEkIe-JR_c/edit?usp=sharing',
            ],
            [
                'judul' => 'Struktur Organisasi Unit Teknologi Informasi',
                'ringkasan' => 'Struktur organisasi Unit Teknologi Informasi PKTJ yang terdiri dari Kepala Unit TI di bawah Kepala Bagian Administrasi Akademik dan Ketarunaan.',
                'pejabat' => 'Unit TI',
                'penerbit' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => 'Sesuai Retensi Arsip',
                'link' => 'https://drive.google.com/file/d/1lLKLUvNEDY8OAUCoOIvV24aFZg3u9JHJ/view?usp=drive_link',
            ],
            [
                'judul' => 'SOP Pembuatan Surat Bebas Pustaka',
                'ringkasan' => 'Syarat dan prosedur pengurusan surat keterangan bebas pustaka untuk syarat Wisuda/Kelulusan taruna/i PKTJ.',
                'pejabat' => 'Kepala Unit Perpustakaan',
                'penerbit' => 'Bagian Penjaminan Mutu PKTJ',
                'bentuk' => 'Hardcopy & Softcopy',
                'waktu' => '2023',
                'tempat' => 'Tegal',
                'retensi' => 'Selama SOP Belum Direvisi',
                'link' => 'https://drive.google.com/drive/folders/1xm0_eKUn8Sd419Cr3f_lgj5y2PjlUddg?usp=drive_link',
            ],
            [
                'judul' => 'SOP Pengadaan Bahan Pustaka',
                'ringkasan' => 'Tata cara pengajuan usulan pengadaan buku dan bahan pustaka oleh Dosen atau Taruna/i PKTJ.',
                'pejabat' => 'Kepala Unit Perpustakaan',
                'penerbit' => 'Bagian Penjaminan Mutu PKTJ',
                'bentuk' => 'Hardcopy & Softcopy',
                'waktu' => '2023',
                'tempat' => 'Tegal',
                'retensi' => 'Selama SOP Belum Direvisi',
                'link' => 'https://drive.google.com/drive/folders/1FE5gflmJ0NoXv51HMzmbz4Q2HRX21zqA?usp=drive_link',
            ],
            [
                'judul' => 'SOP Pemberian Layanan Jasa Perpustakaan Dan Informasi Mengenai Sumber Pembelajaran',
                'ringkasan' => 'Prosedur dan alur layanan peminjaman serta pengembalian buku bagi pemustaka di lingkungan perpustakaan PKTJ.',
                'pejabat' => 'Kepala Unit Perpustakaan',
                'penerbit' => 'Bagian Penjaminan Mutu PKTJ',
                'bentuk' => 'Hardcopy & Softcopy',
                'waktu' => '2023',
                'tempat' => 'Tegal',
                'retensi' => 'Selama SOP Belum Direvisi',
                'link' => 'https://drive.google.com/drive/folders/12LcansqF1ms4T-fTUj1BRyJm-ZK94TaA?usp=drive_link',
            ],
            [
                'judul' => 'Rekapan Pengelolaan CCTV Kampus PKTJ',
                'ringkasan' => 'Informasi ringkas dan berkala mengenai status fungsionalitas dan lokasi CCTV yang terpasang di area kampus PKTJ.',
                'pejabat' => 'Unit IT',
                'penerbit' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk' => 'Softcopy',
                'waktu' => '2025',
                'tempat' => 'Tegal',
                'retensi' => 'Sesuai Retensi Arsip',
                'link' => 'https://drive.google.com/drive/folders/1kBOEMVmvaqK-GkNwlFkldbE0tnXIDWxW?usp=drive_link',
            ],
        ];

        foreach ($setiapSaatData as $item) {
            $insertItem('informasi-setiap-saat', $item);
        }
    }
}
