<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\DaftarInformasi;
use App\Models\InformasiBerkala;
use App\Models\InformasiSetiapSaat;
use App\Models\InformasiSertaMerta;

class DipPktjPdfSeeder extends Seeder
{
    /**
     * Data Resmi Sesuai Lampiran Surat Direktur PKTJ Nomor: IP.102/1/2/PKTJ/2025
     * Lampiran I: Informasi Berkala (24 Dokumen)
     * Lampiran II: Informasi Setiap Saat (49 Dokumen)
     * Lampiran III: Informasi Serta Merta (7 Dokumen)
     * Total: 80 Dokumen Master DIP PKTJ Tegal
     */
    public function run(): void
    {
        $berkala = [
            [
                'no' => 1,
                'judul' => 'Daftar Pejabat wajib lapor LHKPN',
                'deskripsi' => 'Daftar nama pejabat wajib lapor dan telah melaporkan LHKPN',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'Selama masih berlaku',
                'tautan_links' => [['nama' => 'Portal LHKPN KPK', 'url' => 'https://elhkpn.kpk.go.id']],
            ],
            [
                'no' => 2,
                'judul' => 'Rencana Strategis (Renstra)',
                'deskripsi' => 'Rencana Strategis (Renstra) PKTJ',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit_informasi' => 'Bagian Perencanaan',
                'penanggung_jawab' => 'Bagian Perencanaan',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => '5 (lima) tahun',
                'tautan_links' => [],
            ],
            [
                'no' => 3,
                'judul' => 'Rencana Kerja Tahunan (RKT) PKTJ Tahun 2025',
                'deskripsi' => 'Penjabaran dari sasaran dan program yang telah ditetapkan dalam RENSTRA dan akan dilaksanakan oleh BPSDMP',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit_informasi' => 'Bagian Perencanaan',
                'penanggung_jawab' => 'Bagian Perencanaan',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => '1 (satu) tahun',
                'tautan_links' => [],
            ],
            [
                'no' => 4,
                'judul' => 'RKA-KL PKTJ Tahun 2025',
                'deskripsi' => 'Ringkasan rencana kerja anggaran yang berisi program dan kegiatan PKTJ',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit_informasi' => 'Bagian Perencanaan',
                'penanggung_jawab' => 'Bagian Perencanaan',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => '1 (satu) tahun',
                'tautan_links' => [],
            ],
            [
                'no' => 5,
                'judul' => 'Perjanjian Kinerja (PK) PKTJ tahun 2025',
                'deskripsi' => 'Perjanjian Kinerja merupakan rencana kinerja tahunan yang merupakan penjabaran dari RENSTRA',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit_informasi' => 'Bagian Perencanaan',
                'penanggung_jawab' => 'Bagian Perencanaan',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => '1 (satu) tahun',
                'tautan_links' => [],
            ],
            [
                'no' => 6,
                'judul' => 'DIPA INDUK PKTJ Tahun 2025',
                'deskripsi' => 'Informasi tentang program dan kegiatan beserta anggaran PKTJ',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit_informasi' => 'Bagian Perencanaan',
                'penanggung_jawab' => 'Bagian Perencanaan',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => '1 (satu) tahun',
                'tautan_links' => [],
            ],
            [
                'no' => 7,
                'judul' => 'Laporan Keuangan PKTJ',
                'deskripsi' => 'Laporan Realisasi Anggaran (LRA), neraca, Laporan Operasional, Laporan Perubahan Ekuitas dan Catatan atas Laporan Keuangan PKTJ yang telah di audit oleh BPK-RI',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit_informasi' => 'Bagian Keuangan',
                'penanggung_jawab' => 'Bagian Keuangan',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => '1 (satu) tahun',
                'tautan_links' => [],
            ],
            [
                'no' => 8,
                'judul' => 'Laporan Kinerja PKTJ',
                'deskripsi' => 'Informasi Pelaporan Kinerja dan Tata Cara Reviu atas Laporan Kinerja Instansi Pemerintah',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit_informasi' => 'Bagian Perencanaan',
                'penanggung_jawab' => 'Bagian Perencanaan',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => '1 (satu) tahun',
                'tautan_links' => [],
            ],
            [
                'no' => 9,
                'judul' => 'Laporan Tahunan Unit Kerja di lingkungan PKTJ',
                'deskripsi' => 'Informasi pertanggungjawaban atas pelaksanaan kegiatan yang telah dilaksanakan unit kerja di lingkungan PKTJ',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit_informasi' => 'Bagian Perencanaan',
                'penanggung_jawab' => 'Bagian Perencanaan',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => '1 (satu) tahun',
                'tautan_links' => [],
            ],
            [
                'no' => 10,
                'judul' => 'Buku Statistik Unit Kerja di lingkungan PKTJ',
                'deskripsi' => 'Informasi data peserta dan lulusan pendidikan dan pelatihan perhubungan berdasarkan jenis pendidikan dan pelatihan, data tenaga pendidik dan data kapasitas prasarana diklat di PKTJ',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit_informasi' => 'Bagian Perencanaan',
                'penanggung_jawab' => 'Bagian Perencanaan',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => '1 (satu) tahun',
                'tautan_links' => [],
            ],
            [
                'no' => 11,
                'judul' => 'Profil Unit Kerja di lingkungan PKTJ',
                'deskripsi' => 'Informasi mengenai kedudukan, alamat lengkap, kontak, Gambaran umum, tupoksi',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'Website, hardcopy, dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'Selama masih berlaku',
                'tautan_links' => [['nama' => 'Profil PPID PKTJ', 'url' => '/profil/profil-ppid']],
            ],
            [
                'no' => 12,
                'judul' => 'Profil Singkat Pejabat PKTJ',
                'deskripsi' => 'Direktur, Wakil Direktur,Pejabat Struktural eselon 3',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'Website, softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'Selama masih berlaku',
                'tautan_links' => [['nama' => 'Profil PPID PKTJ', 'url' => '/profil/profil-ppid']],
            ],
            [
                'no' => 13,
                'judul' => 'Peta Jabatan di Unit kerja PKTJ',
                'deskripsi' => 'nama Jabatan Fungsional Umum dan Fungsional tertentu',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'Selama masih berlaku',
                'tautan_links' => [],
            ],
            [
                'no' => 14,
                'judul' => 'Tarif Akademik dan Penunjang Akademik',
                'deskripsi' => 'SK Tarif Layanan Penunjang Akdemik dan Layanan Akademik, serta PMK Tarif PKTJ',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => '1 (satu) tahun',
                'tautan_links' => [],
            ],
            [
                'no' => 15,
                'judul' => 'PMK PSAK PKTJ',
                'deskripsi' => 'Penyampaian Salinan Keputusan Menteri Perhubungan pada Satker BLU PKTJ',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'Selama masih berlaku',
                'tautan_links' => [],
            ],
            [
                'no' => 16,
                'judul' => 'KMK Remunerasi',
                'deskripsi' => 'Penetapan Remunerasi Pejabat Pengelola, Dewas dan Pegawai di lingkungan PKTJ',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'Selama masih berlaku',
                'tautan_links' => [],
            ],
            [
                'no' => 17,
                'judul' => 'Informasi pendidikan dan pelatihan yang diselenggarakan',
                'deskripsi' => 'Informasi terkait kriteria umum program kriteria umum program diklat, waktu pelaksanaan, lama diklat, persyaratan diklat, dan biaya',
                'pejabat_penguasa' => 'Ketua Kelompok Kerja Diklat',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => '1 (satu) tahun',
                'tautan_links' => [],
            ],
            [
                'no' => 18,
                'judul' => 'Panduan pendaftaran pendidikan dan pelatihan yang diselenggarakan',
                'deskripsi' => 'Informasi mengenai alur pendaftaran, tata cara pendaftaran dan panduan pembayaran biaya pendaftaran',
                'pejabat_penguasa' => 'Ketua Kelompok Kerja Diklat',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => '1 (satu) tahun',
                'tautan_links' => [],
            ],
            [
                'no' => 19,
                'judul' => 'Kalender akademik',
                'deskripsi' => 'Kalender kegiatan akademik dalam satu tahun ajaran',
                'pejabat_penguasa' => 'Ketua Tim Sub. Bidang Administrasi Ketarunaan dan',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'Selama masih berlaku',
                'tautan_links' => [],
            ],
            [
                'no' => 20,
                'judul' => 'Biaya Layanan Pendidikan dan Pelatihan Perhubungan',
                'deskripsi' => 'Informasi tentang biaya pendidikan dan pelatiihan bidang transportasi darat',
                'pejabat_penguasa' => 'Al i Unit Pengembangan Usaha',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ Satker BLU',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ Satker BLU',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'Selama masih berlaku',
                'tautan_links' => [],
            ],
            [
                'no' => 21,
                'judul' => 'Struktur PPID di lingkungan PKTJ',
                'deskripsi' => 'Struktur PPID Pelaksana UPT PKTJ',
                'pejabat_penguasa' => 'PPID',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'Selama masih berlaku',
                'tautan_links' => [['nama' => 'Struktur PPID PKTJ', 'url' => '/profil/struktur-organisasi']],
            ],
            [
                'no' => 22,
                'judul' => 'Rekapitulasi PPID Pelaksana UPT',
                'deskripsi' => 'Berisi rekapitulalsi PPID Pelaksana UPT beserta SK Pembentukannya',
                'pejabat_penguasa' => 'PPID',
                'penerbit_informasi' => 'Kabag Umum',
                'penanggung_jawab' => 'Kabag Umum',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'Selama masih berlaku',
                'tautan_links' => [],
            ],
            [
                'no' => 23,
                'judul' => 'Dokumen Kurikulum',
                'deskripsi' => 'Berisi tentang SK tentang Kurikulum Pendidikan Tinggi masing-masing Program Studi di PKTJ',
                'pejabat_penguasa' => 'Ka. Prodi',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2019',
                'jangka_waktu' => 'Selama masih berlaku',
                'tautan_links' => [],
            ],
            [
                'no' => 24,
                'judul' => 'Jadwal Diklat Teknis',
                'deskripsi' => 'Berisi tentang Jadwal Rencana Diklat Teknis di PKTJ',
                'pejabat_penguasa' => 'Ketua Kelompok Kerja Diklat',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'Selama masih berlaku',
                'tautan_links' => [],
            ],
        ];

        $setiapSaat = [
            [
                'no' => 1,
                'judul' => 'Buku pedoman pengasuhan taruna',
                'deskripsi' => 'Buku yang memuat berbagai tata cara, aturan, ketentuan dalam pengasuhan Taruna',
                'pejabat_penguasa' => 'Kapus Pembangunan Karakter',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal , 2025',
                'jangka_waktu' => 'selama masih berlaku',
                'tautan_links' => [],
            ],
            [
                'no' => 2,
                'judul' => 'Ringkasan atau statistik peserta diklat',
                'deskripsi' => 'PKTJ Berisi informasi jumlah dan nama peserta diklat',
                'pejabat_penguasa' => 'Ketua Kelompok Kerja Diklat',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => ', 2023, 2025',
                'jangka_waktu' => 'hingga terdapat pemutakhiran',
                'tautan_links' => [],
            ],
            [
                'no' => 3,
                'judul' => 'Daftar nama Fungsional Instruktur',
                'deskripsi' => 'Berisi informasi jumlah dan nama instruktur PKTJ',
                'pejabat_penguasa' => 'Ka. Prodi',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal , 2025',
                'jangka_waktu' => 'hingga terdapat pemutakhiran',
                'tautan_links' => [],
            ],
            [
                'no' => 4,
                'judul' => 'Daftar nama Fungsional Dosen',
                'deskripsi' => 'Berisi informasi jumlah dan nama dosen PKTJ',
                'pejabat_penguasa' => 'Ka. Prodi',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal , 2025',
                'jangka_waktu' => 'hingga terdapat pemutakhiran',
                'tautan_links' => [],
            ],
            [
                'no' => 5,
                'judul' => 'Kurikulum dan Silabus Pendidikan dan Pelatihan',
                'deskripsi' => 'Kurikulum dan Silabus pendidikan dan pelatihan bidang transportasi darat',
                'pejabat_penguasa' => 'Ka. Prodi',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2019',
                'jangka_waktu' => 'hingga terdapat pemutakhiran',
                'tautan_links' => [],
            ],
            [
                'no' => 6,
                'judul' => 'P h b Daftar barang ruangan',
                'deskripsi' => 'Informasi mengenai jenis dan jumlah barang yang terdapat disetiap ruangan',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal , 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 7,
                'judul' => 'Daftar stok opname ATK',
                'deskripsi' => 'Informasi mengenai ketersediaan ATK (jumlah keluar dan masuknya ATK)',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'aplikasi',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal , 2025',
                'jangka_waktu' => 'hingga terdapat pemutakhiran',
                'tautan_links' => [],
            ],
            [
                'no' => 8,
                'judul' => 'Dokumentasi kegiatan Pimpinan',
                'deskripsi' => 'Foto kegiatan Pimpinan PKTJ',
                'pejabat_penguasa' => 'Humas/PPID',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal , 2025',
                'jangka_waktu' => 'selama masih berlaku',
                'tautan_links' => [],
            ],
            [
                'no' => 9,
                'judul' => 'i k j PKTJ Dokumentasi Sarana dan Prasarana Diklat PKTJ',
                'deskripsi' => 'Foto Sarana dan Prasarana Diklat di lingkungan PKTJ',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal , 2025',
                'jangka_waktu' => 'selama masih berlaku',
                'tautan_links' => [],
            ],
            [
                'no' => 10,
                'judul' => 'Ortaker Unit Kerja di lingkungan PKTJ',
                'deskripsi' => 'Susunan organisasi dan tata kerja unit kerja di lingkungan PKTJ yang disahkan melalui Peraturan Menteri Perhubungan',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal , 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 11,
                'judul' => 'Peraturan, keputusan, dan kebijakan Direktur PKTJ',
                'deskripsi' => 'Informasi mengenai peraturan, keputusan, instruksi dan surat edaran Direktur PKTJ',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal , 2025',
                'jangka_waktu' => 'selama masih digunakan dan/ atau belum ada penggantinya',
                'tautan_links' => [],
            ],
            [
                'no' => 12,
                'judul' => 'Keputusan Kepala Unit Kerja PKTJ',
                'deskripsi' => 'Informasi mengenai Keputusan kepala Unit Kerja di lingkungan PKTJ',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal , 2025',
                'jangka_waktu' => 'selama masih digunakan dan/ atau belum ada penggantinya',
                'tautan_links' => [],
            ],
            [
                'no' => 13,
                'judul' => 'Perjanjian dengan Pihak Ketiga',
                'deskripsi' => 'Informasi Perjanjian/ kesepakatan bersama antara PKTJ dengan pihak lain',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Kerjasama dan Pengembangan',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal , 2025',
                'jangka_waktu' => 'selama masih berlaku',
                'tautan_links' => [],
            ],
            [
                'no' => 14,
                'judul' => 'Daftar rekapan PNS dan Pegawai non PNS di lingkungan',
                'deskripsi' => 'berisi informasi jumlah dan nama pegawai aktif',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal , 2025',
                'jangka_waktu' => 'hingga terdapat pemutakhiran',
                'tautan_links' => [],
            ],
            [
                'no' => 15,
                'judul' => 'PKTJ Daftar nominatif pegawai PKTJ',
                'deskripsi' => 'daftar nominatif pegawai berdasarkan jabatan',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal , 2025',
                'jangka_waktu' => 'hingga terdapat pemutakhiran',
                'tautan_links' => [],
            ],
            [
                'no' => 16,
                'judul' => 'Laporan data perbendaharaan dan inventaris unit kerja di PKTJ',
                'deskripsi' => 'berisi inforasi mengenai mutasi tambah kurang, penyusutan, penetapan status penggunaan, penghapusan BMN di PKTJ yang telah diaudit oleh BPK-RI',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal , 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 17,
                'judul' => 'SOP tata naskah dan persuratan',
                'deskripsi' => 'informasi mengenai aturansistem administrasi perkantoran, kode klasifikasi arsip, dan tata naskah dinas',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'aplikasi',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal , 2025',
                'jangka_waktu' => 'selama masih digunakan dan/ atau belum ada penggantinya',
                'tautan_links' => [],
            ],
            [
                'no' => 18,
                'judul' => 'Daftar penomoran surat di PKTJ',
                'deskripsi' => 'Informasi mengenai surat menyurat, proses penomoran surat masuk, surat keluar, nota dinas, peraturan/ keputusan direktur, serta keputusan KPA',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal , 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 19,
                'judul' => 'Daftar arsip unit kerja di lingkungan PKTJ',
                'deskripsi' => 'Informasi mengenai penataan dokumen yang tersimpan menurut bagian di dalam ruang arsip yang tersedia',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal , 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 20,
                'judul' => 'Data Operasional Perkantoran unit kerja di lingkungan',
                'deskripsi' => 'Informasi penyelenggaraan operasional dan pemeliharaan perkantoran',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal , 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 21,
                'judul' => 'PKTJ Data inventaris kendaraan bermotor',
                'deskripsi' => 'Informasi mengenai tahun, jenis, pemegang kendaraan serta BPKB dan STNK kendaraan operasional roda 4',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2023, 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 22,
                'judul' => 'Data inventaris peralatan kantor',
                'deskripsi' => 'd d 2 Label informasi mengenai tahunpengadaan barang yang terdapat dalam suatu ruangan',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 23,
                'judul' => 'Dokumen terkait bantuan tugas belajar',
                'deskripsi' => 'Pelaksanaan kegiatan bantuan tugas belajar',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 24,
                'judul' => 'Dokumen terkait Beasiswa',
                'deskripsi' => 'Pelaksanaan kegiatan pemberian beasiswa',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 25,
                'judul' => 'Dokumen terkait Assesment Jabatan Struktural',
                'deskripsi' => 'Pelaksanaan kegiatan Assesment Jabatan Struktural',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 26,
                'judul' => 'Dokumen terkait Assesment Dosen',
                'deskripsi' => 'Pelaksanaan kegiatan Assesment Dosen',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 27,
                'judul' => 'Dokumen terkait Ujian Dinas',
                'deskripsi' => 'Pelaksanaan kegiatan Ujian Dinas',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 28,
                'judul' => 'Surat Menyurat',
                'deskripsi' => 'Surat menyurat terkait tupoksi unit kerja di lingkungan PKTJ',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 29,
                'judul' => 'Daftar Absensi perpustakaan',
                'deskripsi' => 'Absensi pengunjung Perpustakaan',
                'pejabat_penguasa' => 'Unit Perpustakaan',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 30,
                'judul' => 'Daftar Inventarisasi Buku',
                'deskripsi' => 'Daftar inventaris buku perpustakaan',
                'pejabat_penguasa' => 'Unit Perpustakaan',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 31,
                'judul' => 'Daftar Judul Buku',
                'deskripsi' => 'Daftar judul buku yang tersedia di perpustakaan',
                'pejabat_penguasa' => 'Unit Perpustakaan',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 32,
                'judul' => 'Daftar Inventarisasi Laboratorium CBT',
                'deskripsi' => 'Daftar inventaris laboratorium CBT',
                'pejabat_penguasa' => 'Unit IT',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 33,
                'judul' => 'Daftar Absensi Laboratorium CBT',
                'deskripsi' => 'Absensi pengunjung Laboratorium CBT',
                'pejabat_penguasa' => 'Unit IT',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 34,
                'judul' => 'Daftar Inventarisasi Laboratorium',
                'deskripsi' => 'Daftar inventaris kelengkapan sarana di laboratorium',
                'pejabat_penguasa' => 'Unit Laboratorium',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 35,
                'judul' => 'Daftar Absensi Laboratorium',
                'deskripsi' => 'ji Daftar absensi pengunjung laboratorium pengujian',
                'pejabat_penguasa' => 'Unit Laboratorium',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 36,
                'judul' => 'Daftar Inventarisasi Laboratorium Bahasa',
                'deskripsi' => 'Daftar inventaris laboratorium bahasa',
                'pejabat_penguasa' => 'Unit Laboratorium',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 37,
                'judul' => 'Daftar Absensi Laboratorium Bahasa',
                'deskripsi' => 'Absensi pengunjung laboratorium bahasa',
                'pejabat_penguasa' => 'Unit Laboratorium',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 38,
                'judul' => 'Daftar Inventaris Asrama',
                'deskripsi' => 'Daftar inventaris masing- masing asrama',
                'pejabat_penguasa' => 'bahasa Unit Asrama',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 39,
                'judul' => 'Daftar Asrama Dan Kapasitas',
                'deskripsi' => 'Daftar Jumlah Asrama dan Kapasitas masing- masing asrama',
                'pejabat_penguasa' => 'Unit Asrama',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 40,
                'judul' => 'Daftar obat-obatan Poliklinik',
                'deskripsi' => 'Informasi tentang obat-obatan meliputi kegunaan obat, kandungan dalam obat, aturan pemakaian, indikasi, peringatan',
                'pejabat_penguasa' => 'Ka Unit Poliklinik',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'hingga terdapat pemutakhiran',
                'tautan_links' => [],
            ],
            [
                'no' => 41,
                'judul' => 'Tarif BLU di lingkungan PKTJ',
                'deskripsi' => 'obat Informasi jenis dan tarif layanan BLU (sesuai PMK yang diterbitkan oleh Kementerian Keuangan)',
                'pejabat_penguasa' => 'Ka Unit Pengembangan Usaha',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'hingga terdapat pemutakhiran',
                'tautan_links' => [],
            ],
            [
                'no' => 42,
                'judul' => 'Tarif PNBP Diklat dan Sarana Prasarana',
                'deskripsi' => 'Tarif PNBP yang telah disahkan oleh Kemenkeu RI',
                'pejabat_penguasa' => 'Ka Unit Pengembangan Usaha',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'hingga terdapat pemutakhiran',
                'tautan_links' => [],
            ],
            [
                'no' => 43,
                'judul' => 'Dokumen hasil penelitian dosen, instruktur, dan/atau Taruna (peserta',
                'deskripsi' => 'Dokumen hasil penelitian yang dilakukan oleh dosen, instruktur, dan/atau Taruna PKTJ',
                'pejabat_penguasa' => 'Kapus P3M',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2024',
                'jangka_waktu' => 'hingga terdapat pemutakhiran',
                'tautan_links' => [],
            ],
            [
                'no' => 44,
                'judul' => 'dikl t) Pedoman Mutu',
                'deskripsi' => 'Dokumentasi yang berisi pernyataan dan komitmen organisasi yang menggambarkan latar belakang, kebijakan, dan sasaran',
                'pejabat_penguasa' => 'Kepala Satuan Penjamin Mutu',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 45,
                'judul' => 'Dokumen dewan pengawas',
                'deskripsi' => 'i i Informasi tentang anggota dewan pengawas',
                'pejabat_penguasa' => 'Ketua SPI',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2024',
                'jangka_waktu' => 'sesuai retensi arsip',
                'tautan_links' => [],
            ],
            [
                'no' => 46,
                'judul' => 'Tata tertib asrama',
                'deskripsi' => 'Tata tertib di lingkungan asrama',
                'pejabat_penguasa' => 'Ka. Pusbangkar/Kep ala Unit Asrama',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2024, 2025',
                'jangka_waktu' => 'selama masih digunakan dan/ atau belum ada penggantinya',
                'tautan_links' => [],
            ],
            [
                'no' => 47,
                'judul' => 'Daftar Informasi Publik',
                'deskripsi' => 'Daftar informasi yang disediakan oleh unit kerja',
                'pejabat_penguasa' => 'PPID',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'hingga terdapat pemutakhiran',
                'tautan_links' => [['nama' => 'Daftar Informasi Publik', 'url' => '/informasi-publik/berkala']],
            ],
            [
                'no' => 48,
                'judul' => 'Alur Prosedur Pelayanan Informasi',
                'deskripsi' => 'PKTJ SOP Permohonan Informasi Publik sesuai dengan PM 46 tahun 2018',
                'pejabat_penguasa' => 'PPID',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'selama masih digunakan dan/ atau belum ada penggantinya',
                'tautan_links' => [['nama' => 'SOP Permohonan Informasi', 'url' => '/prosedur/permintaan-informasi']],
            ],
            [
                'no' => 49,
                'judul' => 'Tata cara permohonan informasi publik dan pengajuan keberatan',
                'deskripsi' => 'Mekanisme permohonan informasi dan pengajuan keberatan informasi publik',
                'pejabat_penguasa' => 'PPID',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2025',
                'jangka_waktu' => 'selama masih digunakan dan/ atau belum ada penggantinya',
                'tautan_links' => [['nama' => 'SOP Permohonan Informasi', 'url' => '/prosedur/permintaan-informasi']],
            ],
        ];

        $sertaMerta = [
            [
                'no' => 1,
                'judul' => 'Pengumuman hasil seleksi TPA Sipencatar',
                'deskripsi' => 'Informasi peserta Sipencatar yang lulus seleksi TPA',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang administrasi akademik',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2024',
                'jangka_waktu' => 'selama masih berlaku',
                'tautan_links' => [['nama' => 'Portal SIPENCATAR Kemenhub', 'url' => 'https://sipencatar.dephub.go.id']],
            ],
            [
                'no' => 2,
                'judul' => 'Pengumuman hasil seleksi akhir sipencatar',
                'deskripsi' => 'Informasi peserta Sipencatar yang lulus hasil pantukhir dan diterima sebagai calon Mahasiswa/i',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang administrasi akademik',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2024',
                'jangka_waktu' => 'selama masih berlaku',
                'tautan_links' => [['nama' => 'Portal SIPENCATAR Kemenhub', 'url' => 'https://sipencatar.dephub.go.id']],
            ],
            [
                'no' => 3,
                'judul' => 'Pengumuman hasil seleksi Kesehatan Sipencatar',
                'deskripsi' => 'Informasi peserta Sipencatar yang lulus seleksi Kesehatan',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang administrasi akademik',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2024',
                'jangka_waktu' => 'selama masih berlaku',
                'tautan_links' => [['nama' => 'Portal SIPENCATAR Kemenhub', 'url' => 'https://sipencatar.dephub.go.id']],
            ],
            [
                'no' => 4,
                'judul' => 'Panduan Pendaftaran Sipencatar',
                'deskripsi' => 'Informasi mengenai alur pendaftaran, tatacara pendaftaran, dan panduan pembayaran biaya pendaftaran',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang administrasi akademik',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2024',
                'jangka_waktu' => '1 (satu) tahun',
                'tautan_links' => [['nama' => 'Portal SIPENCATAR Kemenhub', 'url' => 'https://sipencatar.dephub.go.id']],
            ],
            [
                'no' => 5,
                'judul' => 'Informasi Sipencatar',
                'deskripsi' => 'Informasi terkait kriteria umum pendaftar, lokasi tes, jadwal seleksi, program studi, biaya seleksi, persyaratan ijazah dll',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang administrasi akademik',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2024',
                'jangka_waktu' => '1 (satu) tahun',
                'tautan_links' => [['nama' => 'Portal SIPENCATAR Kemenhub', 'url' => 'https://sipencatar.dephub.go.id']],
            ],
            [
                'no' => 6,
                'judul' => 'Pengumuman hasil seleksi Psikologi Sipencatar',
                'deskripsi' => 'Informasi peserta Sipencatar yang lulus seleksi Psikologi',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang administrasi akademik',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2024',
                'jangka_waktu' => 'selama masih berlaku',
                'tautan_links' => [['nama' => 'Portal SIPENCATAR Kemenhub', 'url' => 'https://sipencatar.dephub.go.id']],
            ],
            [
                'no' => 7,
                'judul' => 'Pengumuman hasil selekasi akhir sipencatar',
                'deskripsi' => 'Informasi peserta Sipencatar yang lulus hasil pantukhir dan diterima sebagai calon taruna',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang administrasi akademik',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => 'Tegal, 2024',
                'jangka_waktu' => 'selama masih berlaku',
                'tautan_links' => [['nama' => 'Portal SIPENCATAR Kemenhub', 'url' => 'https://sipencatar.dephub.go.id']],
            ],
        ];

        // 1. Sinkronisasi Informasi Berkala (24 Dokumen)
        InformasiBerkala::query()->delete();
        foreach ($berkala as $b) {
            InformasiBerkala::create([
                'judul' => $b['judul'],
                'deskripsi' => $b['deskripsi'],
                'pejabat_penguasa' => $b['pejabat_penguasa'],
                'penerbit_informasi' => $b['penerbit_informasi'],
                'penanggung_jawab' => $b['penanggung_jawab'],
                'bentuk_informasi' => $b['bentuk_informasi'],
                'tempat_pembuatan' => $b['tempat_pembuatan'],
                'waktu_pembuatan' => $b['waktu_pembuatan'],
                'jangka_waktu' => $b['jangka_waktu'],
                'file_path' => null,
                'tautan_links' => $b['tautan_links'],
                'aktif' => true,
                'bisa_download' => true,
                'tanggal' => date('Y-m-d')
            ]);
        }

        // 2. Sinkronisasi Informasi Setiap Saat (49 Dokumen)
        InformasiSetiapSaat::query()->delete();
        foreach ($setiapSaat as $s) {
            InformasiSetiapSaat::create([
                'judul' => $s['judul'],
                'deskripsi' => $s['deskripsi'],
                'pejabat_penguasa' => $s['pejabat_penguasa'],
                'penerbit_informasi' => $s['penerbit_informasi'],
                'penanggung_jawab' => $s['penanggung_jawab'],
                'bentuk_informasi' => $s['bentuk_informasi'],
                'tempat_pembuatan' => $s['tempat_pembuatan'],
                'waktu_pembuatan' => $s['waktu_pembuatan'],
                'jangka_waktu' => $s['jangka_waktu'],
                'file_path' => null,
                'tautan_links' => $s['tautan_links'],
                'aktif' => true,
                'bisa_download' => true,
                'tanggal' => date('Y-m-d')
            ]);
        }

        // 3. Sinkronisasi Informasi Serta Merta (7 Dokumen)
        InformasiSertaMerta::query()->delete();
        foreach ($sertaMerta as $sm) {
            InformasiSertaMerta::create([
                'judul' => $sm['judul'],
                'deskripsi' => $sm['deskripsi'],
                'pejabat_penguasa' => $sm['pejabat_penguasa'],
                'penerbit_informasi' => $sm['penerbit_informasi'],
                'penanggung_jawab' => $sm['penanggung_jawab'],
                'bentuk_informasi' => $sm['bentuk_informasi'],
                'tempat_pembuatan' => $sm['tempat_pembuatan'],
                'waktu_pembuatan' => $sm['waktu_pembuatan'],
                'jangka_waktu' => $sm['jangka_waktu'],
                'file_path' => null,
                'tautan_links' => $sm['tautan_links'],
                'aktif' => true,
                'bisa_download' => true,
                'tanggal' => date('Y-m-d')
            ]);
        }

        // 4. Sinkronisasi Master Daftar Informasi Publik (80 Dokumen)
        DaftarInformasi::query()->delete();
        foreach ($berkala as $b) {
            DaftarInformasi::create([
                'judul_informasi' => $b['judul'],
                'isi_informasi' => $b['deskripsi'],
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'Berkala',
                'pejabat_penguasa' => $b['pejabat_penguasa'],
                'penerbit_informasi' => $b['penerbit_informasi'],
                'penanggung_jawab' => $b['penanggung_jawab'],
                'bentuk_informasi' => $b['bentuk_informasi'],
                'tempat_pembuatan' => $b['tempat_pembuatan'],
                'waktu_pembuatan' => $b['waktu_pembuatan'],
                'jangka_waktu' => $b['jangka_waktu'],
                'file_informasi' => null,
                'tautan_links' => $b['tautan_links'],
                'aktif' => true,
                'bisa_download' => true
            ]);
        }
        foreach ($setiapSaat as $s) {
            DaftarInformasi::create([
                'judul_informasi' => $s['judul'],
                'isi_informasi' => $s['deskripsi'],
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'Setiap Saat',
                'pejabat_penguasa' => $s['pejabat_penguasa'],
                'penerbit_informasi' => $s['penerbit_informasi'],
                'penanggung_jawab' => $s['penanggung_jawab'],
                'bentuk_informasi' => $s['bentuk_informasi'],
                'tempat_pembuatan' => $s['tempat_pembuatan'],
                'waktu_pembuatan' => $s['waktu_pembuatan'],
                'jangka_waktu' => $s['jangka_waktu'],
                'file_informasi' => null,
                'tautan_links' => $s['tautan_links'],
                'aktif' => true,
                'bisa_download' => true
            ]);
        }
        foreach ($sertaMerta as $sm) {
            DaftarInformasi::create([
                'judul_informasi' => $sm['judul'],
                'isi_informasi' => $sm['deskripsi'],
                'kategori' => 'informasi-serta-merta',
                'tipe_informasi' => 'Serta Merta',
                'pejabat_penguasa' => $sm['pejabat_penguasa'],
                'penerbit_informasi' => $sm['penerbit_informasi'],
                'penanggung_jawab' => $sm['penanggung_jawab'],
                'bentuk_informasi' => $sm['bentuk_informasi'],
                'tempat_pembuatan' => $sm['tempat_pembuatan'],
                'waktu_pembuatan' => $sm['waktu_pembuatan'],
                'jangka_waktu' => $sm['jangka_waktu'],
                'file_informasi' => null,
                'tautan_links' => $sm['tautan_links'],
                'aktif' => true,
                'bisa_download' => true
            ]);
        }
    }
}
