<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DipSeeder extends Seeder
{
    public function run()
    {
        // 1. Seed daftar_informasis
        DB::table('daftar_informasis')->truncate();

        $data = [
        [
            'judul_informasi' => 'Dokumen Kurikulum',
            'kategori' => 'informasi-setiap-saat',
            'isi_informasi' => 'Hasil review kurikulum Prodi TRO. Kurikulum lama (tahun 2020) diganti dengan kurikulum baru (2025)',
            'pejabat_penguasa' => 'Kepala Progam Studi Teknologi Rekayasa Otomotif (TRO)',
            'penanggung_jawab' => 'Prodi TRO Politeknik Keselamatan Transportasi Jalan',
            'penerbit_informasi' => 'Prodi TRO Politeknik Keselamatan Transportasi Jalan',
            'bentuk_informasi' => 'Softcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2026',
            'jangka_waktu' => 'Selama masih berlaku',
            'file_informasi' => 'https://drive.google.com/file/d/1JvAj5qveSh5KW55HlTzEPNWd2XeQuFSU/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2026-01-01 00:00:00',
            'updated_at' => '2026-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Dokumen Kurikulum',
            'kategori' => 'informasi-setiap-saat',
            'isi_informasi' => 'Hasil review kurikulum Prodi RSTJ. Kurikulum lama (tahun 2020) diganti dengan kurikulum baru (2025)',
            'pejabat_penguasa' => 'Kepala Progam Studi Rekayasa Sistem Transportasi Jalan (RSTJ)',
            'penanggung_jawab' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
            'penerbit_informasi' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
            'bentuk_informasi' => 'Softcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => 'Selama masih berlaku',
            'file_informasi' => 'https://drive.google.com/file/d/1y6IgSsr8_Nan6lx9x3MS8tNNodGIzxYM/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Dokumen Kurikulum',
            'kategori' => 'informasi-setiap-saat',
            'isi_informasi' => 'Kurikulum Prodi TO. Kurikulum lama (tahun 2020) diganti dengan kurikulum baru (2025)',
            'pejabat_penguasa' => 'Kepala Progam Studi Diploma III Teknologi Otomotif (TO)',
            'penanggung_jawab' => 'Prodi Diploma III TO Politeknik Keselamatan Transportasi Jalan',
            'penerbit_informasi' => 'Prodi Diploma III TO Politeknik Keselamatan Transportasi Jalan',
            'bentuk_informasi' => 'Softcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => 'Selama masih berlaku',
            'file_informasi' => 'https://drive.google.com/file/d/1cyX-7EgNPsdcsgT2CiBt6b5skNLHGcgv/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Dokumen Kurikulum',
            'kategori' => 'informasi-setiap-saat',
            'isi_informasi' => 'Hasil review kurikulum Prodi TO. Kurikulum lama (tahun 2020) diganti dengan kurikulum baru (2025)',
            'pejabat_penguasa' => 'Kepala Progam Studi Diploma III Teknologi Otomotif (TO)',
            'penanggung_jawab' => 'Prodi Diploma III TO Politeknik Keselamatan Transportasi Jalan',
            'penerbit_informasi' => 'Prodi Diploma III TO Politeknik Keselamatan Transportasi Jalan',
            'bentuk_informasi' => 'Softcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => 'Selama masih berlaku',
            'file_informasi' => 'https://drive.google.com/file/d/1jCxlNseEQufG024MQCutbXfFRLGlnjY3/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Kegiatan Pembelajaran Teaching Factory (TeFa)',
            'kategori' => 'informasi-setiap-saat',
            'isi_informasi' => 'Pedoman TeFa RSTJ',
            'pejabat_penguasa' => 'Kepala Progam Studi Rekayasa Sistem Transportasi Jalan (RSTJ)',
            'penanggung_jawab' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
            'penerbit_informasi' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
            'bentuk_informasi' => 'Softcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '6 bulan',
            'file_informasi' => 'https://drive.google.com/file/d/1U_0Gxo_VDiR44WPU1d3kgzGUWWxwEJZM/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Kegiatan Pembelajaran Teaching Factory (TeFa)',
            'kategori' => 'informasi-setiap-saat',
            'isi_informasi' => 'Progres TeFa RSTJ',
            'pejabat_penguasa' => 'Kepala Progam Studi Rekayasa Sistem Transportasi Jalan (RSTJ)',
            'penanggung_jawab' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
            'penerbit_informasi' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
            'bentuk_informasi' => 'Softcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '6 bulan',
            'file_informasi' => 'https://drive.google.com/file/d/1thfMdVSo7D-kf2cFTtffKmGeDIg-h1gw/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Kegiatan Pembelajaran Teaching Factory (TeFa)',
            'kategori' => 'informasi-setiap-saat',
            'isi_informasi' => 'Produk TeFa RSTJ Kelas A',
            'pejabat_penguasa' => 'Kepala Progam Studi Rekayasa Sistem Transportasi Jalan (RSTJ)',
            'penanggung_jawab' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
            'penerbit_informasi' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
            'bentuk_informasi' => 'Softcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '6 bulan',
            'file_informasi' => 'https://drive.google.com/drive/folders/1JRi9kaNpvPbNkFxWoCl-DMyRkQVRbWog?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Kegiatan Pembelajaran Teaching Factory (TeFa)',
            'kategori' => 'informasi-setiap-saat',
            'isi_informasi' => 'Produk TeFa RSTJ Kelas B',
            'pejabat_penguasa' => 'Kepala Progam Studi Rekayasa Sistem Transportasi Jalan (RSTJ)',
            'penanggung_jawab' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
            'penerbit_informasi' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
            'bentuk_informasi' => 'Softcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '6 bulan',
            'file_informasi' => 'https://drive.google.com/drive/folders/1Q1Hlce9Fc8ndhC5vRVHcW10KdtnsGkeC?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Kegiatan Pembelajaran Teaching Factory (TeFa)',
            'kategori' => 'informasi-setiap-saat',
            'isi_informasi' => 'SK PENUNJUKAN TIM TeFa 2025',
            'pejabat_penguasa' => 'Kepala Progam Studi Teknologi Rekayasa Otomotif (TRO)',
            'penanggung_jawab' => 'Prodi TRO Politeknik Keselamatan Transportasi Jalan',
            'penerbit_informasi' => 'Prodi TRO Politeknik Keselamatan Transportasi Jalan',
            'bentuk_informasi' => 'Softcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '6 Bulan',
            'file_informasi' => 'https://drive.google.com/file/d/1UqUH_JDSE84qvKkT-KrdFjCb53XJTX0i/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Kegiatan Pembelajaran Teaching Factory (TeFa)',
            'kategori' => 'informasi-setiap-saat',
            'isi_informasi' => 'Produk TeFa TRO',
            'pejabat_penguasa' => 'Kepala Progam Studi Teknologi Rekayasa Otomotif (TRO)',
            'penanggung_jawab' => 'Prodi TRO Politeknik Keselamatan Transportasi Jalan',
            'penerbit_informasi' => 'Prodi TRO Politeknik Keselamatan Transportasi Jalan',
            'bentuk_informasi' => 'Softcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '6 Bulan',
            'file_informasi' => 'https://drive.google.com/drive/folders/1aa9YRTIqn9ivjQcX05aA-YJbj-kuC2DF?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Kontrak',
            'kategori' => 'informasi-setiap-saat',
            'isi_informasi' => 'Kontrak adalah kesepakatan atau perjanjian mengikat secara hukum antara dua pihak atau lebih yang menciptakan kewajiban tertentu bagi masing-masing pihak, mengatur hak dan tanggung jawab mereka, serta dapat ditegakkan secara hukum jika terjadi wanprestasi, bisa dalam bentuk lisan atau tulisan, dan seringkali merupakan bagian dari perjanjian yang lebih luas (perikatan).',
            'pejabat_penguasa' => 'Katim Kerjasama',
            'penanggung_jawab' => 'Tim Kerjasama',
            'penerbit_informasi' => 'Tim Kerjasama',
            'bentuk_informasi' => 'softcopy dan hardcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '1 tahun',
            'file_informasi' => 'https://drive.google.com/drive/folders/1FbW3mYEQqomLvakp-TtHWCnm-JwPZMDh?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Laporan kebersihan asrama',
            'kategori' => 'informasi-setiap-saat',
            'isi_informasi' => 'pengecekan kebersihan asrama',
            'pejabat_penguasa' => 'kanit asrama',
            'penanggung_jawab' => 'unit asrama',
            'penerbit_informasi' => 'unit asrama',
            'bentuk_informasi' => 'softfile',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'PKTJ Tegal di tiap akhir bulan',
            'jangka_waktu' => '2 tahun',
            'file_informasi' => 'https://drive.google.com/drive/folders/1qU81c6u8w7zy6oCCF2mLxN_FxIouESxW?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Laporan penanganan keluhan asrama',
            'kategori' => 'informasi-setiap-saat',
            'isi_informasi' => 'tindak lanjut penanganan kekuhan oenghuni asrama',
            'pejabat_penguasa' => 'kanit asrama',
            'penanggung_jawab' => 'unit asrama',
            'penerbit_informasi' => 'unit asrama',
            'bentuk_informasi' => 'softfile',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'PKTJ Tegal di tiap akhir bulan',
            'jangka_waktu' => '2 tahun',
            'file_informasi' => 'https://drive.google.com/drive/folders/1v8dWY5Rpkn0raSdHKxtx21oGclXt0-W_?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Laporan perbaikan fasilitas asrama',
            'kategori' => 'informasi-setiap-saat',
            'isi_informasi' => 'perbaikan yang dilakukan oleh tim unit asrama',
            'pejabat_penguasa' => 'kanit asrama',
            'penanggung_jawab' => 'unit asrama',
            'penerbit_informasi' => 'unit asrama',
            'bentuk_informasi' => 'softfile',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'PKTJ Tegal di tiap akhir bulan',
            'jangka_waktu' => '2 tahun',
            'file_informasi' => 'https://drive.google.com/drive/folders/1dZYayP713qQ2FLxguvs5wGmFc1vv9Sel?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'MoU',
            'kategori' => 'informasi-setiap-saat',
            'isi_informasi' => 'MoU (Memorandum of Understanding) adalah nota kesepahaman atau perjanjian pendahuluan yang berisi pernyataan niat dan kesepakatan awal antara dua pihak atau lebih sebelum membuat kontrak formal yang lebih mengikat secara hukum. MoU berfungsi sebagai landasan awal untuk menjajaki kerja sama, menguraikan tujuan, dan ruang lingkup, namun biasanya tidak mengikat secara hukum seperti kontrak, kecuali ada klausul khusus yang ditambahkan',
            'pejabat_penguasa' => 'Katim Kerjasama',
            'penanggung_jawab' => 'Tim Kerjasama',
            'penerbit_informasi' => 'Tim Kerjasama',
            'bentuk_informasi' => 'softcopy dan hardcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '5 tahun',
            'file_informasi' => 'https://drive.google.com/drive/folders/1FbW3mYEQqomLvakp-TtHWCnm-JwPZMDh?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Perjanjian Kerja Sama',
            'kategori' => 'informasi-setiap-saat',
            'isi_informasi' => 'Perjanjian Kerja Sama (PKS) adalah kesepakatan formal dan mengikat secara hukum antara dua pihak atau lebih untuk bekerja sama mencapai tujuan bersama, yang merinci hak, kewajiban, tanggung jawab, dan pembagian sumber daya untuk suatu proyek atau usaha tertentu, seringkali lebih mengikat daripada MoU (Memorandum of Understanding) yang bersifat pra-kontrak.',
            'pejabat_penguasa' => 'Katim Kerjasama',
            'penanggung_jawab' => 'Tim Kerjasama',
            'penerbit_informasi' => 'Tim Kerjasama',
            'bentuk_informasi' => 'softcopy dan hardcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '5 tahun',
            'file_informasi' => 'https://drive.google.com/drive/folders/1FbW3mYEQqomLvakp-TtHWCnm-JwPZMDh?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Program Kerja SPI',
            'kategori' => 'informasi-setiap-saat',
            'isi_informasi' => 'Program Kerja SPI merupakan dokumen yang berisi tentang rencana tahunan kegiatan pengawasan (audit, reviu, evaluasi) untuk memastikan tujuan organisasi tercapai, pengelolaan keuangan dan aset aman, serta kepatuhan terhadap aturan, mencakup aspek kelembagaan, sistem pengendalian, SDM, dan tindak lanjut temuan audit di PKTJ.',
            'pejabat_penguasa' => 'Kepala SPI',
            'penanggung_jawab' => 'SPI Politeknik Keselamatan Transportasi Jalan',
            'penerbit_informasi' => 'SPI Politeknik Keselamatan Transportasi Jalan',
            'bentuk_informasi' => 'Softcopy dan Hardcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '1 (satu) tahun',
            'file_informasi' => 'https://drive.google.com/file/d/17fHyAY4ctzyzVUIPzhHM2F9o-2Hc0RSi/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Rekapan Pengelolaan CCTV Kampus PKTJ',
            'kategori' => 'informasi-setiap-saat',
            'isi_informasi' => 'Informasi ringkas dan berkala mengenai status fungsionalitas dan lokasi CCTV yang terpasang di area kampus PKTJ.',
            'pejabat_penguasa' => 'Unit IT',
            'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
            'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
            'bentuk_informasi' => 'softcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => 'sesuai retensi arsip',
            'file_informasi' => 'https://drive.google.com/drive/folders/1kBOEMVmvaqK-GkNwlFkldbE0tnXIDWxW?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'SPK/SPMK (Surat Perjanjian Kerja)/(Surat Perintah Mulai Kerja)',
            'kategori' => 'informasi-setiap-saat',
            'isi_informasi' => 'Surat Perjanjian Kerja/Surat Perintah Kerja /Surat Perintah Mulai Kerja adalah dokumen legal yang mengikat secara hukum, berisi perintah resmi dari pemberi kerja (perusahaan/instansi) kepada pekerja/penyedia jasa untuk memulai suatu pekerjaan, serta merinci syarat-syarat kerja, hak, kewajiban, ruang lingkup pekerjaan, batas waktu (durasi), hingga biaya atau nilai kontrak, menjadikannya landasan hukum pelaksanaan proyek atau tugas',
            'pejabat_penguasa' => 'Katim Kerjasama',
            'penanggung_jawab' => 'Tim Kerjasama',
            'penerbit_informasi' => 'Tim Kerjasama',
            'bentuk_informasi' => 'softcopy dan hardcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '1 tahun',
            'file_informasi' => 'https://drive.google.com/drive/folders/1FbW3mYEQqomLvakp-TtHWCnm-JwPZMDh?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Struktur Organisasi Unit Teknologi Informasi',
            'kategori' => 'informasi-setiap-saat',
            'isi_informasi' => 'Struktur organisasi Unit Teknologi Informasi PKTJ yang terdiri dari Kepala Unit Teknologi Informasi di bawah Kepala Bagian Administrasi Akademik dan Ketarunaan, serta Kelompok Jabatan Fungsional. Struktur ini berada di bawah koordinasi Direktur Politeknik Keselamatan Transportasi Jalan',
            'pejabat_penguasa' => 'Unit TI',
            'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
            'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
            'bentuk_informasi' => 'softcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => 'sesuai retensi arsip',
            'file_informasi' => 'https://drive.google.com/file/d/1lLKLUvNEDY8OAUCoOIvV24aFZg3u9JHJ/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Roadmap Penelitian Dan Pengabdian Kepada Masyarakat',
            'kategori' => 'informasi-setiap-saat',
            'isi_informasi' => 'Roadmap Penelitian Dan Pengabdian Kepada Masyarakat Berisi Tema-Tema Penelitian dan PKM selama 5 tahun',
            'pejabat_penguasa' => 'Kepala P3M',
            'penanggung_jawab' => 'P3M Politeknik Keselamatan Transportasi Jalan',
            'penerbit_informasi' => 'P3M Politeknik Keselamatan Transportasi Jalan',
            'bentuk_informasi' => 'Softcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2024',
            'jangka_waktu' => '5 (lima) tahun',
            'file_informasi' => 'https://drive.google.com/file/d/1kg1sCnGls8xv_ZQB2gVQK_Os2kLtu12a/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2024-01-01 00:00:00',
            'updated_at' => '2024-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'SOP Pemberian Layanan Jasa Perpustakaan Dan Informasi Mengenai Sumber Pembelajaran',
            'kategori' => 'informasi-setiap-saat',
            'isi_informasi' => 'Prosedur dan alur layanan peminjaman serta pengembalian buku bagi pemustaka.',
            'pejabat_penguasa' => 'Kepala Unit Perpustakaan',
            'penanggung_jawab' => 'Bagian Penjaminan Mutu PKTJ',
            'penerbit_informasi' => 'Bagian Penjaminan Mutu PKTJ',
            'bentuk_informasi' => 'Hardcopy & Sofcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2023',
            'jangka_waktu' => 'Selama SOP belum direvisi',
            'file_informasi' => 'https://drive.google.com/drive/folders/12LcansqF1ms4T-fTUj1BRyJm-ZK94TaA?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2023-01-01 00:00:00',
            'updated_at' => '2023-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'SOP Pembuatan Surat Bebas Pustaka',
            'kategori' => 'informasi-setiap-saat',
            'isi_informasi' => 'Syarat dan prosedur pengurusan surat keterangan bebas pustaka untuk syarat Wisuda/Kelulusan.',
            'pejabat_penguasa' => 'Kepala Unit Perpustakaan',
            'penanggung_jawab' => 'Bagian Penjaminan Mutu PKTJ',
            'penerbit_informasi' => 'Bagian Penjaminan Mutu PKTJ',
            'bentuk_informasi' => 'Hardcopy & Sofcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2023',
            'jangka_waktu' => 'Selama SOP belum direvisi',
            'file_informasi' => 'https://drive.google.com/drive/folders/1xm0_eKUn8Sd419Cr3f_lgj5y2PjlUddg?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2023-01-01 00:00:00',
            'updated_at' => '2023-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'SOP Pengadaan Bahan Pustaka',
            'kategori' => 'informasi-setiap-saat',
            'isi_informasi' => 'Tata cara pengajuan usulan pengadaan buku oleh Dosen atau Taruna.',
            'pejabat_penguasa' => 'Kepala Unit Perpustakaan',
            'penanggung_jawab' => 'Bagian Penjaminan Mutu PKTJ',
            'penerbit_informasi' => 'Bagian Penjaminan Mutu PKTJ',
            'bentuk_informasi' => 'Hardcopy & Sofcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2023',
            'jangka_waktu' => 'Selama SOP belum direvisi',
            'file_informasi' => 'https://drive.google.com/drive/folders/1FE5gflmJ0NoXv51HMzmbz4Q2HRX21zqA?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2023-01-01 00:00:00',
            'updated_at' => '2023-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Daftar MoU / Kerjasama',
            'kategori' => 'informasi-serta-merta',
            'isi_informasi' => 'Dokumen kerjasama perpustakaan PKTJ dengan perpustakaan perguruan tinggi lain atau instansi.',
            'pejabat_penguasa' => 'Kepala Unit Perpustakaan',
            'penanggung_jawab' => 'Unit Kerjasama / Perpustakaan PKTJ',
            'penerbit_informasi' => 'Unit Kerjasama / Perpustakaan PKTJ',
            'bentuk_informasi' => 'Hardcopy & Sofcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal. Sesuai Tanggal MoU',
            'jangka_waktu' => 'Sesuai masa berlaku MoU (biasanya 3-5 tahun)',
            'file_informasi' => 'https://drive.google.com/drive/folders/1P5NJV8CwYmMiGFawvehtpbGQHrTeBBNG?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Jumlah kunjungan pasien klinik pratama PKTJ tahun 2025',
            'kategori' => 'informasi-serta-merta',
            'isi_informasi' => 'Kunjungan Pasien tahun 2025 meliputi taruna, pegawai, dan masyarakat umum',
            'pejabat_penguasa' => 'Kanit Kesehatan',
            'penanggung_jawab' => 'Nakes Unit Kesehatan',
            'penerbit_informasi' => 'Nakes Unit Kesehatan',
            'bentuk_informasi' => 'Softfile',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'PKTJ Tegal di tiap akhir bulan',
            'jangka_waktu' => '5 tahun',
            'file_informasi' => 'https://drive.google.com/drive/folders/1zmYPO6XuAm6rp9HMuUO1UAy6fSROproS?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Laporan kebersihan asrama',
            'kategori' => 'informasi-serta-merta',
            'isi_informasi' => 'pengecekan kebersihan asrama',
            'pejabat_penguasa' => 'kanit asrama',
            'penanggung_jawab' => 'unit asrama',
            'penerbit_informasi' => 'unit asrama',
            'bentuk_informasi' => 'softfile',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'PKTJ Tegal di tiap akhir bulan',
            'jangka_waktu' => '2 tahun',
            'file_informasi' => 'https://drive.google.com/drive/folders/1qU81c6u8w7zy6oCCF2mLxN_FxIouESxW?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Pemeriksaan Kesehatan Gratis Pengemudi Ojek Online Dalam Rangka Hari Perhubungan Nasional Tahun 2025',
            'kategori' => 'informasi-serta-merta',
            'isi_informasi' => 'Kegiatan pemeriksaan kesehatan gratis meliputi pemeriksaan tekanan darah, gula darah sewaktu, kolesterol, dan asam urat bagi pengemudi Ojek online',
            'pejabat_penguasa' => 'Kanit Kesehatan',
            'penanggung_jawab' => 'Nakes Unit Kesehatan',
            'penerbit_informasi' => 'Nakes Unit Kesehatan',
            'bentuk_informasi' => 'Softfile',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'PKTJ Tegal',
            'jangka_waktu' => '5 tahun',
            'file_informasi' => 'https://drive.google.com/file/d/1a3nUuc1aFcz38juWmUw-FTrpL3QkErkE/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Pemeriksaan Kesehatan Gratis Pengemudi Ojek Online Dalam Rangka HUT RI ke 80',
            'kategori' => 'informasi-serta-merta',
            'isi_informasi' => 'Kegiatan pemeriksaan kesehatan gratis meliputi pemeriksaan tekanan darah, gula darah sewaktu, kolesterol, dan asam urat bagi pengemudi Ojek online',
            'pejabat_penguasa' => 'Kanit Kesehatan',
            'penanggung_jawab' => 'Nakes Unit Kesehatan',
            'penerbit_informasi' => 'Nakes Unit Kesehatan',
            'bentuk_informasi' => 'Softfile',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'PKTJ Tegal',
            'jangka_waktu' => '5 tahun',
            'file_informasi' => 'https://drive.google.com/file/d/14qD_iSgw9QYvEDjeexFzMOqjQBE4O9R7/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Penghapusan BMN Tahun 2025',
            'kategori' => 'informasi-serta-merta',
            'isi_informasi' => 'Kegiatan penghapusan Barang Milik Negarai di lingkungan Politeknik Keselamatan Transportasi Jalan Tahun 2025',
            'pejabat_penguasa' => 'Ketua Tim Bidang Umum',
            'penanggung_jawab' => 'Bagiaun Keuangan Umum dan Kerjasama',
            'penerbit_informasi' => 'Bagiaun Keuangan Umum dan Kerjasama',
            'bentuk_informasi' => 'Soft file',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal bulan Juli 2025',
            'jangka_waktu' => '7 tahun',
            'file_informasi' => 'https://drive.google.com/drive/folders/19cbR6rqgd7geDJsO4q9hxtan9D8Lpz1b?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Penyuluhan Kesehatan Umum dan Gigi Mulut kepada taruna',
            'kategori' => 'informasi-serta-merta',
            'isi_informasi' => 'Kegiatan penyuluhan kesehatan kepada taruna/ni PKTJ baik kesehatan umum maupun kesehatan gigi dan mulut secara offline',
            'pejabat_penguasa' => 'Kanit Kesehatan',
            'penanggung_jawab' => 'Dokter Umum / Dokter Gigi / Nakes Unit Kesehatan',
            'penerbit_informasi' => 'Dokter Umum / Dokter Gigi / Nakes Unit Kesehatan',
            'bentuk_informasi' => 'Softfile',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'PKTJ Tegal',
            'jangka_waktu' => '5 Tahun',
            'file_informasi' => 'https://drive.google.com/drive/folders/1Twh5M06qeoYqGSJQ2wdZ6Uvl4rpyDTtn?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Profil Progam Studi RSTJ',
            'kategori' => 'informasi-serta-merta',
            'isi_informasi' => 'Memuat Visi Misi, Lulusan, Dosen, Prestasi Taruna/i Prodi RSTJ dan kegiatan Pembelajaran Prodi RSTJ',
            'pejabat_penguasa' => 'Kepala Progam Studi Rekayasa Sistem Transportasi Jalan (RSTJ)',
            'penanggung_jawab' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
            'penerbit_informasi' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
            'bentuk_informasi' => 'Softcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => 'Selama masih berlaku / Diperbarui jika ada perubahan',
            'file_informasi' => 'https://drive.google.com/drive/folders/1_uPmo1JucI1DNNpRdtWci5n0Oxyunouq?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Sosialisasi P4GN (Pencegahan, Pemberantasan, Penyalahgunaan dan Peredaran Gelap Narkotika) kepada Taruna PKTJ',
            'kategori' => 'informasi-serta-merta',
            'isi_informasi' => 'Kegiatan Sosialisasi P4GN dilakukan secara online',
            'pejabat_penguasa' => 'Kanit Kesehatan',
            'penanggung_jawab' => 'Dokter Unit Kesehatan PKTJ',
            'penerbit_informasi' => 'Dokter Unit Kesehatan PKTJ',
            'bentuk_informasi' => 'Softfile',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'PKTJ Tegal',
            'jangka_waktu' => '5 tahun',
            'file_informasi' => 'https://drive.google.com/file/d/1-Nv0oNJwzwEHTP6pUEWR9cQbTLzc-7wy/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'SPI CHARTER (Piagam SPI)',
            'kategori' => 'informasi-serta-merta',
            'isi_informasi' => 'Piagam Satuan Pengawas Internal (Audit Charter SPI) adalah dokumen formal yang berisi tentang komitmen pimpinan berupa pengakuan keberadaan dan berfungsinya Satuan Pengawas Internal di sebuah organisasi. Piagam Satuan Pengawas Internal PKTJ mencakup visi, misi, kedudukan, tugas, fungsi, dan ruang lingkup serta persetujuan dan pengesahan dari Pimpinan Organisasi.',
            'pejabat_penguasa' => 'Kepala SPI',
            'penanggung_jawab' => 'SPI Politeknik Keselamatan Transportasi Jalan',
            'penerbit_informasi' => 'SPI Politeknik Keselamatan Transportasi Jalan',
            'bentuk_informasi' => 'Softcopy dan Hardcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '1 (satu) tahun',
            'file_informasi' => 'https://drive.google.com/file/d/1H14Y7vILtPAGoSluY3Zv9zlYk69gDPZl/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Profil Unit Perpustakaan PKTJ',
            'kategori' => 'informasi-serta-merta',
            'isi_informasi' => 'Memuat sejarah, visi misi, struktur organisasi, jam layanan, dan fasilitas perpustakaan.',
            'pejabat_penguasa' => 'Kepala Unit Perpustakaan',
            'penanggung_jawab' => 'Unit Perpustakaan PKTJ',
            'penerbit_informasi' => 'Unit Perpustakaan PKTJ',
            'bentuk_informasi' => 'Hardcopy & Sofcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2023',
            'jangka_waktu' => 'Selama berlaku / Diperbarui jika ada perubahan',
            'file_informasi' => 'https://drive.google.com/file/d/1dTJ_sBSr8JU1tnKSkavIZ1r2nUOUrMrx/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2023-01-01 00:00:00',
            'updated_at' => '2023-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Akreditasi Prodi',
            'kategori' => 'informasi-berkala',
            'isi_informasi' => 'Dokumen Laporan Evaluasi Diri Program Studi (LED), dan Laporan Kinerja Program Studi (LKPS) Prodi RSTJ, TRO, TO yang di Upload pada sistem SAKTI Lam Teknik untuk Akreditasi Prodi',
            'pejabat_penguasa' => 'Ka SPM',
            'penanggung_jawab' => 'Tim SPM dan masing-masing Prodi',
            'penerbit_informasi' => 'Tim SPM dan masing-masing Prodi',
            'bentuk_informasi' => 'Soft Copy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '5 tahun',
            'file_informasi' => 'https://drive.google.com/file/d/1cn3kpfAolP2XXpMwIeFjIbyLyJzMsDGT/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Audit Mutu Internal',
            'kategori' => 'informasi-berkala',
            'isi_informasi' => 'Audit Mutu Internal Tahun 2025 yang dilakukan oleh Auditor internal kepada masing-masing bagian atau Auditee',
            'pejabat_penguasa' => 'Ka SPM',
            'penanggung_jawab' => 'Tim SPM dan Auditor',
            'penerbit_informasi' => 'Tim SPM dan Auditor',
            'bentuk_informasi' => 'Soft Copy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '2 tahun',
            'file_informasi' => 'https://drive.google.com/file/d/1SgWVM5rXisRA03X2mP1V4XE-n_vx7n1A/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Jadwal Kegiatan Softskill Taruna Tahun 2025',
            'kategori' => 'informasi-berkala',
            'isi_informasi' => 'Jadwal kegiatan softskill taruna tentang literasi kesehatan menta; tahun 2025',
            'pejabat_penguasa' => 'Pengasuh Praja',
            'penanggung_jawab' => 'Pusat Pembangunan Karakter',
            'penerbit_informasi' => 'Pusat Pembangunan Karakter',
            'bentuk_informasi' => 'Softfile',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '5 Tahun',
            'file_informasi' => 'https://drive.google.com/file/d/1UKgitogU1fpLfSizig91wbB_XVHSEgxz/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Jadwal Perkuliahan',
            'kategori' => 'informasi-berkala',
            'isi_informasi' => 'Membahas ploting dosen terlebih dahulu untuk penyusunan Jadwal Perkuliahan/ semester',
            'pejabat_penguasa' => 'Kepala Progam Studi Diploma III Teknologi Otomotif (TO)',
            'penanggung_jawab' => 'Prodi Diploma III TO Politeknik Keselamatan Transportasi Jalan',
            'penerbit_informasi' => 'Prodi Diploma III TO Politeknik Keselamatan Transportasi Jalan',
            'bentuk_informasi' => 'Softcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '6 Bulan',
            'file_informasi' => 'https://drive.google.com/file/d/1P4_gCmIeBuj2-NKea-66BFfCutwCc7UX/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Laporan Kegiatan Pengawasan Mutu dan Manajemen Sistem Penyelenggaraan Makanan',
            'kategori' => 'informasi-berkala',
            'isi_informasi' => 'Laporan kegiatan pengawasan mutu dan manajemen sistem penyelenggawaan makanan, yang berisi evaluasi penyelenggaraan permakanan taruna selama tahun 2025',
            'pejabat_penguasa' => 'Nutrisionis Terampil',
            'penanggung_jawab' => 'Pusat Pembangunan Karakter',
            'penerbit_informasi' => 'Pusat Pembangunan Karakter',
            'bentuk_informasi' => 'Softfile',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '5 Tahun',
            'file_informasi' => 'https://drive.google.com/file/d/12hNO6rPTU_0uWUe7jht2aYNH0vGK2M62/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Laporan Kegiatan Pengukuran Indeks Massa Tubuh (IMT) Taruna Tahun 2025',
            'kategori' => 'informasi-berkala',
            'isi_informasi' => 'Laporan kegiatan pengukuran Indeks Massa Tubuh (IMT) yang berisi hasil pengukuran Indeks Massa Tubuh (IMT) Taruna pada Semester 1 dan Semester 2 Tahun 2025',
            'pejabat_penguasa' => 'Nutrisionis Terampil',
            'penanggung_jawab' => 'Pusat Pembangunan Karakter',
            'penerbit_informasi' => 'Pusat Pembangunan Karakter',
            'bentuk_informasi' => 'Softfile',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '5 Tahun',
            'file_informasi' => 'https://drive.google.com/file/d/1Yfm4P60ku-VES3DguWMX-hUmwKPYIP2e/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Laporan Kegiatan Softkill Taruna Tahun 2025',
            'kategori' => 'informasi-berkala',
            'isi_informasi' => 'Laporan kegiatan softkill taruna tentang literasi kesehatan mental tahun 2025',
            'pejabat_penguasa' => 'Pengasuh Praja',
            'penanggung_jawab' => 'Pusat Pembangunan Karakter',
            'penerbit_informasi' => 'Pusat Pembangunan Karakter',
            'bentuk_informasi' => 'Softfile',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '5 Tahun',
            'file_informasi' => 'https://drive.google.com/file/d/1IfqfbuDqsbUskq1H_tFHUwRJcxuoynga/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Laporan Penilian Samapta Periodik Taruna Tahun 2025',
            'kategori' => 'informasi-berkala',
            'isi_informasi' => 'Laporan penilaian samapta periodik berisi hasil penilaian samapta atau kebugaran jasmani taruna yang dilakukan pada semester ganjil dan semester genap tahun 2025',
            'pejabat_penguasa' => 'Pengasuh Praja',
            'penanggung_jawab' => 'Pusat Pembangunan Karakter',
            'penerbit_informasi' => 'Pusat Pembangunan Karakter',
            'bentuk_informasi' => 'Softfile',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '5 Tahun',
            'file_informasi' => 'https://drive.google.com/file/d/1OfKfPGUfovfe34wYQ0IvmB-Gn0JJEynA/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Laporan Perkuliahan Semester Genap',
            'kategori' => 'informasi-berkala',
            'isi_informasi' => 'Laporan Perkuliahan Semester Genap',
            'pejabat_penguasa' => 'Kepala Program Studi RSTJ',
            'penanggung_jawab' => 'Program Studi RSTJ',
            'penerbit_informasi' => 'Program Studi RSTJ',
            'bentuk_informasi' => 'Softcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => 'selama masih berlaku',
            'file_informasi' => 'https://docs.google.com/document/d/1zi2nbLa-2L8tMP9WRwI2uzwUzuUu5A16/edit?usp=drive_link&ouid=104167484510276306286&rtpof=true&sd=true',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Laporan Tracer Study 2025',
            'kategori' => 'informasi-berkala',
            'isi_informasi' => 'Laporan ini merupakan hasil dari kegiatan tracer study yang dilaksanakan terhadap lulusan tahun 2024 dan 2023 dari tiga program studi, yaitu Sarjana Terapan Rekayasa Sistem Transportasi Jalan (RSTJ), Sarjana Terapan Teknologi Rekayasa Otomotif (TRO), dan Diploma III Teknologi Otomotif (TO).',
            'pejabat_penguasa' => 'Katim Substansi Bidang Administrasi Ketarunaan dan Alumni',
            'penanggung_jawab' => 'Tim Administrasi Ketarunaan dan Alumni',
            'penerbit_informasi' => 'Tim Administrasi Ketarunaan dan Alumni',
            'bentuk_informasi' => 'softcopy dan hardcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '5 (lima) tahun',
            'file_informasi' => 'https://drive.google.com/file/d/1_R9FtirHJn8EYshWXI8JpgmJ9ad1SkWO/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Pelaksanaan Ujikom Andalalin',
            'kategori' => 'informasi-berkala',
            'isi_informasi' => 'Diawali dengan kegiatan Pra Ujikom Penilai Andalalin pd tgl 14 s.d 15 Agustus 2025dan di lanjutkan dengan Ujikom Penilai Andalalin pd tgl 19 s.d 21 Agustus 2025',
            'pejabat_penguasa' => 'Kepala Progam Studi Rekayasa Sistem Transportasi Jalan (RSTJ)',
            'penanggung_jawab' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
            'penerbit_informasi' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
            'bentuk_informasi' => 'Softcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '12 bulan',
            'file_informasi' => 'https://drive.google.com/file/d/1Ilhf0YdRhQ7dxrekCkvdzJ4CJCtaGPYP/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Pelaksanaan Ujikom Pembantu PKB',
            'kategori' => 'informasi-berkala',
            'isi_informasi' => 'Diawali dengan kegiatan Pra Ujikom Pembantu PKB pd tgl 13 s.d 15 dan di lanjutkan dengan Ujikom Pembantu PKB pd tgl 19 s.d 21 Agustus 2025 yang diikuti oleh 31 Mahasiswa/i Mandiri',
            'pejabat_penguasa' => 'Kepala Progam Studi Teknologi Rekayasa Otomotif (TRO)',
            'penanggung_jawab' => 'Prodi TRO Politeknik Keselamatan Transportasi Jalan',
            'penerbit_informasi' => 'Prodi TRO Politeknik Keselamatan Transportasi Jalan',
            'bentuk_informasi' => 'Softcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '1 Tahun',
            'file_informasi' => 'https://drive.google.com/file/d/1T0e51-oIN1zi70Tp96Et7tu2WheeAXa7/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Pelaksanaan Ujikom Pemeliharaan Jalan',
            'kategori' => 'informasi-berkala',
            'isi_informasi' => 'Diawali dengan kegiatan Pelatihan Pemeliharaan Jalan pd tgl 15 Agustus 2025 dan di lanjutkan dengan Ujikom/Assesment Pemeliharaan Jalan pd tgl 28 Agustus 2025',
            'pejabat_penguasa' => 'Kepala Progam Studi Rekayasa Sistem Transportasi Jalan (RSTJ)',
            'penanggung_jawab' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
            'penerbit_informasi' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
            'bentuk_informasi' => 'Softcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '12 bulan',
            'file_informasi' => 'https://drive.google.com/file/d/1qnwCoURKV1qnMPuCGXVUwpFn9MlP0Jx8/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Pelaksanaan Ujikom Penguji Berkala Kendaraan Bermotor Tingkat 3',
            'kategori' => 'informasi-berkala',
            'isi_informasi' => 'Diawali dengan kegiatan Pra Ujikom Penguji Berkala Kendaraan Bermotor Tingkat 3 pd tgl 25 s.d 28 dan di lanjutkan dengan Ujikom Penguji Berkala Kendaraan Bermotor Tingkat 3 pd tgl 11 s.d 18 Agustus 2025 yang diikuti oleh 106 Mahasiswa/i D3 TO POLBIT dan NoN POLBIT',
            'pejabat_penguasa' => 'Kepala Progam Studi Diploma III Teknologi Otomotif (TO)',
            'penanggung_jawab' => 'Prodi Diploma III TO Politeknik Keselamatan Transportasi Jalan',
            'penerbit_informasi' => 'Prodi Diploma III TO Politeknik Keselamatan Transportasi Jalan',
            'bentuk_informasi' => 'Softcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '1 Tahun',
            'file_informasi' => 'https://drive.google.com/drive/folders/10bFBQqAABU4xr-UZ4-nD9n_AjTKuVl9U?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Pelaksanaan Ujikom Sistem Manajemen Keselamatan',
            'kategori' => 'informasi-berkala',
            'isi_informasi' => 'Diawali dengan kegiatan Pra Ujikom SMK pd tgl 13 s.d 14 dan di lanjutkan dengan Ujikom SMK pd tgl 18 s.d 19 Agustus 2025 yang diikuti oleh 57 Mahasiswa/i Pola Pembibitan (Polbit)',
            'pejabat_penguasa' => 'Kepala Progam Studi Teknologi Rekayasa Otomotif (TRO)',
            'penanggung_jawab' => 'Prodi TRO Politeknik Keselamatan Transportasi Jalan',
            'penerbit_informasi' => 'Prodi TRO Politeknik Keselamatan Transportasi Jalan',
            'bentuk_informasi' => 'Softcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '1 Tahun',
            'file_informasi' => 'https://drive.google.com/file/d/1YsTHPUBSn-LhG4dhs1xFjmHrEF9UwT2s/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Pelaksanaan UTS dan UAS',
            'kategori' => 'informasi-berkala',
            'isi_informasi' => 'Pelaksanaan mengikuti Kalender Akademik di dukung dengan 7x pertemuan pembelajaran, minimal 6x pertemuan untuk pelaksanaan kegiata UTS dan UAS 14x pertemuan',
            'pejabat_penguasa' => 'Kepala Progam Studi Rekayasa Sistem Transportasi Jalan (RSTJ)',
            'penanggung_jawab' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
            'penerbit_informasi' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
            'bentuk_informasi' => 'Softcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '6 bulan',
            'file_informasi' => 'https://drive.google.com/file/d/15vXKG0Fm8zNr7i-tuC9gHhygv_0rgdIE/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Pelaksanaan UTS dan UAS',
            'kategori' => 'informasi-berkala',
            'isi_informasi' => 'Pelaksanaan mengikuti Kalender Akademik di dukung dengan 7x pertemuan pembelajaran, minimal 6x pertemuan untuk pelaksanaan kegiata UTS dan UAS 14x pertemuan',
            'pejabat_penguasa' => 'Kepala Progam Studi Teknologi Rekayasa Otomotif (TRO)',
            'penanggung_jawab' => 'Prodi TRO Politeknik Keselamatan Transportasi Jalan',
            'penerbit_informasi' => 'Prodi TRO Politeknik Keselamatan Transportasi Jalan',
            'bentuk_informasi' => 'Softcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '6 Bulan',
            'file_informasi' => 'https://drive.google.com/file/d/1cFjBfLtGgOkYsjud8uMLu9qXd5jWbix8/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Pelaksanaan UTS dan UAS',
            'kategori' => 'informasi-berkala',
            'isi_informasi' => 'Pelaksanaan mengikuti Kalender Akademik di dukung dengan 7x pertemuan pembelajaran, minimal 6x pertemuan untuk pelaksanaan kegiata UTS dan UAS 14x pertemuan',
            'pejabat_penguasa' => 'Kepala Progam Studi Diploma III Teknologi Otomotif (TO)',
            'penanggung_jawab' => 'Prodi Diploma III TO Politeknik Keselamatan Transportasi Jalan',
            'penerbit_informasi' => 'Prodi Diploma III TO Politeknik Keselamatan Transportasi Jalan',
            'bentuk_informasi' => 'Softcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '6 Bulan',
            'file_informasi' => 'https://drive.google.com/file/d/1gAl4oo672SWlv05qOeAupBflSJ8DY-F7/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Ploting dan jadwal Perkuliahan Semester Genap',
            'kategori' => 'informasi-berkala',
            'isi_informasi' => 'Membahas ploting dosen terlebih dahulu untuk penyusunan Jadwal Perkuliahan/ semester',
            'pejabat_penguasa' => 'Kepala Progam Studi Rekayasa Sistem Transportasi Jalan (RSTJ)',
            'penanggung_jawab' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
            'penerbit_informasi' => 'Prodi RSTJ Politeknik Keselamatan Transportasi Jalan',
            'bentuk_informasi' => 'Softcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '6 bulann',
            'file_informasi' => 'https://drive.google.com/drive/folders/17IaQFiEyMC3mgEI6Xd99myZV0WA3LAhG?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Rapat Tinjauan Manajemen',
            'kategori' => 'informasi-berkala',
            'isi_informasi' => 'Risalah rapat tinjauan manajemen tahun 2025',
            'pejabat_penguasa' => 'Ka SPM',
            'penanggung_jawab' => 'Tim SPM',
            'penerbit_informasi' => 'Tim SPM',
            'bentuk_informasi' => 'Soft Copy dan Hard Copy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '1 tahun',
            'file_informasi' => 'https://drive.google.com/drive/folders/1YJqNIXAXI-LVZd9ejMdKPLoeePJQJ_TH?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Screening gigi kepada taruna/i PKTJ',
            'kategori' => 'informasi-berkala',
            'isi_informasi' => 'Kegiatan rutin screening TBC yang merupakan program dari Dinas Kesehatan Kota Tegal',
            'pejabat_penguasa' => 'Kanit Kesehatan',
            'penanggung_jawab' => 'Nakes Unit Kesehatan',
            'penerbit_informasi' => 'Nakes Unit Kesehatan',
            'bentuk_informasi' => 'Softfile',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'PKTJ tegal',
            'jangka_waktu' => '5 tahun',
            'file_informasi' => 'https://drive.google.com/file/d/1wt1p7rf2tFoYkEHk3nJxTrc86Oxcea5p/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Surveillance ISO 21001 : 2018',
            'kategori' => 'informasi-berkala',
            'isi_informasi' => 'Audit Surveillance dari SGS Indonesia, Penerapan ISO 21001 : 2018. Standar ini menekankan pentingnya kepuasan peserta didik, proses pembelajaran yang efektif, pemenuhan kebutuhan seluruh pemangku kepentingan pendidikan, serta perbaikan berkelanjutan dalam layanan pendidikan',
            'pejabat_penguasa' => 'Ka SPM',
            'penanggung_jawab' => 'Tim SPM',
            'penerbit_informasi' => 'Tim SPM',
            'bentuk_informasi' => 'Soft Copy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '2 tahun',
            'file_informasi' => 'https://drive.google.com/file/d/1ipXcaEhEjIAUnyCitdhBxGV2cc2rputU/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Survey Kepuasan Masyarakat Semester I',
            'kategori' => 'informasi-berkala',
            'isi_informasi' => 'Laporan berisi nilai Indeks kepuasan masyarakat dan nilai indeks presepsi korupsi',
            'pejabat_penguasa' => 'Ka SPM',
            'penanggung_jawab' => 'Tim SPM',
            'penerbit_informasi' => 'Tim SPM',
            'bentuk_informasi' => 'Soft Copy dan Hard Copy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '1 tahun',
            'file_informasi' => 'https://drive.google.com/drive/folders/1ZDALUWnp5ReH7QRUZt4bXYXjHlGOk6yq?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Daftar Aplikasi Internal PKTJ dan Monitoring Aksesibilitas',
            'kategori' => 'informasi-dikecualikan',
            'isi_informasi' => 'Daftar lengkap aplikasi/sistem informasi yang digunakan secara internal di lingkungan PKTJ meliputi: Website PKTJ, SIAKAD, SIMATA, Seleksi Penerimaan Calon Taruna, E-Library, Repository, Katalog Online Buku, Aplikasi Jurnal, Aplikasi Rekap SPPD, Aplikasi Dokumen Keuangan, Aplikasi Ujian Berbasis Computer, Tracer Study, dan LIMS. Termasuk laporan monitoring kondisi dan aksesibilitas aplikasi.',
            'pejabat_penguasa' => 'Unit IT',
            'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
            'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
            'bentuk_informasi' => 'softcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => 'sesuai retensi arsip',
            'file_informasi' => 'https://drive.google.com/drive/folders/1B9Flre61jbNthvm49762_EWLhCvmoDcV?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'Data Taruna Aktif Tahun Akademik 2025/2026 - Ganjil',
            'kategori' => 'informasi-dikecualikan',
            'isi_informasi' => 'Tahun Akademik 2025/2026 Semester Ganjil, tercatat data taruna aktif yang dikelompokkan berdasarkan Angkatan, Tahun Masuk, Tahun Lulus, Program Studi, Kelas, Jalur Penerimaan, serta Jenis Kelamin',
            'pejabat_penguasa' => 'Katim Substansi Bidang Administrasi Ketarunaan dan Alumni',
            'penanggung_jawab' => 'Tim Administrasi Ketarunaan dan Alumni',
            'penerbit_informasi' => 'Tim Administrasi Ketarunaan dan Alumni',
            'bentuk_informasi' => 'softcopy dan hardcopy',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'Tegal, 2025',
            'jangka_waktu' => '5 (lima) tahun',
            'file_informasi' => 'https://drive.google.com/file/d/1TeVlYnV6i2J_q4apCCnzNyEogQ7YnSzI/view?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul_informasi' => 'MCU Siswa Diklat SPAU tahun 2025',
            'kategori' => 'informasi-dikecualikan',
            'isi_informasi' => 'Kegiatan Medical Check Up bagi Siswa Diklat SPAU',
            'pejabat_penguasa' => 'Kanit Kesehatan',
            'penanggung_jawab' => 'Nakes Unit Kesehatan',
            'penerbit_informasi' => 'Nakes Unit Kesehatan',
            'bentuk_informasi' => 'Softfile',
            'tempat_pembuatan' => 'Tegal',
            'waktu_pembuatan' => 'PKTJ Tegal',
            'jangka_waktu' => '5 tahun',
            'file_informasi' => 'https://drive.google.com/drive/folders/1z6r33ziN9C4eCAJs1A9JTA1syzHRgE9A?usp=drive_link',
            'aktif' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        ];

        foreach (array_chunk($data, 50) as $chunk) {
            DB::table('daftar_informasis')->insert($chunk);
        }

        // 2. Seed informasi_dikecualikans
        DB::table('informasi_dikecualikans')->truncate();

        $data_dik = [
        [
            'judul' => 'Daftar Aplikasi Internal PKTJ dan Monitoring Aksesibilitas',
            'deskripsi' => 'Daftar lengkap aplikasi/sistem informasi yang digunakan secara internal di lingkungan PKTJ meliputi: Website PKTJ, SIAKAD, SIMATA, Seleksi Penerimaan Calon Taruna, E-Library, Repository, Katalog Online Buku, Aplikasi Jurnal, Aplikasi Rekap SPPD, Aplikasi Dokumen Keuangan, Aplikasi Ujian Berbasis Computer, Tracer Study, dan LIMS. Termasuk laporan monitoring kondisi dan aksesibilitas aplikasi.',
            'tanggal' => '2025-01-01',
            'jangka_waktu' => 'sesuai retensi arsip',
            'penanggung_jawab' => 'Unit Kerja di lingkungan PKTJ',
            'file_path' => 'https://drive.google.com/drive/folders/1B9Flre61jbNthvm49762_EWLhCvmoDcV?usp=drive_link',
            'file_name' => 'Dokumen',
            'file_size' => '-',
            'file_type' => 'Google Drive / PDF',
            'aktif' => 1,
            'is_blurred' => 0,
            'bisa_download' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul' => 'Data Taruna Aktif Tahun Akademik 2025/2026 - Ganjil',
            'deskripsi' => 'Tahun Akademik 2025/2026 Semester Ganjil, tercatat data taruna aktif yang dikelompokkan berdasarkan Angkatan, Tahun Masuk, Tahun Lulus, Program Studi, Kelas, Jalur Penerimaan, serta Jenis Kelamin',
            'tanggal' => '2025-01-01',
            'jangka_waktu' => '5 (lima) tahun',
            'penanggung_jawab' => 'Tim Administrasi Ketarunaan dan Alumni',
            'file_path' => 'https://drive.google.com/file/d/1TeVlYnV6i2J_q4apCCnzNyEogQ7YnSzI/view?usp=drive_link',
            'file_name' => 'Dokumen',
            'file_size' => '-',
            'file_type' => 'Google Drive / PDF',
            'aktif' => 1,
            'is_blurred' => 0,
            'bisa_download' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        [
            'judul' => 'MCU Siswa Diklat SPAU tahun 2025',
            'deskripsi' => 'Kegiatan Medical Check Up bagi Siswa Diklat SPAU',
            'tanggal' => '2025-01-01',
            'jangka_waktu' => '5 tahun',
            'penanggung_jawab' => 'Nakes Unit Kesehatan',
            'file_path' => 'https://drive.google.com/drive/folders/1z6r33ziN9C4eCAJs1A9JTA1syzHRgE9A?usp=drive_link',
            'file_name' => 'Dokumen',
            'file_size' => '-',
            'file_type' => 'Google Drive / PDF',
            'aktif' => 1,
            'is_blurred' => 0,
            'bisa_download' => 1,
            'created_at' => '2025-01-01 00:00:00',
            'updated_at' => '2025-01-01 00:00:00',
        ],
        ];

        foreach (array_chunk($data_dik, 50) as $chunk) {
            DB::table('informasi_dikecualikans')->insert($chunk);
        }
    }
}
