<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\DaftarInformasi;
use App\Models\InformasiBerkala;
use App\Models\InformasiSetiapSaat;
use App\Models\InformasiSertaMerta;

class PoltradaBaliDipSeeder extends Seeder
{
    public function run()
    {
        // 1. Nonaktifkan semua data lama terlebih dahulu
        DB::table('daftar_informasis')->update(['aktif' => 0]);
        if (DB::getSchemaBuilder()->hasTable('informasi_berkalas')) {
            DB::table('informasi_berkalas')->update(['aktif' => 0]);
        }
        if (DB::getSchemaBuilder()->hasTable('informasi_setiapsaats')) {
            DB::table('informasi_setiapsaats')->update(['aktif' => 0]);
        }
        if (DB::getSchemaBuilder()->hasTable('informasi_sertamertas')) {
            DB::table('informasi_sertamertas')->update(['aktif' => 0]);
        }

        // =========================================================================
        // 2. DATA INFORMASI BERKALA (26 ITEM - 5 KATEGORI RESMI POLTRADA BALI)
        // =========================================================================
        $berkalaItems = [
            // PROFIL
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'PROFIL',
                'judul_informasi' => 'Profil PKTJ Tegal',
                'isi_informasi' => 'Informasi mengenai kedudukan, alamat lengkap, kontak, gambaran umum, tugas dan fungsi, serta visi-misi PKTJ Tegal',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/profil-ppid',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'PROFIL',
                'judul_informasi' => 'Struktur Organisasi di lingkungan PKTJ Tegal',
                'isi_informasi' => 'Struktur pejabat struktural dan fungsional',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/profil/struktur-organisasi',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'PROFIL',
                'judul_informasi' => 'Profil Singkat Pejabat PKTJ Tegal',
                'isi_informasi' => 'Data diri pejabat struktural dan fungsional',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/profil/pejabat',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'PROFIL',
                'judul_informasi' => 'Laporan Harta Kekayaan Pejabat Negara (LHKPN)',
                'isi_informasi' => 'Laporan LHKPN yang telah diverifikasi dan diumumkan oleh KPK',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/profil/pejabat',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'PROFIL',
                'judul_informasi' => 'Agenda Pimpinan PKTJ Tegal',
                'isi_informasi' => 'Jadwal dan agenda kegiatan pimpinan kelembagaan PKTJ Tegal',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/profil-ppid',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'PROFIL',
                'judul_informasi' => 'Statistik Data Kepegawaian PKTJ Tegal',
                'isi_informasi' => 'Data statistik dan rekapitulasi jumlah dosen serta tenaga kependidikan PKTJ Tegal',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/informasi-publik/statistik-pegawai',
                'aktif' => 1,
            ],

            // PROGRAM DAN KEGIATAN
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'PROGRAM DAN KEGIATAN',
                'judul_informasi' => 'Rencana Strategis (Renstra) PKTJ Tegal 2020–2024',
                'isi_informasi' => 'Dokumen Rencana Strategis (Renstra) PKTJ Tegal periode 2020–2024',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2020',
                'jangka_waktu' => '5 Tahun',
                'file_informasi' => null,
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'PROGRAM DAN KEGIATAN',
                'judul_informasi' => 'Rencana Kerja Tahunan (RKT) PKTJ Tegal',
                'isi_informasi' => 'Dokumen program kerja tahunan dan sasaran operasional PKTJ Tegal',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => null,
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'PROGRAM DAN KEGIATAN',
                'judul_informasi' => 'Kalender Akademik & Jadwal Perkuliahan / Diklat PKTJ',
                'isi_informasi' => 'Informasi kalender akademik perkuliahan dan penyelenggaraan diklat transportasi jalan',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Administrasi Akademik dan Ketarunaan',
                'penerbit_informasi' => 'Bagian Administrasi Akademik dan Ketarunaan',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => null,
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'PROGRAM DAN KEGIATAN',
                'judul_informasi' => 'Informasi Penerimaan Calon Taruna (SIPENCATAR) PKTJ',
                'isi_informasi' => 'Pengumuman seleksi penerimaan calon taruna/i pola pembibitan dan mandiri',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Administrasi Akademik dan Ketarunaan',
                'penerbit_informasi' => 'Bagian Administrasi Akademik dan Ketarunaan',
                'bentuk_informasi' => 'softcopy (online)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => 'https://sipencatar.dephub.go.id/',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'PROGRAM DAN KEGIATAN',
                'judul_informasi' => 'Standar Biaya Pendidikan & Tarif Layanan PKTJ',
                'isi_informasi' => 'Informasi tarif layanan pendidikan, biaya kuliah, dan tarif PNBP PKTJ',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => '/layanan-informasi/maklumat-dan-standar-biaya-layanan',
                'aktif' => 1,
            ],

            // KINERJA DAN KEUANGAN
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'KINERJA DAN KEUANGAN',
                'judul_informasi' => 'Rencana Kerja dan Anggaran K/L (RKA-KL) PKTJ',
                'isi_informasi' => 'Alokasi anggaran belanja program dan kegiatan operasional PKTJ',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => null,
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'KINERJA DAN KEUANGAN',
                'judul_informasi' => 'Daftar Isian Pelaksanaan Anggaran (DIPA) Induk PKTJ',
                'isi_informasi' => 'Dokumen pelaksanaan anggaran satuan kerja PKTJ Tegal',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => null,
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'KINERJA DAN KEUANGAN',
                'judul_informasi' => 'Perjanjian Kinerja (PK) PKTJ Tegal',
                'isi_informasi' => 'Komitmen target kinerja pimpinan unit kerja PKTJ dengan BPSDMP',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => null,
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'KINERJA DAN KEUANGAN',
                'judul_informasi' => 'Laporan Akuntabilitas Kinerja Instansi Pemerintah (LAKIP / LKjIP) PKTJ',
                'isi_informasi' => 'Laporan pertanggungjawaban capaian kinerja tahunan kelembagaan PKTJ',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => null,
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'KINERJA DAN KEUANGAN',
                'judul_informasi' => 'Laporan Tahunan PKTJ Tegal',
                'isi_informasi' => 'Kompilasi laporan tahunan penyelenggaraan tri dharma perguruan tinggi vokasi',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => null,
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'KINERJA DAN KEUANGAN',
                'judul_informasi' => 'Laporan Keuangan Audited BPK-RI PKTJ',
                'isi_informasi' => 'Laporan keuangan satuan kerja PKTJ Tegal audited',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => null,
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'KINERJA DAN KEUANGAN',
                'judul_informasi' => 'Laporan Pelayanan Informasi Publik PPID PKTJ',
                'isi_informasi' => 'Laporan tahunan pelaksanaan layanan keterbukaan informasi publik PPID PKTJ',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penerbit_informasi' => 'PPID Pelaksana UPT PKTJ Tegal',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/layanan-informasi/laporan',
                'aktif' => 1,
            ],

            // PENGADAAN BARANG DAN JASA
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'PENGADAAN BARANG DAN JASA',
                'judul_informasi' => 'Rencana Umum Pengadaan (SiRUP) PKTJ Tegal',
                'isi_informasi' => 'Pengumuman Rencana Umum Pengadaan (RUP) barang/jasa PKTJ melalui SiRUP LKPP',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'PPK / Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'PPK / Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'softcopy (online)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => 'https://sirup.lkpp.go.id/',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'PENGADAAN BARANG DAN JASA',
                'judul_informasi' => 'Pengumuman Pengadaan Pemilihan Penyedia Barang dan Jasa (LPSE) PKTJ',
                'isi_informasi' => 'Daftar pengumuman tender dan seleksi pengadaan barang/jasa via LPSE Kemenhub',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Pokja Pemilihan / UKPBJ',
                'penerbit_informasi' => 'Pokja Pemilihan / UKPBJ',
                'bentuk_informasi' => 'softcopy (online)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => 'https://lpse.dephub.go.id/',
                'aktif' => 1,
            ],

            // TATA CARA / PROSEDUR
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'TATA CARA / PROSEDUR',
                'judul_informasi' => 'Tata cara permohonan informasi publik',
                'isi_informasi' => 'Mekanisme permohonan informasi',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/prosedur/permintaan-informasi',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'TATA CARA / PROSEDUR',
                'judul_informasi' => 'Tata cara mengajukan keberatan informasi publik',
                'isi_informasi' => 'Mekanisme keberatan informasi publik',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/prosedur/penanganan-keberatan',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'TATA CARA / PROSEDUR',
                'judul_informasi' => 'Tata cara penyelesaian sengketa informasi publik',
                'isi_informasi' => 'Mekanisme penyelesaian sengketa informasi publik',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/prosedur/sengketa-informasi',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'TATA CARA / PROSEDUR',
                'judul_informasi' => 'Tata cara pengaduan masyarakat (Whistleblowing System & LAPOR!)',
                'isi_informasi' => 'Mekanisme penyampaian laporan pengaduan masyarakat via SP4N-LAPOR! dan WBS Kemenhub',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Satuan Pengawas Internal (SPI)',
                'penerbit_informasi' => 'Satuan Pengawas Internal (SPI)',
                'bentuk_informasi' => 'softcopy (online)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => 'https://www.lapor.go.id/',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'TATA CARA / PROSEDUR',
                'judul_informasi' => 'Standar Pelayanan PPID PKTJ',
                'isi_informasi' => 'Standar operasional prosedur pelayanan informasi publik dan jangka waktu respon',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => '/layanan-informasi/maklumat-dan-standar-biaya-layanan',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'TATA CARA / PROSEDUR',
                'judul_informasi' => 'Maklumat Pelayanan PPID PKTJ',
                'isi_informasi' => 'Pernyataan janji dan kesanggupan segenap pengelola PPID PKTJ dalam melayani publik',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penerbit_informasi' => 'PPID Pelaksana UPT PKTJ Tegal',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => '/layanan-informasi/maklumat-dan-standar-biaya-layanan',
                'aktif' => 1,
            ],
        ];

        // =========================================================================
        // 3. DATA INFORMASI SETIAP SAAT (10 ITEM - STANDAR POLTRADA BALI)
        // =========================================================================
        $setiapSaatItems = [
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiap-saat',
                'sub_kategori' => 'SETIAP SAAT',
                'judul_informasi' => 'Daftar Informasi Publik (DIP) PKTJ',
                'isi_informasi' => 'Dokumen penetapan Daftar Informasi Publik (DIP) yang wajib disediakan',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Seluruh Unit Kerja PKTJ',
                'penerbit_informasi' => 'Seluruh Unit Kerja PKTJ',
                'bentuk_informasi' => 'Cetak & Online',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Hingga Pemutakhiran',
                'file_informasi' => null,
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiap-saat',
                'sub_kategori' => 'SETIAP SAAT',
                'judul_informasi' => 'SOP Layanan Informasi Publik PPID',
                'isi_informasi' => 'Standar Operasional Prosedur penatausahaan pelayanan informasi publik dan uji konsekuensi',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penerbit_informasi' => 'PPID Pelaksana UPT PKTJ Tegal',
                'bentuk_informasi' => 'Cetak & Online',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => '/prosedur/permintaan-informasi',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiap-saat',
                'sub_kategori' => 'SETIAP SAAT',
                'judul_informasi' => 'Surat Menyurat & Registrasi Naskah Dinas',
                'isi_informasi' => 'Informasi buku register persuratan naskah dinas masuk dan keluar resmi',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Subbagian Tata Usaha & Rumah Tangga',
                'penerbit_informasi' => 'Subbagian Tata Usaha & Rumah Tangga',
                'bentuk_informasi' => 'Cetak & Online',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => null,
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiap-saat',
                'sub_kategori' => 'SETIAP SAAT',
                'judul_informasi' => 'Data Inventaris Barang Milik Negara (BMN) PKTJ',
                'isi_informasi' => 'Laporan penatausahaan dan inventarisasi Barang Milik Negara (BMN)',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => null,
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiap-saat',
                'sub_kategori' => 'SETIAP SAAT',
                'judul_informasi' => 'Pedoman Sistem Penjaminan Mutu Internal (SPMI) PKTJ',
                'isi_informasi' => 'Dokumen kebijakan mutu, manual mutu, dan standar audit internal PKTJ',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Pusat Pengembangan Pembelajaran & SPMI (P4MP)',
                'penerbit_informasi' => 'Pusat Pengembangan Pembelajaran & SPMI (P4MP)',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Sesuai Retensi Arsip',
                'file_informasi' => null,
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiap-saat',
                'sub_kategori' => 'SETIAP SAAT',
                'judul_informasi' => 'Dokumentasi & Kegiatan Pimpinan PKTJ',
                'isi_informasi' => 'Dokumentasi foto dan publikasi kegiatan kedinasan Direktur PKTJ',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Tim Humas & Publikasi PKTJ',
                'penerbit_informasi' => 'Tim Humas & Publikasi PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => '/profil-ppid',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiap-saat',
                'sub_kategori' => 'SETIAP SAAT',
                'judul_informasi' => 'Kurikulum & Silabus Program Studi PKTJ',
                'isi_informasi' => 'Keputusan Direktur mengenai kurikulum program studi D4 dan D3 di PKTJ',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Administrasi Akademik dan Ketarunaan',
                'penerbit_informasi' => 'Bagian Administrasi Akademik dan Ketarunaan',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => null,
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiap-saat',
                'sub_kategori' => 'SETIAP SAAT',
                'judul_informasi' => 'Himpunan Peraturan & Kebijakan Direktur PKTJ',
                'isi_informasi' => 'Kompilasi Peraturan Direktur, Tata Tertib, dan Pedoman Ketarunaan PKTJ',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Subbagian Kepegawaian & Tata Usaha',
                'penerbit_informasi' => 'Subbagian Kepegawaian & Tata Usaha',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => null,
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiap-saat',
                'sub_kategori' => 'SETIAP SAAT',
                'judul_informasi' => 'Data Inventaris Kendaraan Dinas & Sarana Transportasi PKTJ',
                'isi_informasi' => 'Daftar inventaris sarana kendaraan operasional dan bus kampus PKTJ',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Subbagian Rumah Tangga & Perlengkapan',
                'penerbit_informasi' => 'Subbagian Rumah Tangga & Perlengkapan',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => null,
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiap-saat',
                'sub_kategori' => 'SETIAP SAAT',
                'judul_informasi' => 'Data Fasilitas & Sarana Laboratorium PKTJ',
                'isi_informasi' => 'Informasi sarana laboratorium keselamatan jalan, bengkel uji, dan simulator',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Laboratorium & Bengkel Uji PKTJ',
                'penerbit_informasi' => 'Laboratorium & Bengkel Uji PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Sesuai Retensi Arsip',
                'file_informasi' => null,
                'aktif' => 1,
            ],
        ];

        // =========================================================================
        // 4. DATA INFORMASI SERTA MERTA (1 ITEM - STANDAR POLTRADA BALI)
        // =========================================================================
        $sertaMertaItems = [
            [
                'kategori' => 'informasi-serta-merta',
                'tipe_informasi' => 'serta-merta',
                'sub_kategori' => 'SERTA MERTA',
                'judul_informasi' => 'Penutupan Layanan Publik / Sarana Prasarana Akibat Keadaan Darurat',
                'isi_informasi' => 'Pemberitahuan darurat dan pengumuman resmi mengenai penutupan sementara fasilitas kampus akibat keadaan darurat atau bencana',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Seluruh Unit Kerja di Lingkungan PKTJ Tegal',
                'penerbit_informasi' => 'Seluruh Unit Kerja di Lingkungan PKTJ Tegal',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => null,
                'aktif' => 1,
            ],
        ];

        // =========================================================================
        // 5. EKSEKUSI PENYIMPANAN KE TABEL DAFTAR_INFORMASIS & MODEL MASING-MASING
        // =========================================================================
        $allItems = array_merge($berkalaItems, $setiapSaatItems, $sertaMertaItems);

        foreach ($allItems as $it) {
            $existing = DB::table('daftar_informasis')
                ->where('judul_informasi', $it['judul_informasi'])
                ->first();

            $dataToSave = [
                'kategori' => $it['kategori'],
                'tipe_informasi' => $it['sub_kategori'] ?? $it['tipe_informasi'],
                'judul_informasi' => $it['judul_informasi'],
                'isi_informasi' => $it['isi_informasi'],
                'pejabat_penguasa' => $it['pejabat_penguasa'],
                'penanggung_jawab' => $it['penanggung_jawab'],
                'penerbit_informasi' => $it['penerbit_informasi'],
                'bentuk_informasi' => $it['bentuk_informasi'],
                'tempat_pembuatan' => $it['tempat_pembuatan'],
                'waktu_pembuatan' => $it['waktu_pembuatan'],
                'jangka_waktu' => $it['jangka_waktu'],
                'file_informasi' => $it['file_informasi'],
                'aktif' => 1,
                'bisa_download' => 1,
                'is_blurred' => 0,
                'updated_at' => now(),
            ];

            if ($existing) {
                DB::table('daftar_informasis')->where('id', $existing->id)->update($dataToSave);
            } else {
                $dataToSave['created_at'] = now();
                DB::table('daftar_informasis')->insert($dataToSave);
            }

            // Simpan juga ke tabel model spesifik agar di admin panel langsung muncul dan bisa diedit
            if ($it['kategori'] === 'informasi-berkala' && DB::getSchemaBuilder()->hasTable('informasi_berkalas')) {
                $m = DB::table('informasi_berkalas')->where('judul', $it['judul_informasi'])->first();
                $mData = [
                    'judul' => $it['judul_informasi'],
                    'deskripsi' => $it['isi_informasi'],
                    'file_path' => $it['file_informasi'],
                    'aktif' => 1,
                    'is_blurred' => 0,
                    'bisa_download' => 1,
                    'tanggal' => date('Y-m-d'),
                    'updated_at' => now(),
                ];
                if ($m) {
                    DB::table('informasi_berkalas')->where('id', $m->id)->update($mData);
                } else {
                    $mData['created_at'] = now();
                    DB::table('informasi_berkalas')->insert($mData);
                }
            } elseif (in_array($it['kategori'], ['informasi-setiap-saat', 'informasi-setiapsaat']) && DB::getSchemaBuilder()->hasTable('informasi_setiapsaats')) {
                $m = DB::table('informasi_setiapsaats')->where('judul', $it['judul_informasi'])->first();
                $mData = [
                    'judul' => $it['judul_informasi'],
                    'deskripsi' => $it['isi_informasi'],
                    'file_path' => $it['file_informasi'],
                    'aktif' => 1,
                    'is_blurred' => 0,
                    'bisa_download' => 1,
                    'tanggal' => date('Y-m-d'),
                    'updated_at' => now(),
                ];
                if ($m) {
                    DB::table('informasi_setiapsaats')->where('id', $m->id)->update($mData);
                } else {
                    $mData['created_at'] = now();
                    DB::table('informasi_setiapsaats')->insert($mData);
                }
            } elseif (in_array($it['kategori'], ['informasi-serta-merta', 'informasi-sertamerta']) && DB::getSchemaBuilder()->hasTable('informasi_sertamertas')) {
                $m = DB::table('informasi_sertamertas')->where('judul', $it['judul_informasi'])->first();
                $mData = [
                    'judul' => $it['judul_informasi'],
                    'deskripsi' => $it['isi_informasi'],
                    'file_path' => $it['file_informasi'],
                    'aktif' => 1,
                    'is_blurred' => 0,
                    'bisa_download' => 1,
                    'tanggal' => date('Y-m-d'),
                    'updated_at' => now(),
                ];
                if ($m) {
                    DB::table('informasi_sertamertas')->where('id', $m->id)->update($mData);
                } else {
                    $mData['created_at'] = now();
                    DB::table('informasi_sertamertas')->insert($mData);
                }
            }
        }
    }
}
