<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PoltradaBaliDipSeeder extends Seeder
{
    public function run()
    {
        // 1. NONAKTIFKAN SEMUA DATA LAMA AGAR TIDAK MUNCUL TUMPANG TINDIH
        DB::table('daftar_informasis')->update(['aktif' => 0]);
        if (DB::getSchemaBuilder()->hasTable('informasi_berkalas')) {
            DB::table('informasi_berkalas')->update(['aktif' => 0]);
        }
        if (DB::getSchemaBuilder()->hasTable('informasi_setiapsaats')) {
            DB::table('informasi_setiapsaats')->update(['aktif' => 0]);
        }
        if (DB::getSchemaBuilder()->hasTable('informasi_sertamertas')) {
            DB::table('informasi_sertamertas')->update(['aktif' => 0]);
        }

        // =========================================================================
        // 2. DATA INFORMASI BERKALA (26 ITEM - 5 KATEGORI STANDAR POLTRADA BALI)
        // =========================================================================
        $berkalaItems = [
            // A. PROFIL BADAN PUBLIK
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'A. INFORMASI TENTANG PROFIL BADAN PUBLIK',
                'judul_informasi' => 'Profil PKTJ Tegal',
                'isi_informasi' => 'Informasi mengenai profil kelembagaan, kedudukan, sejarah pendirian, alamat kantor, kontak resmi, tugas pokok dan fungsi, serta visi dan misi Politeknik Keselamatan Transportasi Jalan (PKTJ) Tegal.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2026',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/profil-ppid',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'A. INFORMASI TENTANG PROFIL BADAN PUBLIK',
                'judul_informasi' => 'Struktur Organisasi PKTJ Tegal',
                'isi_informasi' => 'Bagan susunan struktur pimpinan, unit kerja struktural, jurusan, program studi, serta struktur organisasi Pejabat Pengelola Informasi dan Dokumentasi (PPID) Pelaksana PKTJ Tegal.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2026',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/profil/struktur-organisasi',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'A. INFORMASI TENTANG PROFIL BADAN PUBLIK',
                'judul_informasi' => 'Profil Singkat Pejabat Struktural PKTJ Tegal',
                'isi_informasi' => 'Biografi ringkas, rekam jejak karir, riwayat pendidikan formal, serta profil tugas Direktur, para Wakil Direktur, dan Kepala Bagian di lingkungan Politeknik Keselamatan Transportasi Jalan Tegal.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2026',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/profil/pejabat',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'A. INFORMASI TENTANG PROFIL BADAN PUBLIK',
                'judul_informasi' => 'Laporan Harta Kekayaan Pejabat Negara (LHKPN) PKTJ',
                'isi_informasi' => 'Rekapitulasi tanda terima dan bukti kepatuhan penyampaian LHKPN para pejabat penyelenggara negara dan pimpinan struktural PKTJ Tegal yang diverifikasi oleh Komisi Pemberantasan Korupsi (KPK).',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2026',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/profil/pejabat',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'A. INFORMASI TENTANG PROFIL BADAN PUBLIK',
                'judul_informasi' => 'Agenda Pimpinan PKTJ Tegal',
                'isi_informasi' => 'Jadwal dan agenda kegiatan kedinasan resmi, kunjungan kerja, serta audiensi Direktur beserta jajaran pimpinan Manajemen Politeknik Keselamatan Transportasi Jalan Tegal.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2026',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/profil-ppid',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'A. INFORMASI TENTANG PROFIL BADAN PUBLIK',
                'judul_informasi' => 'Statistik Data Kepegawaian PKTJ Tegal',
                'isi_informasi' => 'Data statistik dan rekapitulasi jumlah dosen tetap, dosen luar biasa, instruktur diklat, pranata laboratorium, dan tenaga kependidikan ASN maupun PPNPN di PKTJ Tegal.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2026',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/informasi-publik/statistik-pegawai',
                'aktif' => 1,
            ],

            // B. PROGRAM DAN KEGIATAN
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'B. INFORMASI TENTANG PROGRAM DAN KEGIATAN',
                'judul_informasi' => 'Rencana Strategis (Renstra) PKTJ Tegal 2020–2024',
                'isi_informasi' => 'Dokumen Rencana Strategis (Renstra) Politeknik Keselamatan Transportasi Jalan (PKTJ) Tegal periode 2020–2024 yang memuat arah kebijakan, sasaran strategis, dan target kinerja kelembagaan jangka menengah 5 tahun.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2020',
                'jangka_waktu' => '5 Tahun',
                'file_informasi' => '/layanan-informasi/daftar',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'B. INFORMASI TENTANG PROGRAM DAN KEGIATAN',
                'judul_informasi' => 'Rencana Kerja Tahunan (RKT) PKTJ Tegal',
                'isi_informasi' => 'Dokumen penjabaran program kerja tahunan, indikator capaian, dan sasaran operasional unit kerja kampus PKTJ Tegal sebagai implementasi dari Renstra.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/layanan-informasi/daftar',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'B. INFORMASI TENTANG PROGRAM DAN KEGIATAN',
                'judul_informasi' => 'Kalender Akademik & Jadwal Perkuliahan / Diklat PKTJ',
                'isi_informasi' => 'Informasi lengkap jadwal perkuliahan taruna/i, masa ujian tengah/akhir semester, registrasi ulang, wisuda, serta kalender penyelenggaraan diklat teknis transportasi jalan.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Akademik dan Ketarunaan',
                'penerbit_informasi' => 'Bagian Akademik dan Ketarunaan',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/layanan-informasi/daftar',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'B. INFORMASI TENTANG PROGRAM DAN KEGIATAN',
                'judul_informasi' => 'Informasi Penerimaan Calon Taruna (SIPENCATAR) PKTJ',
                'isi_informasi' => 'Pengumuman resmi alur seleksi penerimaan calon taruna/i (SIPENCATAR) jalur pola pembibitan (Polbit) dan mandiri, persyaratan pendaftaran, jadwal tes, dan kuota formasi.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Akademik dan Ketarunaan',
                'penerbit_informasi' => 'Bagian Akademik dan Ketarunaan',
                'bentuk_informasi' => 'Softcopy (Online)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => 'https://sipencatar.dephub.go.id/',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'B. INFORMASI TENTANG PROGRAM DAN KEGIATAN',
                'judul_informasi' => 'Standar Biaya Pendidikan & Tarif Layanan PKTJ',
                'isi_informasi' => 'Rincian tarif layanan pendidikan vokasi program Diploma IV/III, tarif pelatihan/diklat teknis transportasi jalan, serta maklumat pelayanan biaya PKTJ.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/layanan-informasi/maklumat-dan-standar-biaya-layanan',
                'aktif' => 1,
            ],

            // C. KINERJA DAN KEUANGAN
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'C. INFORMASI TENTANG KINERJA DAN KEUANGAN',
                'judul_informasi' => 'Rencana Kerja dan Anggaran K/L (RKA-KL) PKTJ',
                'isi_informasi' => 'Dokumen rencana kerja dan alokasi pagu anggaran belanja kementerian/lembaga satuan kerja PKTJ Tegal untuk pembiayaan operasional dan program prioritas.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/layanan-informasi/daftar',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'C. INFORMASI TENTANG KINERJA DAN KEUANGAN',
                'judul_informasi' => 'Daftar Isian Pelaksanaan Anggaran (DIPA) Induk PKTJ',
                'isi_informasi' => 'Dokumen Daftar Isian Pelaksanaan Anggaran (DIPA) Petikan dan Induk Satuan Kerja PKTJ Tegal yang memuat rincian sumber dana dan alokasi kegiatan tahun berjalan.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/layanan-informasi/daftar',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'C. INFORMASI TENTANG KINERJA DAN KEUANGAN',
                'judul_informasi' => 'Perjanjian Kinerja (PK) PKTJ Tegal',
                'isi_informasi' => 'Dokumen penetapan komitmen dan target kinerja tahunan Direktur PKTJ dengan Kepala BPSDMP Kementerian Perhubungan.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/layanan-informasi/daftar',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'C. INFORMASI TENTANG KINERJA DAN KEUANGAN',
                'judul_informasi' => 'Laporan Akuntabilitas Kinerja Instansi Pemerintah (LAKIP / LKjIP) PKTJ',
                'isi_informasi' => 'Laporan pertanggungjawaban capaian sasaran strategis, efisiensi anggaran, dan realisasi Indikator Kinerja Utama (IKU) PKTJ Tegal tahunan.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/layanan-informasi/daftar',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'C. INFORMASI TENTANG KINERJA DAN KEUANGAN',
                'judul_informasi' => 'Laporan Tahunan PKTJ Tegal',
                'isi_informasi' => 'Laporan komprehensif tahunan pelaksanaan Tri Dharma Perguruan Tinggi, pengembangan sarana kampus, dan tata kelola kelembagaan PKTJ Tegal.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/layanan-informasi/daftar',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'C. INFORMASI TENTANG KINERJA DAN KEUANGAN',
                'judul_informasi' => 'Laporan Keuangan Audited BPK-RI PKTJ',
                'isi_informasi' => 'Laporan Keuangan resmi satuan kerja PKTJ Tegal audited BPK-RI yang memuat Neraca, Laporan Realisasi Anggaran (LRA), Laporan Operasional (LO), LPE, dan CaLK.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/layanan-informasi/daftar',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'C. INFORMASI TENTANG KINERJA DAN KEUANGAN',
                'judul_informasi' => 'Laporan Pelayanan Informasi Publik PPID PKTJ',
                'isi_informasi' => 'Laporan tahunan pelaksanaan layanan keterbukaan informasi publik, rekapitulasi jumlah permohonan informasi, jangka waktu penyelesaian, dan penanganan keberatan.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penerbit_informasi' => 'PPID Pelaksana UPT PKTJ Tegal',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/layanan-informasi/laporan',
                'aktif' => 1,
            ],

            // D. PENGADAAN BARANG DAN JASA
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'D. INFORMASI TENTANG PENGADAAN BARANG DAN JASA',
                'judul_informasi' => 'Rencana Umum Pengadaan (SiRUP) PKTJ Tegal',
                'isi_informasi' => 'Pengumuman Rencana Umum Pengadaan (RUP) barang/jasa pemerintah di lingkungan Politeknik Keselamatan Transportasi Jalan Tegal melalui portal resmi SiRUP LKPP.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'PPK / Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'PPK / Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'Softcopy (Online)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => 'https://sirup.lkpp.go.id/',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'D. INFORMASI TENTANG PENGADAAN BARANG DAN JASA',
                'judul_informasi' => 'Pengumuman Pengadaan Pemilihan Penyedia Barang dan Jasa (LPSE) PKTJ',
                'isi_informasi' => 'Daftar pengumuman tender terbuka, seleksi umum, e-purchasing, dan pengadaan barang/jasa satuan kerja PKTJ Tegal melalui Layanan Pengadaan Secara Elektronik (LPSE) Kemenhub.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Pokja Pemilihan / UKPBJ',
                'penerbit_informasi' => 'Pokja Pemilihan / UKPBJ',
                'bentuk_informasi' => 'Softcopy (Online)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => 'https://lpse.dephub.go.id/',
                'aktif' => 1,
            ],

            // E. PROSEDUR DAN STANDAR PELAYANAN
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'E. INFORMASI TENTANG PROSEDUR DAN STANDAR PELAYANAN',
                'judul_informasi' => 'Standar Pelayanan PPID PKTJ',
                'isi_informasi' => 'Informasi mengenai standar operasional pelayanan informasi publik, persyaratan, biaya/tarif permohonan, jangka waktu respon, serta hak dan kewajiban pemohon.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => '/layanan-informasi/maklumat-dan-standar-biaya-layanan',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'E. INFORMASI TENTANG PROSEDUR DAN STANDAR PELAYANAN',
                'judul_informasi' => 'Maklumat Pelayanan PPID PKTJ',
                'isi_informasi' => 'Pernyataan janji dan kesanggupan segenap pengelola PPID PKTJ untuk memberikan pelayanan informasi publik secara profesional, transparan, dan akuntabel.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penerbit_informasi' => 'PPID Pelaksana UPT PKTJ Tegal',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => '/layanan-informasi/maklumat-dan-standar-biaya-layanan',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'E. INFORMASI TENTANG PROSEDUR DAN STANDAR PELAYANAN',
                'judul_informasi' => 'Tata Cara / Prosedur Permohonan Informasi Publik',
                'isi_informasi' => 'Panduan alur tata cara, tahapan, dan persyaratan administratif permohonan informasi publik ke desk PPID PKTJ secara online melalui formulir daring atau offline.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penerbit_informasi' => 'PPID Pelaksana UPT PKTJ Tegal',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => '/prosedur/permintaan-informasi',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'E. INFORMASI TENTANG PROSEDUR DAN STANDAR PELAYANAN',
                'judul_informasi' => 'Tata Cara / Prosedur Penanganan Keberatan Informasi Publik',
                'isi_informasi' => 'Panduan tata cara dan mekanisme pengajuan keberatan kepada Atasan PPID apabila pemohon informasi tidak puas atas tanggapan atau pelayanan PPID.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penerbit_informasi' => 'PPID Pelaksana UPT PKTJ Tegal',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => '/prosedur/penanganan-keberatan',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'E. INFORMASI TENTANG PROSEDUR DAN STANDAR PELAYANAN',
                'judul_informasi' => 'Tata Cara / Prosedur Penyelesaian Sengketa Informasi Publik',
                'isi_informasi' => 'Mekanisme dan tahapan pengajuan gugatan sengketa informasi publik ke Komisi Informasi Pusat (KIP) apabila tanggapan keberatan tidak diselesaikan.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penerbit_informasi' => 'PPID Pelaksana UPT PKTJ Tegal',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => '/prosedur/sengketa-informasi',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'sub_kategori' => 'E. INFORMASI TENTANG PROSEDUR DAN STANDAR PELAYANAN',
                'judul_informasi' => 'Tata Cara / Prosedur Pengaduan Masyarakat (Whistleblowing System & LAPOR!)',
                'isi_informasi' => 'Mekanisme penyampaian laporan pengaduan masyarakat atas dugaan penyalahgunaan wewenang atau keluhan layanan publik via SP4N-LAPOR! dan WBS Kemenhub.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Satuan Pengawas Internal (SPI)',
                'penerbit_informasi' => 'Satuan Pengawas Internal (SPI)',
                'bentuk_informasi' => 'Softcopy (Online)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => 'https://www.lapor.go.id/',
                'aktif' => 1,
            ],
        ];

        // =========================================================================
        // 3. DATA INFORMASI SETIAP SAAT (10 ITEM - STANDAR POLTRADA BALI)
        // =========================================================================
        $setiapSaatItems = [
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiap-saat',
                'judul_informasi' => 'Daftar Informasi Publik (DIP) PKTJ',
                'isi_informasi' => 'Dokumen usulan dan keputusan penetapan Daftar Informasi Publik (DIP) berkala, setiap saat, dan serta merta yang wajib disediakan di lingkungan PKTJ Tegal.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Seluruh Unit Kerja PKTJ',
                'penerbit_informasi' => 'Seluruh Unit Kerja PKTJ',
                'bentuk_informasi' => 'Cetak & Online',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Hingga Pemutakhiran',
                'file_informasi' => '/layanan-informasi/daftar',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiap-saat',
                'judul_informasi' => 'SOP Layanan Informasi Publik PPID',
                'isi_informasi' => 'Standar Operasional Prosedur penatausahaan pelayanan informasi publik, SOP uji konsekuensi informasi, dan SOP fasilitasi sengketa informasi.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penerbit_informasi' => 'PPID Pelaksana UPT PKTJ Tegal',
                'bentuk_informasi' => 'Cetak & Online',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => '/prosedur/permintaan-informasi',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiap-saat',
                'judul_informasi' => 'Surat Menyurat & Registrasi Naskah Dinas',
                'isi_informasi' => 'Informasi buku register persuratan naskah dinas masuk dan keluar resmi satuan kerja Politeknik Keselamatan Transportasi Jalan Tegal.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Subbagian Tata Usaha & Rumah Tangga',
                'penerbit_informasi' => 'Subbagian Tata Usaha & Rumah Tangga',
                'bentuk_informasi' => 'Cetak & Online',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => '/layanan-informasi/daftar',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiap-saat',
                'judul_informasi' => 'Data Inventaris Barang Milik Negara (BMN) PKTJ',
                'isi_informasi' => 'Laporan penatausahaan, inventarisasi aset, dan pencatatan Barang Milik Negara (BMN) di lingkungan kampus PKTJ Tegal audited.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/layanan-informasi/daftar',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiap-saat',
                'judul_informasi' => 'Pedoman Sistem Penjaminan Mutu Internal (SPMI) PKTJ',
                'isi_informasi' => 'Dokumen kebijakan mutu, manual mutu pendidikan vokasi, standar nasional pendidikan tinggi, dan instrumen audit mutu internal PKTJ Tegal.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Pusat Pengembangan Pembelajaran & SPMI (P4MP)',
                'penerbit_informasi' => 'Pusat Pengembangan Pembelajaran & SPMI (P4MP)',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Sesuai Retensi Arsip',
                'file_informasi' => '/layanan-informasi/daftar',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiap-saat',
                'judul_informasi' => 'Dokumentasi & Kegiatan Pimpinan PKTJ',
                'isi_informasi' => 'Dokumentasi foto, siaran pers, dan liputan video kegiatan kedinasan Direktur serta agenda strategis kelembagaan PKTJ Tegal.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Tim Humas & Publikasi PKTJ',
                'penerbit_informasi' => 'Tim Humas & Publikasi PKTJ',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => '/profil-ppid',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiap-saat',
                'judul_informasi' => 'Kurikulum & Silabus Program Studi PKTJ',
                'isi_informasi' => 'Keputusan Direktur mengenai kurikulum program studi D4 Manajemen Keselamatan Transportasi Jalan, D4 Rekayasa Sistem Transportasi Jalan, dan D3 Teknologi Otomotif.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Akademik dan Ketarunaan',
                'penerbit_informasi' => 'Bagian Akademik dan Ketarunaan',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => '/layanan-informasi/daftar',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiap-saat',
                'judul_informasi' => 'Himpunan Peraturan & Kebijakan Direktur PKTJ',
                'isi_informasi' => 'Kompilasi Peraturan Direktur, Tata Tertib Taruna/i, Pedoman Pembinaan Ketarunaan, dan Surat Edaran internal kampus yang berlaku.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Subbagian Kepegawaian & Tata Usaha',
                'penerbit_informasi' => 'Subbagian Kepegawaian & Tata Usaha',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => '/layanan-informasi/daftar',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiap-saat',
                'judul_informasi' => 'Data Inventaris Kendaraan Dinas & Sarana Transportasi PKTJ',
                'isi_informasi' => 'Daftar inventaris sarana kendaraan operasional roda empat, bus kampus, dan armada kendaraan dinas di lingkungan PKTJ Tegal.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Subbagian Rumah Tangga & Perlengkapan',
                'penerbit_informasi' => 'Subbagian Rumah Tangga & Perlengkapan',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/layanan-informasi/daftar',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiap-saat',
                'judul_informasi' => 'Data Fasilitas & Sarana Laboratorium PKTJ',
                'isi_informasi' => 'Informasi sarana laboratorium keselamatan jalan, bengkel uji berkala kendaraan bermotor, simulator pengemudi, sirkuit uji kelayakan kendaraan kampus PKTJ.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Laboratorium & Bengkel Uji PKTJ',
                'penerbit_informasi' => 'Laboratorium & Bengkel Uji PKTJ',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Sesuai Retensi Arsip',
                'file_informasi' => '/layanan-informasi/daftar',
                'aktif' => 1,
            ],
        ];

        // =========================================================================
        // 4. DATA INFORMASI SERTA MERTA (1 ITEM - STANDAR POLTRADA BALI)
        // =========================================================================
        $sertaMertaItems = [
            [
                'kategori' => 'informasi-serta-merta',
                'tipe_informasi' => 'serta-merta',
                'judul_informasi' => 'Penutupan Layanan Publik / Sarana Prasarana Akibat Keadaan Darurat',
                'isi_informasi' => 'Pemberitahuan darurat dan pengumuman resmi mengenai penutupan sementara fasilitas pendidikan kampus, penundaan kegiatan perkuliahan, atau penyesuaian layanan publik akibat keadaan kahar (force majeure), bencana alam, cuaca ekstrem, kebakaran, atau ancaman keselamatan umum lainnya.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Seluruh Unit Kerja di Lingkungan PKTJ Tegal',
                'penerbit_informasi' => 'Seluruh Unit Kerja di Lingkungan PKTJ Tegal',
                'bentuk_informasi' => 'Hardcopy & Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/layanan-informasi/daftar',
                'aktif' => 1,
            ],
        ];

        // =========================================================================
        // 5. EKSEKUSI PENYIMPANAN KE TABEL DAFTAR_INFORMASIS & MODEL TERKAIT
        // =========================================================================
        $allItems = array_merge($berkalaItems, $setiapSaatItems, $sertaMertaItems);

        foreach ($allItems as $it) {
            $existing = DB::table('daftar_informasis')
                ->where('judul_informasi', $it['judul_informasi'])
                ->first();

            $dataToSave = [
                'kategori' => $it['kategori'],
                'tipe_informasi' => $it['tipe_informasi'],
                'judul_informasi' => $it['judul_informasi'],
                'isi_informasi' => $it['isi_informasi'],
                'pejabat_penguasa' => $it['pejabat_penguasa'],
                'penanggung_jawab' => $it['penanggung_jawab'],
                'penerbit_informasi' => $it['penerbit_informasi'],
                'bentuk_informasi' => $it['bentuk_informasi'],
                'tempat_pembuatan' => $it['tempat_pembuatan'],
                'waktu_pembuatan' => $it['waktu_pembuatan'],
                'jangka_waktu' => $it['jangka_waktu'],
                'file_informasi' => $it['file_informasi'],
                'aktif' => 1,
                'bisa_download' => 1,
                'is_blurred' => 0,
                'updated_at' => now(),
            ];

            if ($existing) {
                DB::table('daftar_informasis')->where('id', $existing->id)->update($dataToSave);
            } else {
                $dataToSave['created_at'] = now();
                DB::table('daftar_informasis')->insert($dataToSave);
            }

            // Sync ke model masing-masing jika tabelnya ada
            if ($it['kategori'] === 'informasi-berkala' && DB::getSchemaBuilder()->hasTable('informasi_berkalas')) {
                $m = DB::table('informasi_berkalas')->where('judul', $it['judul_informasi'])->first();
                $mData = [
                    'judul' => $it['judul_informasi'],
                    'deskripsi' => $it['isi_informasi'],
                    'file_path' => $it['file_informasi'],
                    'aktif' => 1,
                    'is_blurred' => 0,
                    'bisa_download' => 1,
                    'tanggal' => date('Y-m-d'),
                    'updated_at' => now(),
                ];
                if ($m) {
                    DB::table('informasi_berkalas')->where('id', $m->id)->update($mData);
                } else {
                    $mData['created_at'] = now();
                    DB::table('informasi_berkalas')->insert($mData);
                }
            } elseif (in_array($it['kategori'], ['informasi-setiap-saat', 'informasi-setiapsaat']) && DB::getSchemaBuilder()->hasTable('informasi_setiapsaats')) {
                $m = DB::table('informasi_setiapsaats')->where('judul', $it['judul_informasi'])->first();
                $mData = [
                    'judul' => $it['judul_informasi'],
                    'deskripsi' => $it['isi_informasi'],
                    'file_path' => $it['file_informasi'],
                    'aktif' => 1,
                    'is_blurred' => 0,
                    'bisa_download' => 1,
                    'tanggal' => date('Y-m-d'),
                    'updated_at' => now(),
                ];
                if ($m) {
                    DB::table('informasi_setiapsaats')->where('id', $m->id)->update($mData);
                } else {
                    $mData['created_at'] = now();
                    DB::table('informasi_setiapsaats')->insert($mData);
                }
            } elseif (in_array($it['kategori'], ['informasi-serta-merta', 'informasi-sertamerta']) && DB::getSchemaBuilder()->hasTable('informasi_sertamertas')) {
                $m = DB::table('informasi_sertamertas')->where('judul', $it['judul_informasi'])->first();
                $mData = [
                    'judul' => $it['judul_informasi'],
                    'deskripsi' => $it['isi_informasi'],
                    'file_path' => $it['file_informasi'],
                    'aktif' => 1,
                    'is_blurred' => 0,
                    'bisa_download' => 1,
                    'tanggal' => date('Y-m-d'),
                    'updated_at' => now(),
                ];
                if ($m) {
                    DB::table('informasi_sertamertas')->where('id', $m->id)->update($mData);
                } else {
                    $mData['created_at'] = now();
                    DB::table('informasi_sertamertas')->insert($mData);
                }
            }
        }
    }
}
