<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\DaftarInformasi;
use App\Models\InformasiBerkala;
use App\Models\InformasiSetiapSaat;
use App\Models\InformasiSertaMerta;
use App\Models\InformasiDikecualikan;

class PoltradaBaliDipSeeder extends Seeder
{
    public function run()
    {
        // 1. Nonaktifkan status aktif lama terlebih dahulu (draft)
        DB::table('daftar_informasis')->update(['aktif' => 0]);
        if (DB::getSchemaBuilder()->hasTable('informasi_berkalas')) {
            DB::table('informasi_berkalas')->update(['aktif' => 0]);
        }
        if (DB::getSchemaBuilder()->hasTable('informasi_setiapsaats')) {
            DB::table('informasi_setiapsaats')->update(['aktif' => 0]);
        }
        if (DB::getSchemaBuilder()->hasTable('informasi_sertamertas')) {
            DB::table('informasi_sertamertas')->update(['aktif' => 0]);
        }
        if (DB::getSchemaBuilder()->hasTable('informasi_dikecualikans')) {
            DB::table('informasi_dikecualikans')->update(['aktif' => 0]);
        }

        // =========================================================================
        // 2. DATA INFORMASI BERKALA
        // =========================================================================
        $berkalaItems = [
            // PROFIL & MENU RESMI (AKTIF KARENA MEMILIKI HALAMAN RIIL)
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PROFIL',
                'judul_informasi' => 'Profil PKTJ Tegal',
                'isi_informasi' => 'Informasi mengenai kedudukan, alamat lengkap, kontak, gambaran umum, tugas dan fungsi, serta visi-misi PKTJ Tegal',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/profil-ppid',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PROFIL',
                'judul_informasi' => 'Struktur Organisasi di lingkungan PKTJ Tegal',
                'isi_informasi' => 'Struktur pejabat struktural dan fungsional di lingkungan PKTJ Tegal',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/profil/struktur-organisasi',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PROFIL',
                'judul_informasi' => 'Profil Singkat Pejabat PKTJ Tegal',
                'isi_informasi' => 'Data diri pejabat struktural dan fungsional serta riwayat jabatan',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/profil/pejabat',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PROFIL',
                'judul_informasi' => 'Laporan Harta Kekayaan Pejabat Negara (LHKPN)',
                'isi_informasi' => 'Laporan LHKPN yang telah diverifikasi dan diumumkan oleh KPK',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/profil/pejabat',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PROFIL',
                'judul_informasi' => 'Agenda Pimpinan PKTJ Tegal',
                'isi_informasi' => 'Jadwal dan agenda kegiatan pimpinan kelembagaan PKTJ Tegal',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/profil-ppid',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PROFIL',
                'judul_informasi' => 'Statistik Data Kepegawaian PKTJ Tegal',
                'isi_informasi' => 'Data statistik dan rekapitulasi jumlah dosen serta tenaga kependidikan PKTJ Tegal',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/informasi-publik/statistik-pegawai',
                'aktif' => 1,
            ],

            // LAYANAN & PROSEDUR RESMI (AKTIF KARENA MEMILIKI ROUTE RIIL)
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'TATA CARA / PROSEDUR',
                'judul_informasi' => 'Informasi Penerimaan Calon Taruna (SIPENCATAR) PKTJ',
                'isi_informasi' => 'Pengumuman seleksi penerimaan calon taruna/i pola pembibitan dan mandiri PKTJ',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Administrasi Akademik dan Ketarunaan',
                'penerbit_informasi' => 'Bagian Administrasi Akademik dan Ketarunaan',
                'bentuk_informasi' => 'softcopy (online)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => 'https://sipencatar.dephub.go.id/',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PENGADAAN BARANG DAN JASA',
                'judul_informasi' => 'Rencana Umum Pengadaan (SiRUP) PKTJ Tegal',
                'isi_informasi' => 'Pengumuman Rencana Umum Pengadaan (RUP) barang/jasa PKTJ melalui SiRUP LKPP',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'PPK / Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'PPK / Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'softcopy (online)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => 'https://sirup.lkpp.go.id/',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PENGADAAN BARANG DAN JASA',
                'judul_informasi' => 'Pengumuman Pengadaan Pemilihan Penyedia Barang dan Jasa (LPSE) PKTJ',
                'isi_informasi' => 'Daftar pengumuman tender dan seleksi pengadaan barang/jasa via LPSE Kemenhub',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Pokja Pemilihan / UKPBJ',
                'penerbit_informasi' => 'Pokja Pemilihan / UKPBJ',
                'bentuk_informasi' => 'softcopy (online)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => 'https://lpse.dephub.go.id/',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'TATA CARA / PROSEDUR',
                'judul_informasi' => 'Tata cara permohonan informasi publik',
                'isi_informasi' => 'Mekanisme dan tahapan pengajuan permohonan informasi publik secara langsung atau daring',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/prosedur/permintaan-informasi',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'TATA CARA / PROSEDUR',
                'judul_informasi' => 'Tata cara mengajukan keberatan informasi publik',
                'isi_informasi' => 'Mekanisme penyampaian keberatan atas permohonan informasi publik',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/prosedur/penanganan-keberatan',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'TATA CARA / PROSEDUR',
                'judul_informasi' => 'Tata cara penyelesaian sengketa informasi publik',
                'isi_informasi' => 'Mekanisme penyelesaian sengketa informasi publik ke Komisi Informasi',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/prosedur/sengketa-informasi',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'TATA CARA / PROSEDUR',
                'judul_informasi' => 'Tata cara pengaduan masyarakat (Whistleblowing System & LAPOR!)',
                'isi_informasi' => 'Mekanisme penyampaian laporan pengaduan masyarakat via SP4N-LAPOR! dan WBS Kemenhub',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Satuan Pengawas Internal (SPI)',
                'penerbit_informasi' => 'Satuan Pengawas Internal (SPI)',
                'bentuk_informasi' => 'softcopy (online)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => 'https://www.lapor.go.id/',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'TATA CARA / PROSEDUR',
                'judul_informasi' => 'Standar Pelayanan PPID PKTJ',
                'isi_informasi' => 'Standar operasional prosedur pelayanan informasi publik dan jangka waktu respon',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => '/layanan-informasi/maklumat-dan-standar-biaya-layanan',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'TATA CARA / PROSEDUR',
                'judul_informasi' => 'Maklumat Pelayanan PPID PKTJ',
                'isi_informasi' => 'Pernyataan janji dan kesanggupan segenap pengelola PPID PKTJ dalam melayani publik',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penerbit_informasi' => 'PPID Pelaksana UPT PKTJ Tegal',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => '/layanan-informasi/maklumat-dan-standar-biaya-layanan',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'KINERJA DAN KEUANGAN',
                'judul_informasi' => 'Laporan Pelayanan Informasi Publik PPID PKTJ',
                'isi_informasi' => 'Laporan tahunan pelaksanaan layanan keterbukaan informasi publik PPID PKTJ',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penerbit_informasi' => 'PPID Pelaksana UPT PKTJ Tegal',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/layanan-informasi/laporan',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'judul_informasi' => 'Standar Biaya Pendidikan & Tarif Layanan PKTJ',
                'isi_informasi' => 'Informasi tarif layanan pendidikan, biaya kuliah, dan tarif PNBP PKTJ',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => '/layanan-informasi/maklumat-dan-standar-biaya-layanan',
                'aktif' => 1,
            ],

            // DOKUMEN RESMI PKTJ YANG MEMILIKI LINK GOOGLE DRIVE RIIL (AKTIF = 1)
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'KINERJA DAN MUTU',
                'judul_informasi' => 'Laporan Survey Kepuasan Masyarakat & Indeks Persepsi Korupsi PKTJ Semester I 2025',
                'isi_informasi' => 'Laporan hasil pengukuran Indeks Kepuasan Masyarakat (IKM) dan Indeks Persepsi Korupsi (IPK) Politeknik Keselamatan Transportasi Jalan Semester I Tahun 2025.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Satuan Penjaminan Mutu (SPM)',
                'penerbit_informasi' => 'Satuan Penjaminan Mutu (SPM)',
                'bentuk_informasi' => 'Softcopy (PDF)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '5 Tahun',
                'file_informasi' => 'https://drive.google.com/file/d/1zo0Pca8RdyBejtSZOv3QznCp8sXybGlG/view?usp=drive_link',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'KINERJA DAN MUTU',
                'judul_informasi' => 'Sertifikat & Laporan Audit Surveillance ISO 21001:2018 PKTJ',
                'isi_informasi' => 'Dokumen hasil Audit Surveillance dari SGS Indonesia terkait Penerapan ISO 21001:2018 pada Sistem Manajemen Organisasi Pendidikan PKTJ Tegal.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Satuan Penjaminan Mutu (SPM)',
                'penerbit_informasi' => 'Satuan Penjaminan Mutu (SPM)',
                'bentuk_informasi' => 'Softcopy (PDF)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '3 Tahun',
                'file_informasi' => 'https://drive.google.com/file/d/1Y-3lLIDFb5NOHJQJb2tFY_BA8KtBV_Ow/view?usp=drive_link',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PENELITIAN & PENGABDIAN',
                'judul_informasi' => 'Roadmap Penelitian dan Pengabdian Kepada Masyarakat (PPPM) PKTJ 2025–2029',
                'isi_informasi' => 'Peta jalan (Roadmap) rencana strategis arah penelitian terapan dan program pengabdian kepada masyarakat civitas akademika PKTJ untuk periode 5 tahun.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Pusat Penelitian dan Pengabdian Masyarakat (PPPM)',
                'penerbit_informasi' => 'Pusat Penelitian dan Pengabdian Masyarakat (PPPM)',
                'bentuk_informasi' => 'Softcopy (PDF)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '5 Tahun',
                'file_informasi' => 'https://drive.google.com/file/d/1Kcoka0G7I_yJljKUPM0tawnF91FqM57s/view?usp=drive_link',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PENDIDIKAN DAN PELATIHAN',
                'judul_informasi' => 'Laporan Pelaksanaan Diklat Pemberdayaan Masyarakat (DPM) PKTJ Tahun 2025',
                'isi_informasi' => 'Laporan pelaksanaan program Diklat Pemberdayaan Masyarakat (DPM) yang diselenggarakan oleh PKTJ bagi masyarakat luas secara gratis.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Administrasi Akademik dan Ketarunaan',
                'penerbit_informasi' => 'Bagian Administrasi Akademik dan Ketarunaan',
                'bentuk_informasi' => 'Softcopy (Google Drive)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '3 Tahun',
                'file_informasi' => 'https://drive.google.com/drive/folders/1cXqcNK56x99HLxIfS83-leLMysIjIP7k?usp=drive_link',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PENDIDIKAN DAN PELATIHAN',
                'judul_informasi' => 'Laporan Pelaksanaan Diklat Teknis Sektor Perhubungan Darat PKTJ Tahun 2025',
                'isi_informasi' => 'Laporan rekapitulasi pelaksanaan seluruh program pendidikan dan pelatihan teknis perhubungan darat yang diselenggarakan oleh PKTJ.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Administrasi Akademik dan Ketarunaan',
                'penerbit_informasi' => 'Bagian Administrasi Akademik dan Ketarunaan',
                'bentuk_informasi' => 'Softcopy (Google Drive)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '3 Tahun',
                'file_informasi' => 'https://drive.google.com/drive/folders/1cXqcNK56x99HLxIfS83-leLMysIjIP7k?usp=drive_link',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'KETARUNAAN & ALUMNI',
                'judul_informasi' => 'Laporan Tracer Study & Keterserapan Lulusan PKTJ Tahun 2025',
                'isi_informasi' => 'Laporan penelusuran lulusan (tracer study) alumni PKTJ dari program studi Sarjana Terapan RSTJ, TRO, dan D-III TO terkait waktu tunggu kerja.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Ketarunaan dan Alumni',
                'penerbit_informasi' => 'Unit Ketarunaan dan Alumni',
                'bentuk_informasi' => 'Softcopy (PDF)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '5 Tahun',
                'file_informasi' => 'https://drive.google.com/file/d/1RBZ_YmRFmYi375UCMl123cCOeRZTWHe8/view?usp=sharing',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PELAYANAN KESEHATAN',
                'judul_informasi' => 'Laporan Statistik Kunjungan Pasien Klinik Pratama PKTJ Tahun 2025',
                'isi_informasi' => 'Rekapitulasi data agregat kunjungan pelayanan kesehatan pasien di Klinik Pratama PKTJ yang meliputi taruna, pegawai, dan masyarakat umum.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Kesehatan PKTJ',
                'penerbit_informasi' => 'Unit Kesehatan PKTJ',
                'bentuk_informasi' => 'Softcopy (PDF)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '3 Tahun',
                'file_informasi' => 'https://drive.google.com/file/d/1vWf6PsrK6V71WEs3wm8fgoiMyIsJ1W-N/view?usp=drive_link',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PELAYANAN KESEHATAN',
                'judul_informasi' => 'Laporan Pemeriksaan Kesehatan Gratis Pengemudi Ojek Online (Harhubnas 2025)',
                'isi_informasi' => 'Laporan kegiatan bakti sosial pemeriksaan kesehatan gratis bagi pengemudi ojek online dalam rangka Hari Perhubungan Nasional Tahun 2025.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Kesehatan PKTJ',
                'penerbit_informasi' => 'Unit Kesehatan PKTJ',
                'bentuk_informasi' => 'Softcopy (PDF)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '2 Tahun',
                'file_informasi' => 'https://drive.google.com/file/d/10Cx6BNadJheg02d7LmKzlMwYZOGr9Ul-/view?usp=drive_link',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PELAYANAN KESEHATAN',
                'judul_informasi' => 'Laporan Pemeriksaan Kesehatan Gratis Pengemudi Ojek Online (HUT RI ke-80)',
                'isi_informasi' => 'Laporan kegiatan pelayanan pemeriksaan kesehatan gratis bagi komunitas pengemudi ojek online dalam rangka memperingati HUT Kemerdekaan RI ke-80.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Kesehatan PKTJ',
                'penerbit_informasi' => 'Unit Kesehatan PKTJ',
                'bentuk_informasi' => 'Softcopy (PDF)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '2 Tahun',
                'file_informasi' => 'https://drive.google.com/file/d/1MS8a1hTkvMCwNKH-QMc4hS6VCxSXO61d/view?usp=drive_link',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PELAYANAN KESEHATAN',
                'judul_informasi' => 'Laporan Sosialisasi P4GN (Pencegahan Bahaya Narkoba) Civitas Akademika PKTJ',
                'isi_informasi' => 'Laporan pelaksanaan program sosialisasi Pencegahan, Pemberantasan, Penyalahgunaan dan Peredaran Gelap Narkotika (P4GN) bagi taruna PKTJ.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Kesehatan PKTJ',
                'penerbit_informasi' => 'Unit Kesehatan PKTJ',
                'bentuk_informasi' => 'Softcopy (PDF)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '3 Tahun',
                'file_informasi' => 'https://drive.google.com/file/d/1WXfB3EEAb-ZjGr0Mqz8JLqjbDofEvqsC/view?usp=drive_link',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PELAYANAN KESEHATAN',
                'judul_informasi' => 'Laporan Penyuluhan Kesehatan Gigi dan Mulut Taruna PKTJ',
                'isi_informasi' => 'Laporan kegiatan edukasi dan penyuluhan berkala mengenai kesehatan umum dan kebersihan gigi serta mulut taruna PKTJ.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Kesehatan PKTJ',
                'penerbit_informasi' => 'Unit Kesehatan PKTJ',
                'bentuk_informasi' => 'Softcopy (Google Drive)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '2 Tahun',
                'file_informasi' => 'https://drive.google.com/drive/folders/1ecQyl5Pvzpq7Z_HAi5uARDz0qeEirAwu?usp=drive_link',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PELAYANAN KESEHATAN',
                'judul_informasi' => 'Laporan Kegiatan Donor Darah Harhubnas Sivitas Akademika PKTJ',
                'isi_informasi' => 'Laporan penyelenggaraan aksi donor darah kemanusiaan dalam rangka peringatan Hari Perhubungan Nasional di lingkungan PKTJ.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Kesehatan PKTJ',
                'penerbit_informasi' => 'Unit Kesehatan PKTJ',
                'bentuk_informasi' => 'Softcopy (Google Drive)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '2 Tahun',
                'file_informasi' => 'https://drive.google.com/drive/folders/1GYqIyr1QfteIBYA0wsrzVe1IOvswicQr?usp=drive_link',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'ASRAMA DAN KETARUNAAN',
                'judul_informasi' => 'Laporan Kebersihan Asrama Taruna PKTJ Tahun 2025',
                'isi_informasi' => 'Laporan konsolidasi pelaksanaan pemeriksaan, pemantauan, dan evaluasi kebersihan kamar asrama dan lingkungan hunian taruna PKTJ selama Tahun 2025.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Asrama dan Fasilitas Taruna',
                'penerbit_informasi' => 'Unit Asrama dan Fasilitas Taruna',
                'bentuk_informasi' => 'Softcopy (Google Drive)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '2 Tahun',
                'file_informasi' => 'https://drive.google.com/drive/folders/1j5lC-salWAeDNZ_g4pUPEqgpNoKSv90J',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'ASRAMA DAN KETARUNAAN',
                'judul_informasi' => 'Laporan Pemeliharaan & Perbaikan Fasilitas Asrama Taruna PKTJ Tahun 2025',
                'isi_informasi' => 'Laporan periodik pemeliharaan fasilitas asrama, perbaikan sarana prasarana kamar taruna, dan utilitas pendukung asrama PKTJ selama Tahun 2025.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Asrama dan Fasilitas Taruna',
                'penerbit_informasi' => 'Unit Asrama dan Fasilitas Taruna',
                'bentuk_informasi' => 'Softcopy (Google Drive)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '2 Tahun',
                'file_informasi' => 'https://drive.google.com/drive/folders/1j5lC-salWAeDNZ_g4pUPEqgpNoKSv90J',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'LABORATORIUM & PRAKTIKUM',
                'judul_informasi' => 'Daftar Inventarisasi Peralatan & Perlengkapan Laboratorium PKTJ',
                'isi_informasi' => 'Daftar rekapitulasi inventarisasi peralatan uji coba, mesin praktikum, dan perlengkapan pengujian di seluruh laboratorium terpadu PKTJ.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Laboratorium PKTJ',
                'penerbit_informasi' => 'Unit Laboratorium PKTJ',
                'bentuk_informasi' => 'Softcopy (Linktree / Web)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '3 Tahun',
                'file_informasi' => 'https://linktr.ee/lab_pktj',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'LABORATORIUM & PRAKTIKUM',
                'judul_informasi' => 'Rekapitulasi Permintaan & Penggunaan Laboratorium Praktikum PKTJ',
                'isi_informasi' => 'Rekapitulasi penggunaan sarana praktikum laboratorium oleh taruna, instruktur diklat, dan dosen untuk kegiatan pembelajaran dan riset terapan.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Laboratorium PKTJ',
                'penerbit_informasi' => 'Unit Laboratorium PKTJ',
                'bentuk_informasi' => 'Softcopy (Linktree / Web)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '2 Tahun',
                'file_informasi' => 'https://linktr.ee/lab_pktj',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'LABORATORIUM & PRAKTIKUM',
                'judul_informasi' => 'Rekapitulasi Perawatan & Kalibrasi Alat Laboratorium PKTJ',
                'isi_informasi' => 'Laporan rekapitulasi kegiatan perawatan rutin, pemeliharaan berkala, dan kalibrasi peralatan praktikum di laboratorium keselamatan jalan PKTJ.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Laboratorium PKTJ',
                'penerbit_informasi' => 'Unit Laboratorium PKTJ',
                'bentuk_informasi' => 'Softcopy (Linktree / Web)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '3 Tahun',
                'file_informasi' => 'https://linktr.ee/lab_pktj',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'LABORATORIUM & PRAKTIKUM',
                'judul_informasi' => 'Dokumentasi & Pelaksanaan Praktikum Laboratorium PKTJ',
                'isi_informasi' => 'Dokumentasi visual dan catatan pelaksanaan kegiatan praktikum terpadu taruna di instalasi laboratorium pengujian kendaraan dan jalan PKTJ.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Laboratorium PKTJ',
                'penerbit_informasi' => 'Unit Laboratorium PKTJ',
                'bentuk_informasi' => 'Softcopy (Linktree / Web)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '2 Tahun',
                'file_informasi' => 'https://linktr.ee/lab_pktj',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'LABORATORIUM & PRAKTIKUM',
                'judul_informasi' => 'Pemetaan & Jadwal Penggunaan Laboratorium PKTJ Setiap Semester',
                'isi_informasi' => 'Matriks jadwal dan pemetaan alokasi penggunaan laboratorium bagi seluruh program studi per semester guna efektivitas praktikum taruna.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Laboratorium PKTJ',
                'penerbit_informasi' => 'Unit Laboratorium PKTJ',
                'bentuk_informasi' => 'Softcopy (Linktree / Web)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => 'https://linktr.ee/lab_pktj',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'UNIT PENDUKUNG',
                'judul_informasi' => 'Program Kerja Tahunan & Sasaran Mutu Unit Bahasa PKTJ',
                'isi_informasi' => 'Dokumen rencana kerja tahunan dan target sasaran mutu Unit Bahasa PKTJ dalam peningkatan kompetensi bahasa asing civitas akademika.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Bahasa PKTJ',
                'penerbit_informasi' => 'Unit Bahasa PKTJ',
                'bentuk_informasi' => 'Softcopy (Google Drive)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '3 Tahun',
                'file_informasi' => 'https://drive.google.com/drive/u/1/folders/1MfhK-FPxNBLlTEss5_5xgde8hOJILdLT',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'UNIT PENDUKUNG',
                'judul_informasi' => 'Struktur Organisasi & Tata Kerja Unit Teknologi Informasi PKTJ',
                'isi_informasi' => 'Bagan susunan struktur organisasi, fungsi, dan tata hubungan kerja Unit Teknologi Informasi di bawah Bagian Keuangan dan Umum PKTJ.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Teknologi Informasi',
                'penerbit_informasi' => 'Unit Teknologi Informasi',
                'bentuk_informasi' => 'Softcopy (PDF)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Permanen',
                'file_informasi' => 'https://drive.google.com/file/d/1qf007NChqtIdko7ztiGrXwgs4PUPMuYO/view?usp=drive_link',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PENGEMBANGAN USAHA',
                'judul_informasi' => 'Katalog & Penawaran Program Diklat Teknis Sektor Perhubungan Darat PKTJ',
                'isi_informasi' => 'Daftar katalog program diklat teknis keahlian transportasi darat, ketentuan kurikulum, silabus, dan informasi penawaran pelatihan.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Pengembangan Usaha (UPU)',
                'penerbit_informasi' => 'Unit Pengembangan Usaha (UPU)',
                'bentuk_informasi' => 'Softcopy (Google Drive)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '2 Tahun',
                'file_informasi' => 'https://drive.google.com/drive/folders/1_ZyJK5OAbFBbh9Wz_20-5PrIOW_1PsAN',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PENGEMBANGAN USAHA',
                'judul_informasi' => 'Surat Keputusan Tarif Layanan Penunjang Akademik PKTJ',
                'isi_informasi' => 'Surat Keputusan Direktur PKTJ tentang Penetapan Tarif Layanan Penunjang Akademik sebagai bentuk keterbukaan tarif layanan Badan Layanan Umum.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Pengembangan Usaha (UPU)',
                'penerbit_informasi' => 'Unit Pengembangan Usaha (UPU)',
                'bentuk_informasi' => 'Softcopy (PDF)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '5 Tahun',
                'file_informasi' => 'https://drive.google.com/file/d/1wONd8mSyTWiYm8oq4DQHlXp4PKqyLKW6/view?usp=drivesdk',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PENGEMBANGAN USAHA',
                'judul_informasi' => 'Surat Keputusan Tarif Layanan Pendidikan & Pelatihan Teknis PKTJ',
                'isi_informasi' => 'Surat Keputusan Direktur PKTJ tentang Tarif Layanan Diklat Teknis Perhubungan Darat dan Pelatihan Kompetensi Keselamatan Transportasi Jalan.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Pengembangan Usaha (UPU)',
                'penerbit_informasi' => 'Unit Pengembangan Usaha (UPU)',
                'bentuk_informasi' => 'Softcopy (PDF)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '5 Tahun',
                'file_informasi' => 'https://drive.google.com/file/d/1NZXstlfM_LJ7By9qCsvTVSvv3yTW_kwO/view?usp=drivesdk',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PERPUSTAKAAN',
                'judul_informasi' => 'Profil & Fasilitas Layanan Unit Perpustakaan PKTJ',
                'isi_informasi' => 'Profil kelembagaan perpustakaan PKTJ, sejarah singkat, visi, misi, jam operasional pelayanan, serta fasilitas sarana membaca digital dan fisik.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Perpustakaan PKTJ',
                'penerbit_informasi' => 'Unit Perpustakaan PKTJ',
                'bentuk_informasi' => 'Softcopy (PDF)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '3 Tahun',
                'file_informasi' => 'https://drive.google.com/file/d/1MwezHxQxQaKgyyuiJaKkysKDjF98gVLe/view?usp=sharing',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PERPUSTAKAAN',
                'judul_informasi' => 'Laporan Statistik Koleksi Bahan Pustaka & Kunjungan Pemustaka PKTJ',
                'isi_informasi' => 'Laporan data statistik jumlah penambahan koleksi buku/jurnal, rekapitulasi pengunjung, dan sirkulasi peminjaman di Perpustakaan PKTJ.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Perpustakaan PKTJ',
                'penerbit_informasi' => 'Unit Perpustakaan PKTJ',
                'bentuk_informasi' => 'Softcopy (Google Drive)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '3 Tahun',
                'file_informasi' => 'https://drive.google.com/drive/folders/1XlOWPNX4ymMk6DlO4kfeWddWaLVOTQ59?usp=sharing',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PERPUSTAKAAN',
                'judul_informasi' => 'Repository Institusi & Publikasi Karya Ilmiah Civitas PKTJ',
                'isi_informasi' => 'Pangkalan data digital e-prints yang memuat metadata karya ilmiah, laporan magang, skripsi, dan publikasi penelitian sivitas akademika PKTJ.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Perpustakaan PKTJ',
                'penerbit_informasi' => 'Unit Perpustakaan PKTJ',
                'bentuk_informasi' => 'Sistem Informasi Web (E-Prints)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Permanen',
                'file_informasi' => 'http://eprints.pktj.ac.id/',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'AKADEMIK & PRODI',
                'judul_informasi' => 'Profil Program Studi Sarjana Terapan Teknologi Rekayasa Otomotif (TRO)',
                'isi_informasi' => 'Informasi profil resmi Prodi TRO PKTJ memuat kurikulum pembelajaran, fasilitas laboratorium, kualifikasi dosen pengajar, dan kompetensi lulusan.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Program Studi D-IV TRO',
                'penerbit_informasi' => 'Program Studi D-IV TRO',
                'bentuk_informasi' => 'Portal Informasi Web',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '3 Tahun',
                'file_informasi' => 'https://tinyurl.com/webtro',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'AKADEMIK & PRODI',
                'judul_informasi' => 'Profil Program Studi Diploma III Teknologi Otomotif (TO) PKTJ',
                'isi_informasi' => 'Informasi profil program studi Diploma III Teknologi Otomotif PKTJ mengenai visi keilmuan, profil lulusan, dan capaian pembelajaran.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Program Studi D-III TO',
                'penerbit_informasi' => 'Program Studi D-III TO',
                'bentuk_informasi' => 'Portal Informasi Web',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '3 Tahun',
                'file_informasi' => 'https://pktj.ac.id/program-studi/27-diii-teknolgi-otomotif',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'AKADEMIK & PRODI',
                'judul_informasi' => 'Berita Acara Pelaksanaan Ujian (UTS & UAS) Program Studi TRO PKTJ',
                'isi_informasi' => 'Dokumen rekapitulasi berita acara penyelenggaraan Ujian Tengah Semester (UTS) dan Ujian Akhir Semester (UAS) pada Program Studi TRO.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Program Studi D-IV TRO',
                'penerbit_informasi' => 'Program Studi D-IV TRO',
                'bentuk_informasi' => 'Softcopy (Google Drive)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '2 Tahun',
                'file_informasi' => 'https://tinyurl.com/BA-UTS-GANJIL-25-26',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'AKADEMIK & PRODI',
                'judul_informasi' => 'Rekapitulasi Pelaksanaan Seminar Proposal Tugas Akhir Prodi TRO',
                'isi_informasi' => 'Daftar jadwal dan rekapitulasi pelaksanaan seminar proposal tugas akhir / skripsi terapan bagi taruna tingkat akhir Prodi TRO.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Program Studi D-IV TRO',
                'penerbit_informasi' => 'Program Studi D-IV TRO',
                'bentuk_informasi' => 'Softcopy (Google Drive)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '2 Tahun',
                'file_informasi' => 'https://tinyurl.com/DaftarProposalTRO2526',
                'aktif' => 1,
            ],

            // DATA POLTRADA TANPA LINK DOKUMEN (AKTIF = 0 / DRAFT / TERSIMPAN DI ADMIN)
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'judul_informasi' => 'Rencana Strategis (Renstra) PKTJ Tegal 2020–2024',
                'isi_informasi' => 'Dokumen Rencana Strategis (Renstra) PKTJ Tegal periode 2020–2024',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2020',
                'jangka_waktu' => '5 Tahun',
                'file_informasi' => null,
                'aktif' => 0,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'judul_informasi' => 'Rencana Kerja Tahunan (RKT) PKTJ Tegal',
                'isi_informasi' => 'Dokumen program kerja tahunan dan sasaran operasional PKTJ Tegal',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => null,
                'aktif' => 0,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'PROGRAM DAN KEGIATAN',
                'judul_informasi' => 'Kalender Akademik & Jadwal Perkuliahan / Diklat PKTJ',
                'isi_informasi' => 'Informasi kalender akademik perkuliahan dan penyelenggaraan diklat transportasi jalan',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Administrasi Akademik dan Ketarunaan',
                'penerbit_informasi' => 'Bagian Administrasi Akademik dan Ketarunaan',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => null,
                'aktif' => 0,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'KINERJA DAN KEUANGAN',
                'judul_informasi' => 'Rencana Kerja dan Anggaran K/L (RKA-KL) PKTJ',
                'isi_informasi' => 'Alokasi anggaran belanja program dan kegiatan operasional PKTJ',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => null,
                'aktif' => 0,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'KINERJA DAN KEUANGAN',
                'judul_informasi' => 'Daftar Isian Pelaksanaan Anggaran (DIPA) Induk PKTJ',
                'isi_informasi' => 'Dokumen pelaksanaan anggaran satuan kerja PKTJ Tegal',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => null,
                'aktif' => 0,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'KINERJA DAN KEUANGAN',
                'judul_informasi' => 'Perjanjian Kinerja (PK) PKTJ Tegal',
                'isi_informasi' => 'Komitmen target kinerja pimpinan unit kerja PKTJ dengan BPSDMP',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => null,
                'aktif' => 0,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'KINERJA DAN KEUANGAN',
                'judul_informasi' => 'Laporan Akuntabilitas Kinerja Instansi Pemerintah (LAKIP / LKjIP) PKTJ',
                'isi_informasi' => 'Laporan pertanggungjawaban capaian kinerja tahunan kelembagaan PKTJ',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => null,
                'aktif' => 0,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'KINERJA DAN KEUANGAN',
                'judul_informasi' => 'Laporan Tahunan PKTJ Tegal',
                'isi_informasi' => 'Kompilasi laporan tahunan penyelenggaraan tri dharma perguruan tinggi vokasi',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => null,
                'aktif' => 0,
            ],
            [
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'KINERJA DAN KEUANGAN',
                'judul_informasi' => 'Laporan Keuangan Audited BPK-RI PKTJ',
                'isi_informasi' => 'Laporan keuangan satuan kerja PKTJ Tegal audited',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => null,
                'aktif' => 0,
            ],
        ];

        // =========================================================================
        // 3. DATA INFORMASI SETIAP SAAT
        // =========================================================================
        $setiapSaatItems = [
            // MEMILIKI LINK RIIL (AKTIF = 1)
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'PROSEDUR PPID',
                'judul_informasi' => 'SOP Layanan Informasi Publik PPID',
                'isi_informasi' => 'Standar Operasional Prosedur penatausahaan pelayanan informasi publik dan uji konsekuensi',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penerbit_informasi' => 'PPID Pelaksana UPT PKTJ Tegal',
                'bentuk_informasi' => 'Cetak & Online',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => '/prosedur/permintaan-informasi',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'KEGIATAN PIMPINAN',
                'judul_informasi' => 'Dokumentasi & Kegiatan Pimpinan PKTJ',
                'isi_informasi' => 'Dokumentasi foto dan publikasi kegiatan kedinasan Direktur PKTJ',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Tim Humas & Publikasi PKTJ',
                'penerbit_informasi' => 'Tim Humas & Publikasi PKTJ',
                'bentuk_informasi' => 'Online',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => '/profil-ppid',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'PENGAWASAN INTERNAL',
                'judul_informasi' => 'Standar Operasional Prosedur (SOP) Satuan Pengawas Internal (SPI) PKTJ',
                'isi_informasi' => 'Standar Operasional Prosedur mengenai tata kelola pengawasan, audit kepatuhan, dan reviu internal di lingkungan PKTJ Tegal.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Satuan Pengawas Internal (SPI)',
                'penerbit_informasi' => 'Satuan Pengawas Internal (SPI)',
                'bentuk_informasi' => 'Softcopy (Google Drive)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '5 Tahun',
                'file_informasi' => 'https://drive.google.com/drive/folders/1tLf20PZTw1cHyw71MvI-okt9djAQCuD3?usp=drive_link',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'PENGAWASAN INTERNAL',
                'judul_informasi' => 'Piagam Satuan Pengawas Internal (SPI Charter) PKTJ',
                'isi_informasi' => 'Piagam formal komitmen pimpinan terkait kedudukan, wewenang, ruang lingkup, dan independensi Satuan Pengawas Internal (SPI) PKTJ.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Satuan Pengawas Internal (SPI)',
                'penerbit_informasi' => 'Satuan Pengawas Internal (SPI)',
                'bentuk_informasi' => 'Softcopy (PDF)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Permanen',
                'file_informasi' => 'https://drive.google.com/file/d/1eCpVTnOJ4bE4wdRZ0KQOd_YQcF3UN0Iy/view?usp=drive_link',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'PENELITIAN & PENGABDIAN',
                'judul_informasi' => 'Pedoman Pelaksanaan Penelitian dan Pengabdian Kepada Masyarakat PKTJ',
                'isi_informasi' => 'Panduan resmi mengenai ketentuan, sistematika usulan proposal, dan tata cara pelaksanaan penelitian serta pengabdian masyarakat dosen dan taruna.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Pusat Penelitian dan Pengabdian Masyarakat (PPPM)',
                'penerbit_informasi' => 'Pusat Penelitian dan Pengabdian Masyarakat (PPPM)',
                'bentuk_informasi' => 'Softcopy (PDF)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '5 Tahun',
                'file_informasi' => 'https://drive.google.com/file/d/1LPKPUO7i24y5nU6_CNppSlLfjOfQNm5-/view?usp=drive_link',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'PENGELOLAAN BMN',
                'judul_informasi' => 'Dokumen Penghapusan Barang Milik Negara (BMN) PKTJ Tahun 2025',
                'isi_informasi' => 'Surat Keputusan dan berita acara pelaksanaan penghapusan aset Barang Milik Negara (BMN) yang telah memenuhi syarat ketentuan perundang-undangan.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'Softcopy (Google Drive)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '10 Tahun',
                'file_informasi' => 'https://drive.google.com/drive/folders/19LTo-mY6g6YApou8fIuUAvid5c4I-SXk?usp=drive_link',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'TATA KELOLA KEARSIPAN',
                'judul_informasi' => 'Daftar Arsip Aktif Politeknik Keselamatan Transportasi Jalan Tahun 2025',
                'isi_informasi' => 'Daftar penataan berkas arsip dinas aktif yang telah dikelompokkan berdasarkan klasifikasi permasalahan kearsipan di lingkungan PKTJ.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'Softcopy (PDF)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '5 Tahun',
                'file_informasi' => 'https://drive.google.com/file/d/1KiY0ogEJjtTPxpIKo4ivR3bFM4C0mTGp/view?usp=drive_link',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'LABORATORIUM & PRAKTIKUM',
                'judul_informasi' => 'Standar Operasional Prosedur (SOP) Laboratorium Terpadu PKTJ',
                'isi_informasi' => 'Kumpulan Standar Operasional Prosedur pelaksanaan praktikum, penggunaan instrumen uji, dan keselamatan kerja di laboratorium PKTJ.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Laboratorium PKTJ',
                'penerbit_informasi' => 'Unit Laboratorium PKTJ',
                'bentuk_informasi' => 'Softcopy (Google Drive)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '5 Tahun',
                'file_informasi' => 'https://drive.google.com/drive/folders/1K1blB5-7OzEGhrLgWPjW1bsRfcL3kC-b?usp=drive_link',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'KERJASAMA & KEMITRAAN',
                'judul_informasi' => 'Perjanjian Kerja Sama Kemitraan IIEF dan PKTJ (Tes TOEFL ITP)',
                'isi_informasi' => 'Naskah Perjanjian Kerja Sama kemitraan antara Indonesian International Education Foundation (IIEF) dan PKTJ terkait penyelenggaraan tes resmi TOEFL ITP.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Bahasa PKTJ',
                'penerbit_informasi' => 'Unit Bahasa PKTJ',
                'bentuk_informasi' => 'Softcopy (Google Drive)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Masa Berlaku PKS',
                'file_informasi' => 'https://drive.google.com/drive/u/1/folders/1MfhK-FPxNBLlTEss5_5xgde8hOJILdLT',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'KERJASAMA & KEMITRAAN',
                'judul_informasi' => 'Perjanjian Kerja Sama Kemitraan Dejavato Foundation dan PKTJ (Volunteer Asing)',
                'isi_informasi' => 'Naskah Perjanjian Kerja Sama PKTJ dengan Dejavato Foundation mengenai program pendampingan volunteer asing untuk peningkatan kompetensi bahasa internasional.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Bahasa PKTJ',
                'penerbit_informasi' => 'Unit Bahasa PKTJ',
                'bentuk_informasi' => 'Softcopy (Google Drive)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Masa Berlaku PKS',
                'file_informasi' => 'https://drive.google.com/drive/u/1/folders/1MfhK-FPxNBLlTEss5_5xgde8hOJILdLT',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'UNIT BAHASA',
                'judul_informasi' => 'Standar Operasional Prosedur (SOP) Pelayanan Unit Bahasa PKTJ',
                'isi_informasi' => 'Standar Operasional Prosedur mengenai alur pelayanan pembelajaran bahasa, tes kemampuan bahasa Inggris (EPT), dan sertifikasi bahasa di Unit Bahasa PKTJ.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Bahasa PKTJ',
                'penerbit_informasi' => 'Unit Bahasa PKTJ',
                'bentuk_informasi' => 'Softcopy (Google Drive)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '5 Tahun',
                'file_informasi' => 'https://drive.google.com/drive/u/1/folders/1MfhK-FPxNBLlTEss5_5xgde8hOJILdLT',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'UNIT TEKNOLOGI INFORMASI',
                'judul_informasi' => 'Standar Operasional Prosedur (SOP) Unit Teknologi Informasi PKTJ',
                'isi_informasi' => 'Kumpulan SOP bidang TI meliputi pengelolaan webservice, pemeliharaan website, sistem informasi akademik, dan dukungan infrastruktur digital PKTJ.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Teknologi Informasi',
                'penerbit_informasi' => 'Unit Teknologi Informasi',
                'bentuk_informasi' => 'Softcopy (Google Drive)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '5 Tahun',
                'file_informasi' => 'https://drive.google.com/drive/folders/1vNUncJeSbXVTzRsn3Vx727xo5yxNo26F?usp=drive_link',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'PENGEMBANGAN USAHA',
                'judul_informasi' => 'Surat Keputusan Tim Pelaksana Studi Kelayakan Terminal / Shelter Karanggede',
                'isi_informasi' => 'Keputusan Direktur PKTJ Nomor KP-PKTJ 305 mengenai penetapan Tim Pelaksana Kegiatan Studi Kelayakan Teknis Terminal dan Shelter Kecamatan Karanggede.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Pengembangan Usaha (UPU)',
                'penerbit_informasi' => 'Unit Pengembangan Usaha (UPU)',
                'bentuk_informasi' => 'Softcopy (PDF)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '5 Tahun',
                'file_informasi' => 'https://drive.google.com/file/d/1Y9V16YqYooOSkqDZ2RhuDwRceLo39PJ-/view?usp=drivesdk',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'PENGEMBANGAN USAHA',
                'judul_informasi' => 'Surat Keputusan Tim Pelaksana Studi Kelayakan Terminal / Shelter Mojosongo',
                'isi_informasi' => 'Keputusan Direktur PKTJ Nomor KP-PKTJ 304 tentang penetapan Tim Pelaksana Studi Kelayakan Teknis Terminal dan Shelter Angkutan Umum Kecamatan Mojosongo.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Pengembangan Usaha (UPU)',
                'penerbit_informasi' => 'Unit Pengembangan Usaha (UPU)',
                'bentuk_informasi' => 'Softcopy (PDF)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '5 Tahun',
                'file_informasi' => 'https://drive.google.com/file/d/1Y7rGK62Oo2gxmPs7_FEkrwz_mjRhf2TM/view?usp=drivesdk',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'PERPUSTAKAAN',
                'judul_informasi' => 'Tata Tertib & Ketentuan Layanan Pemustaka Perpustakaan PKTJ',
                'isi_informasi' => 'Ketentuan tata tertib, etika berkunjung, hak dan kewajiban pemustaka, serta sanksi keterlambatan pengembalian buku di Perpustakaan PKTJ.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Perpustakaan PKTJ',
                'penerbit_informasi' => 'Unit Perpustakaan PKTJ',
                'bentuk_informasi' => 'Portal Informasi Web',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '3 Tahun',
                'file_informasi' => 'https://library.pktj.ac.id/tata-tertib-2/',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'PERPUSTAKAAN',
                'judul_informasi' => 'Standar Operasional Prosedur (SOP) Layanan Sirkulasi Perpustakaan PKTJ',
                'isi_informasi' => 'Prosedur baku pelayanan jasa peminjaman, perpanjangan, dan pengembalian bahan pustaka bagi seluruh civitas akademika PKTJ.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Perpustakaan PKTJ',
                'penerbit_informasi' => 'Unit Perpustakaan PKTJ',
                'bentuk_informasi' => 'Softcopy (PDF)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '5 Tahun',
                'file_informasi' => 'https://drive.google.com/file/d/1Eywr9Rv4kOmBB4Hedjv6WOK38LvLh88I/view?usp=sharing',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'PERPUSTAKAAN',
                'judul_informasi' => 'Standar Operasional Prosedur (SOP) Penerbitan Surat Keterangan Bebas Pustaka',
                'isi_informasi' => 'Alur dan persyaratan administrasi pengurusan surat keterangan bebas pustaka sebagai salah satu syarat yudisium dan kelulusan taruna PKTJ.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Perpustakaan PKTJ',
                'penerbit_informasi' => 'Unit Perpustakaan PKTJ',
                'bentuk_informasi' => 'Softcopy (PDF)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '5 Tahun',
                'file_informasi' => 'https://drive.google.com/file/d/1o5doGRosopf4UKf-eWf2Xx8_DT6fmE2p/view?usp=sharing',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'PERPUSTAKAAN',
                'judul_informasi' => 'Standar Operasional Prosedur (SOP) Usulan Pengadaan Bahan Pustaka PKTJ',
                'isi_informasi' => 'Tata cara dan tahapan pengusulan penambahan buku referensi atau bahan pustaka baru oleh dosen, taruna, dan pengelola perpustakaan.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Perpustakaan PKTJ',
                'penerbit_informasi' => 'Unit Perpustakaan PKTJ',
                'bentuk_informasi' => 'Softcopy (PDF)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '5 Tahun',
                'file_informasi' => 'https://drive.google.com/file/d/145s563VEfXPpC4Ci90xk_f9A_wh_q179/view?usp=sharing',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'PERPUSTAKAAN',
                'judul_informasi' => 'Katalog Induk Buku Online (OPAC Perpustakaan PKTJ)',
                'isi_informasi' => 'Sistem katalog daring interaktif Online Public Access Catalog (OPAC) untuk penelusuran lokasi dan ketersediaan koleksi literatur fisik di PKTJ.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Perpustakaan PKTJ',
                'penerbit_informasi' => 'Unit Perpustakaan PKTJ',
                'bentuk_informasi' => 'Sistem Informasi Web (OPAC)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Permanen',
                'file_informasi' => 'https://opac.pktj.ac.id/',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'PENGADAAN BARANG DAN JASA',
                'judul_informasi' => 'Rencana Umum Pengadaan (RUP) Barang dan Jasa PKTJ Tahun Anggaran 2025',
                'isi_informasi' => 'Dokumen resmi Rencana Umum Pengadaan (RUP) barang dan jasa pemerintah di lingkungan PKTJ Tegal untuk Tahun Anggaran 2025.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Pejabat Pembuat Komitmen (PPK)',
                'penerbit_informasi' => 'Pejabat Pembuat Komitmen (PPK)',
                'bentuk_informasi' => 'Softcopy (PDF)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '5 Tahun',
                'file_informasi' => 'https://drive.google.com/file/d/1NhbltcjhBPTdK7JgDepqbFbQ2ELHfdVx/view?usp=drive_link',
                'aktif' => 1,
            ],

            // TANPA LINK (AKTIF = 0 / DRAFT / TERSIMPAN DI ADMIN)
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'DOKUMEN PPID',
                'judul_informasi' => 'Daftar Informasi Publik (DIP) PKTJ',
                'isi_informasi' => 'Dokumen penetapan Daftar Informasi Publik (DIP) yang wajib disediakan',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Seluruh Unit Kerja PKTJ',
                'penerbit_informasi' => 'Seluruh Unit Kerja PKTJ',
                'bentuk_informasi' => 'Cetak & Online',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Hingga Pemutakhiran',
                'file_informasi' => null,
                'aktif' => 0,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'TATA USAHA',
                'judul_informasi' => 'Surat Menyurat & Registrasi Naskah Dinas',
                'isi_informasi' => 'Informasi buku register persuratan naskah dinas masuk dan keluar resmi',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Subbagian Tata Usaha & Rumah Tangga',
                'penerbit_informasi' => 'Subbagian Tata Usaha & Rumah Tangga',
                'bentuk_informasi' => 'Cetak & Online',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => null,
                'aktif' => 0,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'BARANG MILIK NEGARA',
                'judul_informasi' => 'Data Inventaris Barang Milik Negara (BMN) PKTJ',
                'isi_informasi' => 'Laporan penatausahaan dan inventarisasi Barang Milik Negara (BMN)',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => null,
                'aktif' => 0,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'PENJAMINAN MUTU',
                'judul_informasi' => 'Pedoman Sistem Penjaminan Mutu Internal (SPMI) PKTJ',
                'isi_informasi' => 'Dokumen kebijakan mutu, manual mutu, dan standar audit internal PKTJ',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Pusat Pengembangan Pembelajaran & SPMI (P4MP)',
                'penerbit_informasi' => 'Pusat Pengembangan Pembelajaran & SPMI (P4MP)',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Sesuai Retensi Arsip',
                'file_informasi' => null,
                'aktif' => 0,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'AKADEMIK',
                'judul_informasi' => 'Kurikulum & Silabus Program Studi PKTJ',
                'isi_informasi' => 'Struktur kurikulum, mata kuliah, capaian pembelajaran, dan silabus program studi PKTJ',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Administrasi Akademik dan Ketarunaan',
                'penerbit_informasi' => 'Bagian Administrasi Akademik dan Ketarunaan',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '5 Tahun',
                'file_informasi' => null,
                'aktif' => 0,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'HUKUM & REGULASI',
                'judul_informasi' => 'Himpunan Peraturan & Kebijakan Direktur PKTJ',
                'isi_informasi' => 'Kompilasi Surat Keputusan dan Surat Edaran Direktur PKTJ yang masih berlaku',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Subbagian Tata Usaha & Rumah Tangga',
                'penerbit_informasi' => 'Subbagian Tata Usaha & Rumah Tangga',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama Berlaku',
                'file_informasi' => null,
                'aktif' => 0,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'SARANA & PRASARANA',
                'judul_informasi' => 'Data Inventaris Kendaraan Dinas & Sarana Transportasi PKTJ',
                'isi_informasi' => 'Daftar inventarisasi kendaraan operasional kedinasan dan sarana transportasi kampus',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Subbagian Tata Usaha & Rumah Tangga',
                'penerbit_informasi' => 'Subbagian Tata Usaha & Rumah Tangga',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => null,
                'aktif' => 0,
            ],
            [
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'SARANA & PRASARANA',
                'judul_informasi' => 'Data Fasilitas & Sarana Laboratorium PKTJ',
                'isi_informasi' => 'Daftar fasilitas peralatan pengujian kendaraan bermotor dan keselamatan transportasi',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Laboratorium PKTJ',
                'penerbit_informasi' => 'Unit Laboratorium PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => null,
                'aktif' => 0,
            ],
        ];

        // =========================================================================
        // 4. DATA INFORMASI SERTA MERTA
        // =========================================================================
        $sertaMertaItems = [
            // MEMILIKI LINK RIIL (AKTIF = 1)
            [
                'kategori' => 'informasi-serta-merta',
                'tipe_informasi' => 'KERJASAMA / MOU',
                'judul_informasi' => 'Daftar Dokumen Kerja Sama & Nota Kesepahaman (MoU) Perpustakaan PKTJ (Tersensor)',
                'isi_informasi' => 'Daftar dokumen naskah nota kesepahaman (MoU) dan perjanjian kerja sama perpustakaan dengan perguruan tinggi dan instansi mitra yang telah disesuaikan dan disensor sesuai ketentuan perlindungan rahasia dagang UU KIP.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Unit Perpustakaan PKTJ',
                'penerbit_informasi' => 'Unit Perpustakaan PKTJ',
                'bentuk_informasi' => 'Softcopy (Google Drive)',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Masa Berlaku Dokumen',
                'file_informasi' => 'https://drive.google.com/drive/folders/1ziMT2t4wxGFhUkNaDOmYByOYVG3lvKlp?usp=sharing',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-serta-merta',
                'tipe_informasi' => 'SIPENCATAR',
                'judul_informasi' => 'Pengumuman Kelulusan Seleksi Penerimaan Calon Taruna (SIPENCATAR) PKTJ',
                'isi_informasi' => 'Informasi penting dan serta merta mengenai kelulusan tahapan seleksi penerimaan calon taruna/taruni baru pola pembibitan dan mandiri PKTJ.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Panitia Penerimaan Calon Taruna (SIPENCATAR)',
                'penerbit_informasi' => 'Panitia Penerimaan Calon Taruna (SIPENCATAR)',
                'bentuk_informasi' => 'Portal Informasi Web',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 Tahun',
                'file_informasi' => 'https://sipencatar.dephub.go.id/',
                'aktif' => 1,
            ],
            [
                'kategori' => 'informasi-serta-merta',
                'tipe_informasi' => 'KESELAMATAN & DARURAT',
                'judul_informasi' => 'Peringatan Dini & Prosedur Tanggap Darurat Keselamatan Sivitas PKTJ',
                'isi_informasi' => 'Pedoman evakuasi cepat dan tanggap darurat bencana, kebakaran, serta peringatan keselamatan lingkungan di area kampus PKTJ.',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Bagian Keuangan dan Umum',
                'penerbit_informasi' => 'Bagian Keuangan dan Umum',
                'bentuk_informasi' => 'Softcopy & Prosedur Resmi',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Permanen',
                'file_informasi' => '/prosedur/permintaan-informasi',
                'aktif' => 1,
            ],

            // TANPA LINK (AKTIF = 0 / DRAFT / TERSIMPAN DI ADMIN)
            [
                'kategori' => 'informasi-serta-merta',
                'tipe_informasi' => 'LAYANAN DARURAT',
                'judul_informasi' => 'Penutupan Layanan Publik / Sarana Prasarana Akibat Keadaan Darurat',
                'isi_informasi' => 'Pengumuman resmi mengenai penutupan sementara fasilitas atau layanan kampus PKTJ',
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => 'Seluruh Unit Kerja PKTJ',
                'penerbit_informasi' => 'Seluruh Unit Kerja PKTJ',
                'bentuk_informasi' => 'Cetak & Online',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Insidental',
                'file_informasi' => null,
                'aktif' => 0,
            ],
        ];

        // =========================================================================
        // 5. DATA INFORMASI DIKECUALIKAN
        // =========================================================================
        $dikecualikanItems = [
            [
                'judul' => 'Keputusan Penetapan Daftar Informasi Yang Dikecualikan (DIK) Kementerian Perhubungan Tahun 2026',
                'deskripsi' => 'Surat Keputusan mengenai penetapan daftar klasifikasi informasi yang dikecualikan di lingkungan Kementerian Perhubungan berdasarkan pengujian konsekuensi.',
                'file_path' => 'https://drive.google.com/file/d/1r-Tkqfo_pgXCJ9UXBzSWNcMlJViTu-jk/view?usp=drive_link',
                'penanggung_jawab' => 'PPID Kementerian Perhubungan',
                'dasar_hukum' => 'UU No. 14 Tahun 2008 Pasal 17',
                'waktu_pembuatan' => '2026',
                'jangka_waktu' => '10 Tahun',
                'aktif' => 1
            ],
            [
                'judul' => 'Program Kerja Pengawasan Tahunan Satuan Pengawas Internal (SPI) PKTJ',
                'deskripsi' => 'Rencana tahunan obyek dan jadwal audit pengawasan internal yang dikecualikan agar tidak menghambat efektivitas pengawasan sebagaimana Pasal 17 huruf a UU KIP.',
                'file_path' => 'https://drive.google.com/file/d/12qg8MgbDXFxbrxDwmnioxxs0lIBqX8jv/view?usp=drive_link',
                'penanggung_jawab' => 'Satuan Pengawas Internal (SPI)',
                'dasar_hukum' => 'UU No. 14 Tahun 2008 Pasal 17 huruf a',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '5 Tahun',
                'aktif' => 1
            ],
            [
                'judul' => 'Laporan Hasil Audit Mutu Internal (AMI) PKTJ Tahun 2025',
                'deskripsi' => 'Temuan rincian audit mutu internal antar unit kerja yang masih dalam proses pemenuhan tindakan perbaikan (Pasal 17 huruf a UU KIP).',
                'file_path' => 'https://drive.google.com/file/d/1gmr-SXPV7mXjap_X-dsMEbvXuHAGkkcs/view?usp=drive_link',
                'penanggung_jawab' => 'Satuan Penjaminan Mutu (SPM)',
                'dasar_hukum' => 'UU No. 14 Tahun 2008 Pasal 17 huruf a',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '5 Tahun',
                'aktif' => 1
            ],
            [
                'judul' => 'Risalah & Notulen Rapat Tinjauan Manajemen (RTM) PKTJ Tahun 2025',
                'deskripsi' => 'Catatan evaluasi internal dan penilaian kinerja personal unit kerja yang bersifat rahasia dalam Rapat Tinjauan Manajemen.',
                'file_path' => 'https://drive.google.com/file/d/13oHGQ9ZkUlbvF1CYdoAqTHvJ4ZfVpHiU/view?usp=drive_link',
                'penanggung_jawab' => 'Satuan Penjaminan Mutu (SPM)',
                'dasar_hukum' => 'UU No. 14 Tahun 2008 Pasal 17 huruf a',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '5 Tahun',
                'aktif' => 1
            ],
            [
                'judul' => 'Data Rekapitulasi Taruna Aktif PKTJ Semester Ganjil T.A 2025/2026',
                'deskripsi' => 'Data induk taruna aktif yang memuat identitas pribadi dan rekam akademik taruna (Pasal 17 huruf h UU KIP - data pribadi).',
                'file_path' => 'https://drive.google.com/file/d/1sLjIOb0ApA-Te8w_9NIOetr_eq1Srm3B/view?usp=sharing',
                'penanggung_jawab' => 'Bagian Administrasi Akademik dan Ketarunaan',
                'dasar_hukum' => 'UU No. 14 Tahun 2008 Pasal 17 huruf h',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '5 Tahun',
                'aktif' => 1
            ],
            [
                'judul' => 'Laporan Pemeriksaan Kesehatan (MCU) Siswa Diklat SPAU PKTJ Tahun 2025',
                'deskripsi' => 'Dokumen hasil medical check up peserta diklat yang memuat data rekam medis pribadi (Pasal 17 huruf h UU KIP).',
                'file_path' => 'https://drive.google.com/drive/folders/1jymT80VdcTYPMerZC9zYiXZ5oGFdROhl?usp=drive_link',
                'penanggung_jawab' => 'Unit Kesehatan PKTJ',
                'dasar_hukum' => 'UU No. 14 Tahun 2008 Pasal 17 huruf h',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '10 Tahun',
                'aktif' => 1
            ],
            [
                'judul' => 'Laporan Hasil Pengujian English Proficiency Test (EPT) Taruna Tingkat Akhir',
                'deskripsi' => 'Rekapitulasi skor perolehan uji kemahiran bahasa inggris individual taruna (Pasal 17 huruf h angka 4 UU KIP).',
                'file_path' => 'https://drive.google.com/drive/u/1/folders/1MfhK-FPxNBLlTEss5_5xgde8hOJILdLT',
                'penanggung_jawab' => 'Unit Bahasa PKTJ',
                'dasar_hukum' => 'UU No. 14 Tahun 2008 Pasal 17 huruf h',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '5 Tahun',
                'aktif' => 1
            ],
            [
                'judul' => 'Rekapitulasi Pengelolaan & Pemantauan CCTV Kampus PKTJ',
                'deskripsi' => 'Informasi teknis titik lokasi kamera dan topologi pemantauan CCTV area kampus yang dikecualikan demi keamanan sarana prasarana vital.',
                'file_path' => 'https://drive.google.com/file/d/14iCZMBIjIiVq0CcxkfwxSHgE3oNlJHnM/view?usp=drive_link',
                'penanggung_jawab' => 'Unit Teknologi Informasi',
                'dasar_hukum' => 'UU No. 14 Tahun 2008 Pasal 17 huruf a',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '3 Tahun',
                'aktif' => 1
            ],
            [
                'judul' => 'Daftar Arsitektur Aplikasi Internal & Monitoring Aksesibilitas Sistem IT PKTJ',
                'deskripsi' => 'Daftar konfigurasi arsitektur sistem informasi internal dan celah pemantauan aksesibilitas yang dikecualikan guna proteksi keamanan siber institusi.',
                'file_path' => 'https://drive.google.com/file/d/1Pb9fEml80Trs2bz2uawPVMlDu51zSV0c/view?usp=drive_link',
                'penanggung_jawab' => 'Unit Teknologi Informasi',
                'dasar_hukum' => 'UU No. 14 Tahun 2008 Pasal 17 huruf a',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '3 Tahun',
                'aktif' => 1
            ],
            [
                'judul' => 'Rekapitulasi Penanganan Keluhan Sarana Prasarana Asrama Taruna PKTJ',
                'deskripsi' => 'Catatan identitas taruna pelapor dan tindak lanjut keluhan fasilitas hunian asrama yang memuat data pribadi pelapor.',
                'file_path' => 'https://drive.google.com/drive/folders/1j5lC-salWAeDNZ_g4pUPEqgpNoKSv90J',
                'penanggung_jawab' => 'Unit Asrama dan Fasilitas Taruna',
                'dasar_hukum' => 'UU No. 14 Tahun 2008 Pasal 17 huruf h',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '2 Tahun',
                'aktif' => 1
            ],
            [
                'judul' => 'Rekapitulasi Perjanjian Sewa Pemanfaatan Aset Sarana & Prasarana PKTJ',
                'deskripsi' => 'Daftar data penyewa pihak ketiga perorangan yang memuat informasi identitas kependudukan privat (Pasal 18 ayat 2 UU KIP).',
                'file_path' => 'https://docs.google.com/spreadsheets/d/1hYdbaLljh5G0OzsNXHwgF78e5aYUONs3Ni5TMnBg1vM/edit?usp=drivesdk',
                'penanggung_jawab' => 'Unit Pengembangan Usaha (UPU)',
                'dasar_hukum' => 'UU No. 14 Tahun 2008 Pasal 18 ayat 2',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '5 Tahun',
                'aktif' => 1
            ],
        ];

        // =========================================================================
        // 6. PROSES INSERT / UPDATE DATABASE SECARA AMAN & TEPAT
        // =========================================================================
        $allItems = array_merge($berkalaItems, $setiapSaatItems, $sertaMertaItems);

        foreach ($allItems as $it) {
            // Evaluasi status aktif: aktif=1 HANYA jika memiliki file/link yang valid
            $hasValidLink = !empty($it['file_informasi']) && !in_array(trim($it['file_informasi']), ['#', '-', 'null', 'none', '', '/layanan-informasi/daftar']);
            $isAktif = $hasValidLink ? ($it['aktif'] ?? 1) : 0;

            $existing = DB::table('daftar_informasis')
                ->where('judul_informasi', $it['judul_informasi'])
                ->first();

            $dataToSave = [
                'kategori' => $it['kategori'],
                'tipe_informasi' => $it['sub_kategori'] ?? $it['tipe_informasi'],
                'judul_informasi' => $it['judul_informasi'],
                'isi_informasi' => $it['isi_informasi'],
                'pejabat_penguasa' => $it['pejabat_penguasa'],
                'penanggung_jawab' => $it['penanggung_jawab'],
                'penerbit_informasi' => $it['penerbit_informasi'],
                'bentuk_informasi' => $it['bentuk_informasi'],
                'tempat_pembuatan' => $it['tempat_pembuatan'],
                'waktu_pembuatan' => $it['waktu_pembuatan'],
                'jangka_waktu' => $it['jangka_waktu'],
                'file_informasi' => $it['file_informasi'],
                'aktif' => $isAktif,
                'bisa_download' => $hasValidLink ? 1 : 0,
                'is_blurred' => 0,
                'updated_at' => now(),
            ];

            if ($existing) {
                DB::table('daftar_informasis')->where('id', $existing->id)->update($dataToSave);
            } else {
                $dataToSave['created_at'] = now();
                DB::table('daftar_informasis')->insert($dataToSave);
            }

            // Simpan juga ke tabel model spesifik masing-masing
            if ($it['kategori'] === 'informasi-berkala' && DB::getSchemaBuilder()->hasTable('informasi_berkalas')) {
                $m = DB::table('informasi_berkalas')->where('judul', $it['judul_informasi'])->first();
                $mData = [
                    'judul' => $it['judul_informasi'],
                    'deskripsi' => $it['isi_informasi'],
                    'file_path' => $it['file_informasi'],
                    'aktif' => $isAktif,
                    'is_blurred' => 0,
                    'bisa_download' => $hasValidLink ? 1 : 0,
                    'tanggal' => date('Y-m-d'),
                    'updated_at' => now(),
                ];
                if ($m) {
                    DB::table('informasi_berkalas')->where('id', $m->id)->update($mData);
                } else {
                    $mData['created_at'] = now();
                    DB::table('informasi_berkalas')->insert($mData);
                }
            } elseif (in_array($it['kategori'], ['informasi-setiap-saat', 'informasi-setiapsaat']) && DB::getSchemaBuilder()->hasTable('informasi_setiapsaats')) {
                $m = DB::table('informasi_setiapsaats')->where('judul', $it['judul_informasi'])->first();
                $mData = [
                    'judul' => $it['judul_informasi'],
                    'deskripsi' => $it['isi_informasi'],
                    'file_path' => $it['file_informasi'],
                    'aktif' => $isAktif,
                    'is_blurred' => 0,
                    'bisa_download' => $hasValidLink ? 1 : 0,
                    'tanggal' => date('Y-m-d'),
                    'updated_at' => now(),
                ];
                if ($m) {
                    DB::table('informasi_setiapsaats')->where('id', $m->id)->update($mData);
                } else {
                    $mData['created_at'] = now();
                    DB::table('informasi_setiapsaats')->insert($mData);
                }
            } elseif (in_array($it['kategori'], ['informasi-serta-merta', 'informasi-sertamerta']) && DB::getSchemaBuilder()->hasTable('informasi_sertamertas')) {
                $m = DB::table('informasi_sertamertas')->where('judul', $it['judul_informasi'])->first();
                $mData = [
                    'judul' => $it['judul_informasi'],
                    'deskripsi' => $it['isi_informasi'],
                    'file_path' => $it['file_informasi'],
                    'aktif' => $isAktif,
                    'is_blurred' => 0,
                    'bisa_download' => $hasValidLink ? 1 : 0,
                    'tanggal' => date('Y-m-d'),
                    'updated_at' => now(),
                ];
                if ($m) {
                    DB::table('informasi_sertamertas')->where('id', $m->id)->update($mData);
                } else {
                    $mData['created_at'] = now();
                    DB::table('informasi_sertamertas')->insert($mData);
                }
            }
        }

        // Simpan Informasi Dikecualikan
        foreach ($dikecualikanItems as $dik) {
            $existing = DB::table('daftar_informasis')
                ->where('judul_informasi', $dik['judul'])
                ->first();

            $dataDaftar = [
                'kategori' => 'informasi-dikecualikan',
                'tipe_informasi' => 'DIKECUALIKAN',
                'judul_informasi' => $dik['judul'],
                'isi_informasi' => $dik['deskripsi'],
                'pejabat_penguasa' => 'PPID Pelaksana UPT PKTJ Tegal',
                'penanggung_jawab' => $dik['penanggung_jawab'],
                'penerbit_informasi' => $dik['penanggung_jawab'],
                'bentuk_informasi' => 'Softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => $dik['waktu_pembuatan'] ?? '2025',
                'jangka_waktu' => $dik['jangka_waktu'] ?? '5 Tahun',
                'file_informasi' => $dik['file_path'],
                'aktif' => 1,
                'bisa_download' => 0,
                'is_blurred' => 1,
                'updated_at' => now(),
            ];

            if ($existing) {
                DB::table('daftar_informasis')->where('id', $existing->id)->update($dataDaftar);
            } else {
                $dataDaftar['created_at'] = now();
                DB::table('daftar_informasis')->insert($dataDaftar);
            }

            if (DB::getSchemaBuilder()->hasTable('informasi_dikecualikans')) {
                $m = DB::table('informasi_dikecualikans')->where('judul', $dik['judul'])->first();
                $mData = [
                    'judul' => $dik['judul'],
                    'deskripsi' => $dik['deskripsi'],
                    'file_path' => $dik['file_path'],
                    'penanggung_jawab' => $dik['penanggung_jawab'],
                    'dasar_hukum' => $dik['dasar_hukum'],
                    'aktif' => 1,
                    'is_blurred' => 1,
                    'bisa_download' => 0,
                    'tanggal' => date('Y-m-d'),
                    'updated_at' => now(),
                ];
                if ($m) {
                    DB::table('informasi_dikecualikans')->where('id', $m->id)->update($mData);
                } else {
                    $mData['created_at'] = now();
                    DB::table('informasi_dikecualikans')->insert($mData);
                }
            }
        }
    }
}
