---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ppid2026/Laravel-Core
    - /bin/cp -rf . $DEPLOYPATH
    - cd $DEPLOYPATH && php artisan config:clear
    - cd $DEPLOYPATH && php artisan cache:clear
    - cd $DEPLOYPATH && php artisan view:clear
    - cd $DEPLOYPATH && php artisan migrate --force