<?php

use Illuminate\Database\Migrations\Migration;
use App\Models\DaftarInformasi;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $records = [
            [
                'judul_informasi' => 'Daftar Pejabat wajib lapor LHKPN',
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'isi_informasi' => 'Daftar nama pejabat wajib lapor dan telah melaporkan LHKPN',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama masih berlaku',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Rencana Strategis (Renstra) PKTJ',
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'isi_informasi' => 'Rencana Strategis (Renstra)',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit_informasi' => 'Bagian Perencanaan',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '5 (lima) tahun',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Rencana Kerja Tahunan (RKT) PKTJ Tahun 2025',
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'isi_informasi' => 'Penjabaran dari sasaran dan program yang telah ditetapkan dalam RENSTRA dan akan dilaksanakan oleh BPSDMP',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit_informasi' => 'Bagian Perencanaan',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 (satu) tahun',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'RKA-KL PKTJ Tahun 2025',
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'isi_informasi' => 'Ringkasan rencana kerja anggaran yang berisi program dan kegiatan PKTJ',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit_informasi' => 'Bagian Perencanaan',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 (satu) tahun',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Perjanjian Kinerja (PK) PKTJ tahun 2025',
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'isi_informasi' => 'Perjanjian Kinerja merupakan rencana kinerja tahunan yang merupakan penjabaran dari RENSTRA',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit_informasi' => 'Bagian Perencanaan',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 (satu) tahun',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'DIPA INDUK PKTJ Tahun 2025',
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'isi_informasi' => 'Informasi tentang program dan kegiatan beserta anggaran PKTJ',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit_informasi' => 'Bagian Perencanaan',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 (satu) tahun',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Laporan Keuangan PKTJ',
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'isi_informasi' => 'Laporan Realisasi Anggaran (LRA), neraca, Laporan Operasional, Laporan Perubahan Ekuitas and Catatan atas Laporan Keuangan PKTJ yang telah di audit oleh BPK-RI',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit_informasi' => 'Bagian Keuangan',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 (satu) tahun',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Laporan Kinerja PKTJ',
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'isi_informasi' => 'Informasi Pelaporan Kinerja dan Tata Cara Reviu atas Laporan Kinerja Instansi Pemerintah',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit_informasi' => 'Bagian Perencanaan',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 (satu) tahun',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Laporan Tahunan',
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'isi_informasi' => 'Informasi pertanggungjawaban atas pelaksanaan kegiatan yang telah dilaksanakan unit kerja di lingkungan PKTJ',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit_informasi' => 'Bagian Perencanaan',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 (satu) tahun',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Buku Statistik',
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'isi_informasi' => 'Informasi data peserta dan lulusan pendidikan dan pelatihan perhubungan berdasarkan jenis pendidikan dan pelatihan, data tenaga pendidik dan data kapasitas prasarana diklat di PKTJ',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit_informasi' => 'Bagian Perencanaan',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 (satu) tahun',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Profil Unit Kerja di lingkungan PKTJ',
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'isi_informasi' => 'Informasi mengenai kedudukan, alamat lengkap, kontak, Gambaran umum, tupoksi',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'Website, hardcopy, dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama masih berlaku',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Profil Singkat Pejabat PKTJ',
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'isi_informasi' => 'Direktur, Wakil Direktur, Pejabat Struktural eselon 3',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'Website, softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama masih berlaku',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Peta Jabatan di Unit kerja PKTJ',
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'isi_informasi' => 'nama Jabatan Fungsional Umum dan Fungsional tertentu',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama masih berlaku',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Tarif Akademik dan Penunjang Akademik',
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'isi_informasi' => 'SK Tarif Layanan Penunjang Akademik dan Layanan Akademik, serta PMK Tarif PKTJ',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 (satu) tahun',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'PMK PSAK PKTJ',
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'isi_informasi' => 'Penyampaian Salinan Keputusan Menteri Perhubungan pada Satker BLU PKTJ',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama masih berlaku',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Penetapan Remunerasi Pejabat Pengelola, Dewas dan Pegawai di lingkungan PKTJ',
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'isi_informasi' => 'KMK Remunerasi',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Keuangan',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama masih berlaku',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Informasi pendidikan dan pelatihan yang diselenggarakan',
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'isi_informasi' => 'Informasi terkait kriteria umum program diklat, waktu pelaksanaan, lama diklat, persyaratan diklat, dan biaya',
                'pejabat_penguasa' => 'Ketua Kelompok Kerja Diklat',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 (satu) tahun',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Panduan pendaftaran pendidikan dan pelatihan yang diselenggarakan',
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'isi_informasi' => 'Informasi mengenai alur pendaftaran, tata cara pendaftaran dan panduan pembayaran biaya pendaftaran',
                'pejabat_penguasa' => 'Ketua Kelompok Kerja Diklat',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => '1 (satu) tahun',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Informasi tentang biaya pendidikan dan pelatihan bidang transportasi darat',
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'isi_informasi' => 'Biaya Layanan Pendidikan dan Pelatihan Perhubungan',
                'pejabat_penguasa' => 'Ketua Tim Sub. Bidang Administrasi Ketarunaan dan Alumni',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama masih berlaku',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Struktur PPID Pelaksana UPT PKTJ',
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'isi_informasi' => 'Struktur PPID di lingkungan PKTJ',
                'pejabat_penguasa' => 'Unit Pengembangan Usaha',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ Satker BLU',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama masih berlaku',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Kalender kegiatan akademik dalam satu tahun ajaran',
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'isi_informasi' => 'Kalender akademik',
                'pejabat_penguasa' => 'PPID',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama masih berlaku',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Berisi rekapitulasi PPID Pelaksana UPT beserta SK Pembentukannya',
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'isi_informasi' => 'Rekapitulasi PPID Pelaksana UPT',
                'pejabat_penguasa' => 'PPID',
                'penerbit_informasi' => 'Kabag Umum',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama masih berlaku',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Berisi tentang SK tentang Kurikulum Pendidikan Tinggi masing-masing Program Studi di PKTJ',
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'isi_informasi' => 'Dokumen Kurikulum',
                'pejabat_penguasa' => 'Ka. Prodi',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2019',
                'jangka_waktu' => 'Selama masih berlaku',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Berisi tentang Jadwal Rencana Diklat Teknis di PKTJ',
                'kategori' => 'informasi-berkala',
                'tipe_informasi' => 'berkala',
                'isi_informasi' => 'Jadwal Diklat Teknis',
                'pejabat_penguasa' => 'Ketua Kelompok Kerja Diklat',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'Selama masih berlaku',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Buku pedoman pengasuhan taruna',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Buku yang memuat berbagai tata cara, aturan, ketentuan dalam pengasuhan Taruna PKTJ',
                'pejabat_penguasa' => 'Kapus Pembangunan Karakter',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'selama masih berlaku',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Ringkasan atau statistik peserta diklat',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Berisi informasi jumlah dan nama peserta diklat',
                'pejabat_penguasa' => 'Ketua Kelompok Kerja Diklat',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'hingga terdapat pemutakhiran',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Daftar nama Fungsional Instruktur',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Berisi informasi jumlah dan nama instruktur PKTJ',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'hingga terdapat pemutakhiran',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Daftar nama Fungsional Dosen',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Berisi informasi jumlah dan nama dosen PKTJ',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'hingga terdapat pemutakhiran',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Kurikulum dan Silabus Pendidikan dan Pelatihan Perhubungan',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Kurikulum dan Silabus pendidikan dan pelatihan bidang transportasi darat',
                'pejabat_penguasa' => 'Ka. Prodi',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2019',
                'jangka_waktu' => 'hingga terdapat pemutakhiran',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Daftar barang ruangan',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Informasi mengenai jenis dan jumlah barang yang terdapat disetiap ruangan',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Daftar stok opname ATK',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Informasi mengenai ketersediaan ATK (jumlah keluar dan masuknya ATK)',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'aplikasi',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'hingga terdapat pemutakhiran',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Dokumentasi kegiatan Pimpinan unit kerja PKTJ',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Foto kegiatan Pimpinan PKTJ',
                'pejabat_penguasa' => 'Humas/PPID',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'selama masih berlaku',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Dokumentasi Sarana dan Prasarana Diklat PKTJ',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Foto Sarana dan Prasarana Diklat di lingkungan PKTJ',
                'pejabat_penguasa' => 'Humas/PPID',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'selama masih berlaku',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Ortaker Unit Kerja di lingkungan PKTJ',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Susunan organisasi dan tata kerja unit kerja di lingkungan PKTJ yang disahkan melalui Peraturan Menteri Perhubungan',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Peraturan, keputusan, dan kebijakan Direktur PKTJ',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Informasi mengenai peraturan, keputusan, instruksi dan surat edaran Direktur PKTJ',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'selama masih digunakan dan/ atau belum ada penggantinya',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Keputusan Kepala Unit Kerja PKTJ',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Informasi mengenai Keputusan kepala Unit Kerja di lingkungan PKTJ',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'selama masih digunakan dan/ atau belum ada penggantinya',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Perjanjian dengan Pihak Ketiga',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Informasi Perjanjian/ kesepakatan bersama antara PKTJ dengan pihak lain',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang Kerjasama dan Pengembangan Usaha',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'selama masih berlaku',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Daftar rekapan PNS dan Pegawai non PNS di lingkungan PKTJ',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'berisi informasi jumlah dan nama pegawai aktif',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'hingga terdapat pemutakhiran',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Daftar nominatif pegawai PKTJ',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'daftar nominatif pegawai berdasarkan jabatan',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'hingga terdapat pemutakhiran',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Laporan data perbendaharaan dan inventaris unit kerja di PKTJ',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'berisi informasi mengenai mutasi tambah kurang, penyusutan, penetapan status penggunaan, penghapusan BMN di PKTJ yang telah diaudit oleh BPK-RI',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'SOP tata naskah dan persuratan',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'informasi mengenai aturansistem administrasi perkantoran, kode klasifikasi arsip, dan tata naskah dinas',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'aplikasi',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'selama masih digunakan dan/ atau belum ada penggantinya',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Daftar penomoran surat di PKTJ',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Informasi mengenai surat menyurat, proses penomoran surat masuk, surat keluar, nota dinas, peraturan/ keputusan direktur, serta keputusan KPA',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'softcopy dan hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Daftar arsip unit kerja di lingkungan PKTJ',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Informasi mengenai penataan dokumen yang tersimpan menurut bagian di dalam ruang arsip yang tersedia',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Data Operasional Perkantoran unit kerja di lingkungan PKTJ',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Informasi penyelenggaraan operasional dan pemeliharaan perkantoran',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Data inventaris kendaraan bermotor',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Informasi mengenai tahun, jenis, pemegang kendaraan serta BPKB dan STNK kendaraan operasional roda 4 dan roda 2',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2023, 2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Data inventaris peralatan kantor',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Label informasi mengenai tahun pengadaan barang yang terdapat dalam suatu ruangan',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Dokumen terkait bantuan tugas belajar',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Pelaksanaan kegiatan bantuan tugas belajar',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Dokumen terkait Beasiswa',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Pelaksanaan kegiatan pemberian beasiswa',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Dokumen terkait Assesment Jabatan Struktural',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Pelaksanaan kegiatan Assesment Jabatan Struktural',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Dokumen terkait Assesment Dosen',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Pelaksanaan kegiatan Assesment Dosen',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Dokumen terkait Ujian Dinas',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Pelaksanaan kegiatan Ujian Dinas',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Surat Menyurat',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Surat menyurat terkait tupoksi unit kerja di lingkungan PKTJ',
                'pejabat_penguasa' => 'Analis SDM Aparatur Ahli Muda',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Daftar Absensi perpustakaan',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Absensi pengunjung Perpustakaan',
                'pejabat_penguasa' => 'Unit Perpustakaan',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Daftar Inventarisasi Buku',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Daftar inventaris buku perpustakaan',
                'pejabat_penguasa' => 'Unit Perpustakaan',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Daftar Judul Buku',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Daftar judul buku yang tersedia di perpustakaan',
                'pejabat_penguasa' => 'Unit Perpustakaan',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Daftar Inventarisasi Laboratorium CBT',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Daftar inventaris laboratorium CBT',
                'pejabat_penguasa' => 'Unit IT',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Daftar Absensi Laboratorium CBT',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Absensi pengunjung Laboratorium CBT',
                'pejabat_penguasa' => 'Unit IT',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Daftar Inventarisasi Laboratorium',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Daftar inventaris kelengkapan sarana di laboratorium pengujian',
                'pejabat_penguasa' => 'Unit Laboratorium',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Daftar Absensi Laboratorium',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Daftar absensi pengunjung laboratorium pengujian',
                'pejabat_penguasa' => 'Unit Laboratorium',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Daftar Inventarisasi Laboratorium Bahasa',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Daftar inventaris laboratorium bahasa',
                'pejabat_penguasa' => 'Unit Laboratorium bahasa',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Daftar Absensi Laboratorium Bahasa',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Absensi pengunjung laboratorium bahasa',
                'pejabat_penguasa' => 'Unit Laboratorium bahasa',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Daftar Inventaris Asrama',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Daftar inventaris masing-masing asrama',
                'pejabat_penguasa' => 'Unit Asrama',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Daftar Asrama Dan Kapasitas',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Daftar Jumlah Asrama dan Kapasitas masing-masing asrama',
                'pejabat_penguasa' => 'Unit Asrama',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Daftar obat-obatan Poliklinik',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Informasi tentang obat-obatan meliputi kegunaan obat, kandungan dalam obat, aturan pemakaian, indikasi, peringatan obat',
                'pejabat_penguasa' => 'Ka Unit Poliklinik',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'hingga terdapat pemutakhiran',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Tarif BLU di lingkungan PKTJ',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Informasi jenis dan tarif layanan BLU (sesuai PMK yang diterbitkan oleh Kementerian Keuangan)',
                'pejabat_penguasa' => 'Ka Unit Pengembangan Usaha',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'hingga terdapat pemutakhiran',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Tarif PNBP Diklat dan Sarana Prasarana',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Tarif PNBP yang telah disahkan oleh Kemenkeu RI',
                'pejabat_penguasa' => 'Ka Unit Pengembangan Usaha',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'hingga terdapat pemutakhiran',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Dokumen hasil penelitian dosen, instruktur, dan/atau Taruna (peserta diklat)',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Dokumen hasil penelitian yang dilakukan oleh dosen, instruktur, dan/atau Taruna PKTJ',
                'pejabat_penguasa' => 'Kapus P3M',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2024',
                'jangka_waktu' => 'hingga terdapat pemutakhiran',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Pedoman Mutu',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Dokumentasi yang berisi pernyataan dan komitmen organisasi yang menggambarkan latar belakang, kebijakan, dan sasaran organisasi',
                'pejabat_penguasa' => 'Kepala Satuan Penjamin Mutu',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Dokumen dewan pengawas',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Informasi tentang anggota dewan pengawas',
                'pejabat_penguasa' => 'Ketua SPI',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2024',
                'jangka_waktu' => 'sesuai retensi arsip',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Tata tertib asrama',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Tata tertib di lingkungan asrama',
                'pejabat_penguasa' => 'Ka. Pusbangkar/Kepala Unit Asrama',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2024, 2025',
                'jangka_waktu' => 'selama masih digunakan dan/ atau belum ada penggantinya',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Daftar Informasi Publik',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Daftar informasi yang disediakan oleh unit kerja PKTJ',
                'pejabat_penguasa' => 'PPID',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'hingga terdapat pemutakhiran',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Alur Prosedur Pelayanan Informasi',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'SOP Permohonan Informasi Publik sesuai dengan PM 46 tahun 2018',
                'pejabat_penguasa' => 'PPID',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'selama masih digunakan dan/ atau belum ada penggantinya',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Tata cara permohonan informasi publik dan pengajuan keberatan informasi publik',
                'kategori' => 'informasi-setiap-saat',
                'tipe_informasi' => 'setiapsaat',
                'isi_informasi' => 'Mekanisme permohonan informasi dan pengajuan keberatan informasi publik',
                'pejabat_penguasa' => 'PPID',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2025',
                'jangka_waktu' => 'selama masih digunakan dan/ atau belum ada penggantinya',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Pengumuman hasil seleksi TPA Sipencatar',
                'kategori' => 'informasi-serta-merta',
                'tipe_informasi' => 'sertamerta',
                'isi_informasi' => 'Informasi peserta Sipencatar yang lulus seleksi TPA',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang administrasi akademik',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2024',
                'jangka_waktu' => 'selama masih berlaku',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Pengumuman hasil seleksi akhir sipencatar',
                'kategori' => 'informasi-serta-merta',
                'tipe_informasi' => 'sertamerta',
                'isi_informasi' => 'Informasi peserta Sipencatar yang lulus hasil pantukhir dan diterima sebagai calon Mahasiswa/i',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang administrasi akademik',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2024',
                'jangka_waktu' => 'selama masih berlaku',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Pengumuman hasil seleksi Kesehatan Sipencatar',
                'kategori' => 'informasi-serta-merta',
                'tipe_informasi' => 'sertamerta',
                'isi_informasi' => 'Informasi peserta Sipencatar yang lulus seleksi Kesehatan',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang administrasi akademik',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2024',
                'jangka_waktu' => 'selama masih berlaku',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Panduan Pendaftaran Sipencatar',
                'kategori' => 'informasi-serta-merta',
                'tipe_informasi' => 'sertamerta',
                'isi_informasi' => 'Informasi mengenai alur pendaftaran, tatacara pendaftaran, dan panduan pembayaran biaya pendaftaran',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang administrasi akademik',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2024',
                'jangka_waktu' => '1 (satu) tahun',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Informasi Sipencatar',
                'kategori' => 'informasi-serta-merta',
                'tipe_informasi' => 'sertamerta',
                'isi_informasi' => 'Informasi terkait kriteria umum pendaftar, lokasi tes, jadwal seleksi, program studi, biaya seleksi, persyaratan ijazah dll',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang administrasi akademik',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2024',
                'jangka_waktu' => '1 (satu) tahun',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Pengumuman hasil seleksi Psikologi Sipencatar',
                'kategori' => 'informasi-serta-merta',
                'tipe_informasi' => 'sertamerta',
                'isi_informasi' => 'Informasi peserta Sipencatar yang lulus seleksi Psikologi',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang administrasi akademik',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2024',
                'jangka_waktu' => 'selama masih berlaku',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
            [
                'judul_informasi' => 'Pengumuman hasil selekasi akhir sipencatar',
                'kategori' => 'informasi-serta-merta',
                'tipe_informasi' => 'sertamerta',
                'isi_informasi' => 'Informasi peserta Sipencatar yang lulus hasil pantukhir dan diterima sebagai calon taruna',
                'pejabat_penguasa' => 'Ketua Tim Substansi Bidang administrasi akademik',
                'penerbit_informasi' => 'Unit Kerja di lingkungan PKTJ',
                'bentuk_informasi' => 'hardcopy dan softcopy',
                'tempat_pembuatan' => 'Tegal',
                'waktu_pembuatan' => '2024',
                'jangka_waktu' => 'selama masih berlaku',
                'penanggung_jawab' => 'PPID Pelaksana UPT PKTJ',
                'aktif' => true,
            ],
        ];

        foreach ($records as $record) {
            DaftarInformasi::updateOrCreate(
                [
                    'judul_informasi' => $record['judul_informasi'],
                    'kategori'        => $record['kategori']
                ],
                $record
            );
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // Don't delete in down to prevent data loss
    }
};
