<?php

use Illuminate\Database\Migrations\Migration;
use App\Models\InformasiDikecualikan;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $records = [
            [
                'judul'               => 'Dokumen Hasil Penilaian Proses Penetapan Seleksi Penerimaan Calon Mahasiswa/i',
                'deskripsi'           => 'Dokumen rincian hasil penilaian proses penetapan seleksi Penerimaan Calon Mahasiswa/i',
                'tanggal'             => '2025-09-19',
                'dasar_hukum'         => 'Pasal 17 huruf h angka 4: informasi publik yang apabila dibuka dan diberikan kepada pemohon informasi publik dapat mengungkap rahasia pribadi yaitu hasil-hasil evaluasi sehubungan dengan kapabilitas, intelektualitas, dan rekomendasi kemampuan seseorang',
                'konsekuensi_dibuka'  => 'Dapat mengungkap rahasia pribadi seseorang mengenai hasil evaluasi kapabilitas, intelektualitas, dan rekomendasi kemampuannya.',
                'konsekuensi_ditutup' => 'Melindungi kerahasiaan dan privasi data pribadi peserta seleksi dari akses pihak ketiga yang tidak berkepentingan.',
                'jangka_waktu'        => '1 Tahun',
                'penanggung_jawab'    => 'PPID Pelaksana UPT PKTJ',
                'file_path'           => 'https://drive.google.com/file/d/1OsgYkgEeCjHrSRn5lU5wMdz-h0YrA3mR/view?usp=sharing',
                'file_name'           => 'Daftar Informasi Dikecualikan (PDF)',
                'file_size'           => '-',
                'file_type'           => 'gdrive',
                'aktif'               => true,
                'is_blurred'          => false,
            ],
            [
                'judul'               => 'Realisasi Belanja',
                'deskripsi'           => 'Pengeluaran Belanja BLU PKTJ',
                'tanggal'             => '2025-09-19',
                'dasar_hukum'         => 'Pasal 17 huruf h angka 3: kondisi keuangan, aset, pendapatan, dan rekening bank seseorang',
                'konsekuensi_dibuka'  => 'Dapat mengungkap kondisi keuangan, aset, pendapatan, dan rekening bank pribadi seseorang yang bersifat rahasia.',
                'konsekuensi_ditutup' => 'Menjaga kerahasiaan data finansial pribadi pegawai/pihak terkait sesuai ketentuan perlindungan privasi.',
                'jangka_waktu'        => '1 Tahun',
                'penanggung_jawab'    => 'PPID Pelaksana UPT PKTJ',
                'file_path'           => 'https://drive.google.com/file/d/1OsgYkgEeCjHrSRn5lU5wMdz-h0YrA3mR/view?usp=sharing',
                'file_name'           => 'Daftar Informasi Dikecualikan (PDF)',
                'file_size'           => '-',
                'file_type'           => 'gdrive',
                'aktif'               => true,
                'is_blurred'          => false,
            ],
            [
                'judul'               => 'Nilai Tes Siswa Diklat',
                'deskripsi'           => 'Berisi Daftar Nilai Tes Siswa Diklat',
                'tanggal'             => '2025-09-19',
                'dasar_hukum'         => 'Pasal 17 huruf h angka 4: informasi publik yang apabila dibuka dan diberikan kepada pemohon informasi publik dapat mengungkap rahasia pribadi yaitu hasil-hasil evaluasi sehubungan dengan kapabilitas, intelektualitas, dan rekomendasi kemampuan seseorang',
                'konsekuensi_dibuka'  => 'Dapat mempublikasikan hasil evaluasi kemampuan pribadi siswa diklat tanpa hak.',
                'konsekuensi_ditutup' => 'Melindungi privasi hasil evaluasi intelektual dan kemampuan akademik siswa.',
                'jangka_waktu'        => '1 Tahun / Diberikan jika ada persetujuan tertulis dari pihak/CPNS yang bersangkutan',
                'penanggung_jawab'    => 'PPID Pelaksana UPT PKTJ',
                'file_path'           => 'https://drive.google.com/file/d/1OsgYkgEeCjHrSRn5lU5wMdz-h0YrA3mR/view?usp=sharing',
                'file_name'           => 'Daftar Informasi Dikecualikan (PDF)',
                'file_size'           => '-',
                'file_type'           => 'gdrive',
                'aktif'               => true,
                'is_blurred'          => false,
            ],
            [
                'judul'               => 'Nilai Tes Mahasiswa/i',
                'deskripsi'           => 'Berisi Daftar Nilai Tes Mahasiswa',
                'tanggal'             => '2025-09-19',
                'dasar_hukum'         => 'Pasal 17 huruf h angka 4: informasi publik yang apabila dibuka dan diberikan kepada pemohon informasi publik dapat mengungkap rahasia pribadi yaitu hasil-hasil evaluasi sehubungan dengan kapabilitas, intelektualitas, dan rekomendasi kemampuan seseorang',
                'konsekuensi_dibuka'  => 'Dapat menyebarluaskan riwayat akademik dan nilai evaluasi personal mahasiswa.',
                'konsekuensi_ditutup' => 'Menjamin perlindungan data pribadi mahasiswa terkait hasil evaluasi akademik.',
                'jangka_waktu'        => '1 Tahun / Diberikan jika ada persetujuan tertulis dari pihak/CPNS yang bersangkutan',
                'penanggung_jawab'    => 'PPID Pelaksana UPT PKTJ',
                'file_path'           => 'https://drive.google.com/file/d/1OsgYkgEeCjHrSRn5lU5wMdz-h0YrA3mR/view?usp=sharing',
                'file_name'           => 'Daftar Informasi Dikecualikan (PDF)',
                'file_size'           => '-',
                'file_type'           => 'gdrive',
                'aktif'               => true,
                'is_blurred'          => false,
            ],
            [
                'judul'               => 'Hasil Proses Penjatuhan Hukuman',
                'deskripsi'           => 'Hasil dari Proses Penjatuhan Hukuman Disiplin bagi pegawai',
                'tanggal'             => '2025-09-19',
                'dasar_hukum'         => 'Undang-Undang No.8 Tahun 1981 tentang Hukum Acara Pidana, Undang-Undang No. 43 Tahun 2009 tentang Kearsipan',
                'konsekuensi_dibuka'  => 'Dapat mengganggu proses penegakan disiplin dan mencemarkan nama baik pegawai sebelum adanya keputusan yang berkekuatan hukum tetap.',
                'konsekuensi_ditutup' => 'Menjaga objektivitas proses hukum disiplin dan melindungi hak-hak kepegawaian selama proses berjalan.',
                'jangka_waktu'        => 'Dibuka setelah ada keputusan tetap dari pimpinan Politeknik Keselamatan Transportasi Jalan',
                'penanggung_jawab'    => 'PPID Pelaksana UPT Politeknik Keselamatan Transportasi Jalan',
                'file_path'           => 'https://drive.google.com/file/d/1OsgYkgEeCjHrSRn5lU5wMdz-h0YrA3mR/view?usp=sharing',
                'file_name'           => 'Daftar Informasi Dikecualikan (PDF)',
                'file_size'           => '-',
                'file_type'           => 'gdrive',
                'aktif'               => true,
                'is_blurred'          => false,
            ],
            [
                'judul'               => 'Rekam Medis Calon Mahasiswa/i, dan Pegawai di Lingkungan PKTJ',
                'deskripsi'           => 'Data rekam medis Calon Mahasiswa/i',
                'tanggal'             => '2025-09-19',
                'dasar_hukum'         => 'Pasal 17 huruf h angka 2: informasi publik yang apabila dibuka dan diberikan kepada pemohon informasi publik dapat mengungkap rahasia pribadi yaitu riwayat, kondisi dan perawatan, pengobatan kesehatan fisik, dan psikis seseorang',
                'konsekuensi_dibuka'  => 'Mengungkap kondisi kesehatan fisik dan psikis yang sangat bersifat pribadi dan sensitif.',
                'konsekuensi_ditutup' => 'Menjaga kerahasiaan medis pasien sesuai etika kedokteran dan hukum perlindungan konsumen/pasien.',
                'jangka_waktu'        => '1 Tahun / Diberikan jika ada persetujuan tertulis dari pihak yang bersangkutan',
                'penanggung_jawab'    => 'PPID Pelaksana UPT PKTJ',
                'file_path'           => 'https://drive.google.com/file/d/1OsgYkgEeCjHrSRn5lU5wMdz-h0YrA3mR/view?usp=sharing',
                'file_name'           => 'Daftar Informasi Dikecualikan (PDF)',
                'file_size'           => '-',
                'file_type'           => 'gdrive',
                'aktif'               => true,
                'is_blurred'          => false,
            ],
            [
                'judul'               => 'Analisis dan Hasil Audit Internal',
                'deskripsi'           => 'Kegiatan analisis dan hasil audit SPI, SPM dan Inspektorat',
                'tanggal'             => '2025-09-19',
                'dasar_hukum'         => 'Pasal 17 huruf h angka 3: kondisi keuangan, aset, pendapatan, dan rekening bank seseorang; Undang-Undang No.15 Tahun 2004 tentang Pemeriksaan Pengelolaan dan Tanggung Jawab Keuangan Negara',
                'konsekuensi_dibuka'  => 'Dapat menimbulkan kesalahpahaman publik terhadap proses evaluasi internal yang belum bersifat final.',
                'konsekuensi_ditutup' => 'Memberikan ruang bagi tim auditor internal untuk bekerja secara independen dan menyusun rekomendasi perbaikan sebelum dipublikasikan secara resmi.',
                'jangka_waktu'        => '1 Tahun',
                'penanggung_jawab'    => 'PPID Pelaksana UPT PKTJ',
                'file_path'           => 'https://drive.google.com/file/d/1OsgYkgEeCjHrSRn5lU5wMdz-h0YrA3mR/view?usp=sharing',
                'file_name'           => 'Daftar Informasi Dikecualikan (PDF)',
                'file_size'           => '-',
                'file_type'           => 'gdrive',
                'aktif'               => true,
                'is_blurred'          => false,
            ],
            [
                'judul'               => 'Hasil Proses Penjatuhan Hukuman Pegawai',
                'deskripsi'           => 'Hasil dari Proses Penjatuhan Hukuman Disiplin bagi pegawai',
                'tanggal'             => '2025-09-19',
                'dasar_hukum'         => 'Undang-Undang No.8 Tahun 1981 tentang Hukum Acara Pidana, Undang-Undang No. 43 Tahun 2009 tentang Kearsipan',
                'konsekuensi_dibuka'  => 'Dapat mengganggu penegakan tata tertib disiplin di lingkungan institusi sebelum ada keputusan yang inkrah.',
                'konsekuensi_ditutup' => 'Melindungi nama baik pegawai dan menjaga kerahasiaan berkas kepegawaian internal.',
                'jangka_waktu'        => '1 Tahun / Dibuka setelah ada keputusan tetap dari pimpinan PKTJ',
                'penanggung_jawab'    => 'PPID Pelaksana UPT PKTJ',
                'file_path'           => 'https://drive.google.com/file/d/1OsgYkgEeCjHrSRn5lU5wMdz-h0YrA3mR/view?usp=sharing',
                'file_name'           => 'Daftar Informasi Dikecualikan (PDF)',
                'file_size'           => '-',
                'file_type'           => 'gdrive',
                'aktif'               => true,
                'is_blurred'          => false,
            ],
            [
                'judul'               => 'Analisis dan Hasil Audit External',
                'deskripsi'           => 'Kegiatan analisis dan hasil audit KAP dan BPK',
                'tanggal'             => '2025-09-19',
                'dasar_hukum'         => 'Pasal 17 huruf h angka 3: kondisi keuangan, aset, pendapatan, dan rekening bank seseorang; Undang-Undang No.15 Tahun 2004 tentang Pemeriksaan Pengelolaan dan Tanggung Jawab Keuangan Negara',
                'konsekuensi_dibuka'  => 'Dapat memicu interpretasi keliru terhadap laporan keuangan sebelum selesainya audit formal.',
                'konsekuensi_ditutup' => 'Menjaga objektivitas pemeriksaan laporan keuangan eksternal oleh BPK/KAP.',
                'jangka_waktu'        => '1 Tahun',
                'penanggung_jawab'    => 'PPID Pelaksana UPT PKTJ',
                'file_path'           => 'https://drive.google.com/file/d/1OsgYkgEeCjHrSRn5lU5wMdz-h0YrA3mR/view?usp=sharing',
                'file_name'           => 'Daftar Informasi Dikecualikan (PDF)',
                'file_size'           => '-',
                'file_type'           => 'gdrive',
                'aktif'               => true,
                'is_blurred'          => false,
            ],
            [
                'judul'               => 'POK PKTJ',
                'deskripsi'           => 'Berisi tentang Dokumen yang memuat uraian kerja dan biaya yang diperlukan PKTJ',
                'tanggal'             => '2025-09-19',
                'dasar_hukum'         => 'Pasal 17 huruf h angka 3: kondisi keuangan, aset, pendapatan, dan rekening bank seseorang',
                'konsekuensi_dibuka'  => 'Membuka rincian alokasi anggaran internal secara mendalam kepada pihak luar yang berpotensi disalahgunakan.',
                'konsekuensi_ditutup' => 'Melindungi rincian rencana keuangan internal dan efisiensi pengeluaran institusi.',
                'jangka_waktu'        => '1 Tahun',
                'penanggung_jawab'    => 'PPID Pelaksana UPT PKTJ',
                'file_path'           => 'https://drive.google.com/file/d/1OsgYkgEeCjHrSRn5lU5wMdz-h0YrA3mR/view?usp=sharing',
                'file_name'           => 'Daftar Informasi Dikecualikan (PDF)',
                'file_size'           => '-',
                'file_type'           => 'gdrive',
                'aktif'               => true,
                'is_blurred'          => false,
            ],
            [
                'judul'               => 'Realisasi Penerimaan',
                'deskripsi'           => 'Pendapatan BLU PKTJ',
                'tanggal'             => '2025-09-19',
                'dasar_hukum'         => 'Pasal 17 huruf h angka 3: kondisi keuangan, aset, pendapatan, dan rekening bank seseorang',
                'konsekuensi_dibuka'  => 'Mengungkap data aliran dana masuk secara mendetail yang dapat disalahgunakan.',
                'konsekuensi_ditutup' => 'Menjaga integritas data finansial penerimaan negara bukan pajak (PNBP) / BLU.',
                'jangka_waktu'        => '1 Tahun',
                'penanggung_jawab'    => 'PPID Pelaksana UPT PKTJ',
                'file_path'           => 'https://drive.google.com/file/d/1OsgYkgEeCjHrSRn5lU5wMdz-h0YrA3mR/view?usp=sharing',
                'file_name'           => 'Daftar Informasi Dikecualikan (PDF)',
                'file_size'           => '-',
                'file_type'           => 'gdrive',
                'aktif'               => true,
                'is_blurred'          => false,
            ],
            [
                'judul'               => 'Rekam Medis Calon Taruna, Taruna, dan Pegawai di Lingkungan Politeknik Keselamatan Transportasi Jalan',
                'deskripsi'           => 'Data rekam medis Calon Tarun',
                'tanggal'             => '2025-09-19',
                'dasar_hukum'         => 'Pasal 17 huruf h angka 2 : informasi publik yang apabila dibuka dan diberikan kepada pemohon informasi publik dapat mengungkap rahasia pribadi yaitu riwayat, kondisi dan perawatan, pengobatan kesehatan fisik, dan psikis seseorang',
                'konsekuensi_dibuka'  => 'Dapat menyebarkan riwayat medis personal yang sangat rahasia tanpa persetujuan.',
                'konsekuensi_ditutup' => 'Menjaga hak kerahasiaan pasien dan integritas riwayat medis pegawai/taruna.',
                'jangka_waktu'        => 'Diberikan jika ada persetujuan tertulis dari pihak yang bersangkutan',
                'penanggung_jawab'    => 'PPID Pelaksana UPT Politeknik Keselamatan Transportasi Jalan',
                'file_path'           => 'https://drive.google.com/file/d/1OsgYkgEeCjHrSRn5lU5wMdz-h0YrA3mR/view?usp=sharing',
                'file_name'           => 'Daftar Informasi Dikecualikan (PDF)',
                'file_size'           => '-',
                'file_type'           => 'gdrive',
                'aktif'               => true,
                'is_blurred'          => false,
            ],
        ];

        foreach ($records as $record) {
            InformasiDikecualikan::updateOrCreate(
                ['judul' => $record['judul']],
                $record
            );
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // Opt to not delete in down to prevent accidental data loss
    }
};
