import json

extracted_file = "scratch/D1_extracted.txt"
output_php_file = "scratch/D1_records.php"

# Let's define the records manually or parse them.
# Given the complex layout, it is much safer and more accurate to write a parser
# or structure the lists manually in Python using the extracted text as reference,
# then export it to PHP.
# Let's inspect the text and write the records in Python.

berkala_records = [
    {
        "judul_informasi": "Daftar Pejabat wajib lapor LHKPN",
        "kategori": "informasi-berkala",
        "tipe_informasi": "berkala",
        "isi_informasi": "Daftar nama pejabat wajib lapor dan telah melaporkan LHKPN",
        "pejabat_penguasa": "Ketua Tim Substansi Bidang Keuangan",
        "penerbit_informasi": "Unit Kerja di lingkungan PKTJ",
        "bentuk_informasi": "softcopy dan hardcopy",
        "tempat_pembuatan": "Tegal",
        "waktu_pembuatan": "2025",
        "jangka_waktu": "Selama masih berlaku",
        "penanggung_jawab": "PPID Pelaksana UPT PKTJ",
        "aktif": True
    },
    {
        "judul_informasi": "Rencana Strategis (Renstra) PKTJ",
        "kategori": "informasi-berkala",
        "tipe_informasi": "berkala",
        "isi_informasi": "Rencana Strategis (Renstra)",
        "pejabat_penguasa": "Ketua Tim Substansi Bidang Keuangan",
        "penerbit_informasi": "Bagian Perencanaan",
        "bentuk_informasi": "softcopy dan hardcopy",
        "tempat_pembuatan": "Tegal",
        "waktu_pembuatan": "2025",
        "jangka_waktu": "5 (lima) tahun",
        "penanggung_jawab": "PPID Pelaksana UPT PKTJ",
        "aktif": True
    },
    {
        "judul_informasi": "Rencana Kerja Tahunan (RKT) PKTJ Tahun 2025",
        "kategori": "informasi-berkala",
        "tipe_informasi": "berkala",
        "isi_informasi": "Penjabaran dari sasaran dan program yang telah ditetapkan dalam RENSTRA dan akan dilaksanakan oleh BPSDMP",
        "pejabat_penguasa": "Ketua Tim Substansi Bidang Keuangan",
        "penerbit_informasi": "Bagian Perencanaan",
        "bentuk_informasi": "softcopy dan hardcopy",
        "tempat_pembuatan": "Tegal",
        "waktu_pembuatan": "2025",
        "jangka_waktu": "1 (satu) tahun",
        "penanggung_jawab": "PPID Pelaksana UPT PKTJ",
        "aktif": True
    },
    {
        "judul_informasi": "RKA-KL PKTJ Tahun 2025",
        "kategori": "informasi-berkala",
        "tipe_informasi": "berkala",
        "isi_informasi": "Ringkasan rencana kerja anggaran yang berisi program dan kegiatan PKTJ",
        "pejabat_penguasa": "Ketua Tim Substansi Bidang Keuangan",
        "penerbit_informasi": "Bagian Perencanaan",
        "bentuk_informasi": "softcopy dan hardcopy",
        "tempat_pembuatan": "Tegal",
        "waktu_pembuatan": "2025",
        "jangka_waktu": "1 (satu) tahun",
        "penanggung_jawab": "PPID Pelaksana UPT PKTJ",
        "aktif": True
    },
    {
        "judul_informasi": "Perjanjian Kinerja (PK) PKTJ tahun 2025",
        "kategori": "informasi-berkala",
        "tipe_informasi": "berkala",
        "isi_informasi": "Perjanjian Kinerja merupakan rencana kinerja tahunan yang merupakan penjabaran dari RENSTRA",
        "pejabat_penguasa": "Ketua Tim Substansi Bidang Keuangan",
        "penerbit_informasi": "Bagian Perencanaan",
        "bentuk_informasi": "softcopy dan hardcopy",
        "tempat_pembuatan": "Tegal",
        "waktu_pembuatan": "2025",
        "jangka_waktu": "1 (satu) tahun",
        "penanggung_jawab": "PPID Pelaksana UPT PKTJ",
        "aktif": True
    },
    {
        "judul_informasi": "DIPA INDUK PKTJ Tahun 2025",
        "kategori": "informasi-berkala",
        "tipe_informasi": "berkala",
        "isi_informasi": "Informasi tentang program dan kegiatan beserta anggaran PKTJ",
        "pejabat_penguasa": "Ketua Tim Substansi Bidang Keuangan",
        "penerbit_informasi": "Bagian Perencanaan",
        "bentuk_informasi": "softcopy dan hardcopy",
        "tempat_pembuatan": "Tegal",
        "waktu_pembuatan": "2025",
        "jangka_waktu": "1 (satu) tahun",
        "penanggung_jawab": "PPID Pelaksana UPT PKTJ",
        "aktif": True
    },
    {
        "judul_informasi": "Laporan Keuangan PKTJ",
        "kategori": "informasi-berkala",
        "tipe_informasi": "berkala",
        "isi_informasi": "Laporan Realisasi Anggaran (LRA), neraca, Laporan Operasional, Laporan Perubahan Ekuitas dan Catatan atas Laporan Keuangan PKTJ yang telah di audit oleh BPK-RI",
        "pejabat_penguasa": "Ketua Tim Substansi Bidang Keuangan",
        "penerbit_informasi": "Bagian Keuangan",
        "bentuk_informasi": "softcopy dan hardcopy",
        "tempat_pembuatan": "Tegal",
        "waktu_pembuatan": "2025",
        "jangka_waktu": "1 (satu) tahun",
        "penanggung_jawab": "PPID Pelaksana UPT PKTJ",
        "aktif": True
    },
    {
        "judul_informasi": "Laporan Kinerja PKTJ",
        "kategori": "informasi-berkala",
        "tipe_informasi": "berkala",
        "isi_informasi": "Informasi Pelaporan Kinerja dan Tata Cara Reviu atas Laporan Kinerja Instansi Pemerintah",
        "pejabat_penguasa": "Ketua Tim Substansi Bidang Keuangan",
        "penerbit_informasi": "Bagian Perencanaan",
        "bentuk_informasi": "softcopy dan hardcopy",
        "tempat_pembuatan": "Tegal",
        "waktu_pembuatan": "2025",
        "jangka_waktu": "1 (satu) tahun",
        "penanggung_jawab": "PPID Pelaksana UPT PKTJ",
        "aktif": True
    },
    {
        "judul_informasi": "Laporan Tahunan",
        "kategori": "informasi-berkala",
        "tipe_informasi": "berkala",
        "isi_informasi": "Informasi pertanggungjawaban atas pelaksanaan kegiatan yang telah dilaksanakan unit kerja di lingkungan PKTJ",
        "pejabat_penguasa": "Ketua Tim Substansi Bidang Keuangan",
        "penerbit_informasi": "Bagian Perencanaan",
        "bentuk_informasi": "softcopy dan hardcopy",
        "tempat_pembuatan": "Tegal",
        "waktu_pembuatan": "2025",
        "jangka_waktu": "1 (satu) tahun",
        "penanggung_jawab": "PPID Pelaksana UPT PKTJ",
        "aktif": True
    },
    {
        "judul_informasi": "Buku Statistik",
        "kategori": "informasi-berkala",
        "tipe_informasi": "berkala",
        "isi_informasi": "Informasi data peserta dan lulusan pendidikan dan pelatihan perhubungan berdasarkan jenis pendidikan dan pelatihan, data tenaga pendidik dan data kapasitas prasarana diklat di PKTJ",
        "pejabat_penguasa": "Ketua Tim Substansi Bidang Keuangan",
        "penerbit_informasi": "Bagian Perencanaan",
        "bentuk_informasi": "softcopy dan hardcopy",
        "tempat_pembuatan": "Tegal",
        "waktu_pembuatan": "2025",
        "jangka_waktu": "1 (satu) tahun",
        "penanggung_jawab": "PPID Pelaksana UPT PKTJ",
        "aktif": True
    },
    {
        "judul_informasi": "Profil Unit Kerja di lingkungan PKTJ",
        "kategori": "informasi-berkala",
        "tipe_informasi": "berkala",
        "isi_informasi": "Informasi mengenai kedudukan, alamat lengkap, kontak, Gambaran umum, tupoksi",
        "pejabat_penguasa": "Analis SDM Aparatur Ahli Muda",
        "penerbit_informasi": "Unit Kerja di lingkungan PKTJ",
        "bentuk_informasi": "Website, hardcopy, dan softcopy",
        "tempat_pembuatan": "Tegal",
        "waktu_pembuatan": "2025",
        "jangka_waktu": "Selama masih berlaku",
        "penanggung_jawab": "PPID Pelaksana UPT PKTJ",
        "aktif": True
    },
    {
        "judul_informasi": "Profil Singkat Pejabat PKTJ",
        "kategori": "informasi-berkala",
        "tipe_informasi": "berkala",
        "isi_informasi": "Direktur, Wakil Direktur, Pejabat Struktural eselon 3",
        "pejabat_penguasa": "Analis SDM Aparatur Ahli Muda",
        "penerbit_informasi": "Unit Kerja di lingkungan PKTJ",
        "bentuk_informasi": "Website, softcopy dan hardcopy",
        "tempat_pembuatan": "Tegal",
        "waktu_pembuatan": "2025",
        "jangka_waktu": "Selama masih berlaku",
        "penanggung_jawab": "PPID Pelaksana UPT PKTJ",
        "aktif": True
    },
    {
        "judul_informasi": "Peta Jabatan di Unit kerja PKTJ",
        "kategori": "informasi-berkala",
        "tipe_informasi": "berkala",
        "isi_informasi": "nama Jabatan Fungsional Umum dan Fungsional tertentu",
        "pejabat_penguasa": "Analis SDM Aparatur Ahli Muda",
        "penerbit_informasi": "Unit Kerja di lingkungan PKTJ",
        "bentuk_informasi": "softcopy dan hardcopy",
        "tempat_pembuatan": "Tegal",
        "waktu_pembuatan": "2025",
        "jangka_waktu": "Selama masih berlaku",
        "penanggung_jawab": "PPID Pelaksana UPT PKTJ",
        "aktif": True
    },
    {
        "judul_informasi": "Tarif Akademik dan Penunjang Akademik",
        "kategori": "informasi-berkala",
        "tipe_informasi": "berkala",
        "isi_informasi": "SK Tarif Layanan Penunjang Akademik dan Layanan Akademik, serta PMK Tarif PKTJ",
        "pejabat_penguasa": "Ketua Tim Substansi Bidang Keuangan",
        "penerbit_informasi": "Unit Kerja di lingkungan PKTJ",
        "bentuk_informasi": "softcopy dan hardcopy",
        "tempat_pembuatan": "Tegal",
        "waktu_pembuatan": "2025",
        "jangka_waktu": "1 (satu) tahun",
        "penanggung_jawab": "PPID Pelaksana UPT PKTJ",
        "aktif": True
    },
    {
        "judul_informasi": "PMK PSAK PKTJ",
        "kategori": "informasi-berkala",
        "tipe_informasi": "berkala",
        "isi_informasi": "Penyampaian Salinan Keputusan Menteri Perhubungan pada Satker BLU PKTJ",
        "pejabat_penguasa": "Ketua Tim Substansi Bidang Keuangan",
        "penerbit_informasi": "Unit Kerja di lingkungan PKTJ",
        "bentuk_informasi": "softcopy dan hardcopy",
        "tempat_pembuatan": "Tegal",
        "waktu_pembuatan": "2025",
        "jangka_waktu": "Selama masih berlaku",
        "penanggung_jawab": "PPID Pelaksana UPT PKTJ",
        "aktif": True
    },
    {
        "judul_informasi": "Penetapan Remunerasi Pejabat Pengelola, Dewas dan Pegawai di lingkungan PKTJ",
        "kategori": "informasi-berkala",
        "tipe_informasi": "berkala",
        "isi_informasi": "KMK Remunerasi",
        "pejabat_penguasa": "Ketua Tim Substansi Bidang Keuangan",
        "penerbit_informasi": "Unit Kerja di lingkungan PKTJ",
        "bentuk_informasi": "softcopy dan hardcopy",
        "tempat_pembuatan": "Tegal",
        "waktu_pembuatan": "2025",
        "jangka_waktu": "Selama masih berlaku",
        "penanggung_jawab": "PPID Pelaksana UPT PKTJ",
        "aktif": True
    },
    {
        "judul_informasi": "Informasi pendidikan dan pelatihan yang diselenggarakan",
        "kategori": "informasi-berkala",
        "tipe_informasi": "berkala",
        "isi_informasi": "Informasi terkait kriteria umum program diklat, waktu pelaksanaan, lama diklat, persyaratan diklat, dan biaya",
        "pejabat_penguasa": "Ketua Kelompok Kerja Diklat",
        "penerbit_informasi": "Unit Kerja di lingkungan PKTJ",
        "bentuk_informasi": "softcopy dan hardcopy",
        "tempat_pembuatan": "Tegal",
        "waktu_pembuatan": "2025",
        "jangka_waktu": "1 (satu) tahun",
        "penanggung_jawab": "PPID Pelaksana UPT PKTJ",
        "aktif": True
    },
    {
        "judul_informasi": "Panduan pendaftaran pendidikan dan pelatihan yang diselenggarakan",
        "kategori": "informasi-berkala",
        "tipe_informasi": "berkala",
        "isi_informasi": "Informasi mengenai alur pendaftaran, tata cara pendaftaran dan panduan pembayaran biaya pendaftaran",
        "pejabat_penguasa": "Ketua Kelompok Kerja Diklat",
        "penerbit_informasi": "Unit Kerja di lingkungan PKTJ",
        "shapes": "softcopy dan hardcopy",
        "bentuk_informasi": "softcopy dan hardcopy",
        "tempat_pembuatan": "Tegal",
        "waktu_pembuatan": "2025",
        "jangka_waktu": "1 (satu) tahun",
        "penanggung_jawab": "PPID Pelaksana UPT PKTJ",
        "aktif": True
    },
    {
        "judul_informasi": "Informasi tentang biaya pendidikan dan pelatihan bidang transportasi darat",
        "kategori": "informasi-berkala",
        "tipe_informasi": "berkala",
        "isi_informasi": "Biaya Layanan Pendidikan dan Pelatihan Perhubungan",
        "pejabat_penguasa": "Ketua Tim Sub. Bidang Administrasi Ketarunaan dan Alumni",
        "penerbit_informasi": "Unit Kerja di lingkungan PKTJ",
        "bentuk_informasi": "softcopy dan hardcopy",
        "tempat_pembuatan": "Tegal",
        "waktu_pembuatan": "2025",
        "jangka_waktu": "Selama masih berlaku",
        "penanggung_jawab": "PPID Pelaksana UPT PKTJ",
        "aktif": True
    },
    {
        "judul_informasi": "Struktur PPID Pelaksana UPT PKTJ",
        "kategori": "informasi-berkala",
        "tipe_informasi": "berkala",
        "isi_informasi": "Struktur PPID di lingkungan PKTJ",
        "pejabat_penguasa": "Unit Pengembangan Usaha",
        "penerbit_informasi": "Unit Kerja di lingkungan PKTJ Satker BLU",
        "bentuk_informasi": "softcopy dan hardcopy",
        "tempat_pembuatan": "Tegal",
        "waktu_pembuatan": "2025",
        "jangka_waktu": "Selama masih berlaku",
        "penanggung_jawab": "PPID Pelaksana UPT PKTJ",
        "aktif": True
    },
    {
        "judul_informasi": "Kalender kegiatan akademik dalam satu tahun ajaran",
        "kategori": "informasi-berkala",
        "tipe_informasi": "berkala",
        "isi_informasi": "Kalender akademik",
        "pejabat_penguasa": "PPID",
        "penerbit_informasi": "Unit Kerja di lingkungan PKTJ",
        "bentuk_informasi": "softcopy dan hardcopy",
        "tempat_pembuatan": "Tegal",
        "waktu_pembuatan": "2025",
        "jangka_waktu": "Selama masih berlaku",
        "penanggung_jawab": "PPID Pelaksana UPT PKTJ",
        "aktif": True
    },
    {
        "judul_informasi": "Berisi rekapitulasi PPID Pelaksana UPT beserta SK Pembentukannya",
        "kategori": "informasi-berkala",
        "tipe_informasi": "berkala",
        "isi_informasi": "Rekapitulasi PPID Pelaksana UPT",
        "pejabat_penguasa": "PPID",
        "penerbit_informasi": "Kabag Umum",
        "bentuk_informasi": "softcopy dan hardcopy",
        "tempat_pembuatan": "Tegal",
        "waktu_pembuatan": "2025",
        "jangka_waktu": "Selama masih berlaku",
        "penanggung_jawab": "PPID Pelaksana UPT PKTJ",
        "aktif": True
    },
    {
        "judul_informasi": "Berisi tentang SK tentang Kurikulum Pendidikan Tinggi masing-masing Program Studi di PKTJ",
        "kategori": "informasi-berkala",
        "tipe_informasi": "berkala",
        "isi_informasi": "Dokumen Kurikulum",
        "pejabat_penguasa": "Ka. Prodi",
        "penerbit_informasi": "Unit Kerja di lingkungan PKTJ",
        "bentuk_informasi": "softcopy dan hardcopy",
        "tempat_pembuatan": "Tegal",
        "waktu_pembuatan": "2019",
        "jangka_waktu": "Selama masih berlaku",
        "penanggung_jawab": "PPID Pelaksana UPT PKTJ",
        "aktif": True
    },
    {
        "judul_informasi": "Berisi tentang Jadwal Rencana Diklat Teknis di PKTJ",
        "kategori": "informasi-berkala",
        "tipe_informasi": "berkala",
        "isi_informasi": "Jadwal Diklat Teknis",
        "pejabat_penguasa": "Ketua Kelompok Kerja Diklat",
        "penerbit_informasi": "Unit Kerja di lingkungan PKTJ",
        "bentuk_informasi": "softcopy dan hardcopy",
        "tempat_pembuatan": "Tegal",
        "waktu_pembuatan": "2025",
        "jangka_waktu": "Selama masih berlaku",
        "penanggung_jawab": "PPID Pelaksana UPT PKTJ",
        "aktif": True
    }
]

# Let's save the progress for berkala first, then write python code to generate the whole PHP migration
# file containing all 80 items. We'll do this page by page so we don't hit limits and stay robust.
# Let's write the code for the generator.
